src/Schema/Field.php, src/Schema/Registrars/ConnectionRegistrar.php, src/Support/Console/Commands/stubs/relay_connection.stub, src/Support/Interfaces/Connection.php, tests/Support/GraphQL/Connections/TaskConnection.php
I'm integrating this project into a work project, and I wanted to have clean connection names. I found that the default names where a bit unwieldy especially if you have your custom connections nested deep in some namespaces. No worries if you don't want to merge this in.
=> added the ability to override the default naming of custom connections.

src/Schema/SchemaBuilder.php
Allows you to do e.g.
```php
GraphQL::schema()->group(['middleware' => ['auth']], function () {
//Types
GraphQL::schema()->types([
'user'     => \App\GraphQL\Types\UserType::class,
'viewer'   => \App\GraphQL\Types\ViewerType::class,
'task'     => \App\GraphQL\Types\TaskType::class
]);
//Queries
GraphQL::schema()->queries([
'viewer' => \App\GraphQL\Queries\ViewerQuery::class
]);
//Mutations
GraphQL::schema()->mutations([
'createUser' => \App\GraphQL\Mutations\CreateUserMutation::class
]);
});
````
=> Add mass schema creation functions

src/Schema/Registrars/ConnectionRegistrar.php, src/Support/Definition/RelayConnectionType.php
Currently the connection descriptions are hard coded to `A connection to a list of items.`.
This small update allows you to add a `description(){}` method to your `Connection` to override this.
This is useful in the instance where you have several relations named in a similar fashion where the name itself is not enough to distinguish the purpose.
=> Allow setting description on Connections

.codecov.yml, .gitattributes, .travis.yml
Enable code coverage with Codecov.io
After the repo is enabled at https://codecov.io - a coverage report status will be created for each build
---
**Note:**
Codecov is free for public repositories.
=> Enable code coverage with Codecov.io.

composer.json
Set minimum PHP requirement
---
Laravel 5.2 requires PHP>=5.5.9
---
Requires https://github.com/nuwave/lighthouse/pull/33
=> Set minimum PHP requirement

.gitattributes
We need to export the assets since the `SchemaGenerator` looks for `assets/introspection-*.txt`
=> Export assets

src/Support/Http/Controllers/GraphQLController.php
@chrissm79 When I use artisan CLI command:
`php artisan route:list`
I catch error:
```
GraphQL\Error\SyntaxError  : Syntax Error GraphQL (1:1) Unexpected <EOF>
at /Users/latik/Dev/projects/lighthouse/vendor/webonyx/graphql-php/src/Language/Parser.php: 236
```
It happening because if request query is empty we put the empty string in Parser and it not a valid GraphQL query. 
I not sure that "{ empty }" string is the best decision but it works fine for this case.
=> use valid dummy graphql query if request query is empty

config/config.php, src/Support/Http/routes.php
I think its convenient to have this on users control.
Otherwise they will have to look inside your service provider or router file to find out what its meant to be happening.
If you have another reason to not do, just discard the pull request.
=> Issues saver

config/config.php, src/Schema/Directives/Fields/CanDirective.php, src/Support/Http/Controllers/GraphQLController.php, src/Support/Http/routes.php
With this Lumen does not break on getting the context.
@auth directive can't be used.
instead of using `\Auth::user()` it could be obtained from the `$request->user()`.
Im going to add full auth with passport on the lumen demo, you can take from there what you need for your documentation, no need to ask.
NOTE: tried to split the commits but obviously I forgot to roll back before last!
=> Lumen support

src/Schema/Directives/Fields/AuthDirective.php, src/Schema/Directives/Fields/CanDirective.php, src/Support/DataLoader/QueryBuilder.php, src/Support/Http/Controllers/GraphQLController.php, src/Support/Http/routes.php, src/Support/helpers.php, tests/DBTestCase.php
Hi @chrissm79,
with the help of ao @kikoseijo I managed to get things working nicely without the need for facades.
As you can see, the changes are quite minimal, I'm just not 100% sure if this won't break anyhting on the Laravel part.
I do already have a workaround in place since Laravel's Passport is also still depending on facades.  The workaround is fairly simpel though: create your own PassportServiceProvider in app/Providers, extending the Laravel Passport service provider and override the offending methods `registerGuard()`, `makeGuard()` and `deleteCookieOnLogout()`. (I've requested the removal of facade calls in Passport months ago but the willingness of the passport team to change this seems very low).
So please feel free to test this in your full laravel projects and I'll be …
=> Remove dependencies on Facades

src/Schema/Directives/Fields/PaginateDirective.php, src/Support/Database/QueryFilter.php, tests/Integration/Schema/Directives/Fields/PaginateDirectiveTest.php, tests/Utils/Models/Comment.php, tests/Utils/Models/Post.php, tests/Utils/Models/User.php, tests/database/factories/CommentFactory.php, tests/database/factories/PostFactory.php, tests/database/migrations/2018_02_28_000004_create_testbench_posts_table.php, tests/database/migrations/2018_02_28_000005_create_testbench_comments_table.php
- Changed so pagination now uses `pageresolvers`, so we don't have to write default parameters in our code. (This also gives more flexibility when creating custom directives)
- Changed so query filters now uses the returned query as the new query. This gives us a lot of flexibility, now we can even return a whole other query, with a filter directive. 
These changed was also required before I could implement a Scout directive, or at least to implement it really easy. #93
=> More flexible directives

config/config.php, src/Support/Http/routes.php, tests/Integration/GraphQLTest.php
Being able to hit the graphql endpoint with a get request is extremely useful for debugging
=> Enable GET requests to the graphql endpoint when app is in debug mode

composer.json, src/Support/Http/routes.php
Lumen routing has no concept of ::match, therefor I just split the one-liner into two, adding the ::get if allowed, whilst keeping the default ::post
=> Keep routes compatible with Lumen framework

src/Schema/Directives/Fields/DeleteDirective.php, src/Schema/Directives/Fields/UpdateDirective.php
When you use the delete directive with a global ID $id comes back as an array with `['modelName', 'id']`, so $model::find($id) returns a collection instead of the model instance. I'm simply access the first index of the global ID resolver, so we get the actual model instance back when doing the `$model::find($id)` operation.
=> Fixed a bug with DeleteDirective when using a globalId

composer.json
We are already using features that are not in PHP 5.6, so we might as well make it official.
=> Require php >= 7.0

src/Support/DataLoader/QueryBuilder.php, tests/Integration/Support/DataLoader/QueryBuilderTest.php
This fixes #143 in a manner that is compatible with various databases
=> Use query builder to construct the union query and properly escape the alias

src/Schema/Factories/FieldFactory.php
We need to have a resolver in place for the middleware to function properly.
The default resolver does have a sensible behaviour, especially towards handling
nested fields. The previous default here did not handle that correctly.
=> Use the graphql-php default resolver when no other resolver is given

tests/Unit/Schema/Factories/RuleFactoryTest.php
The generated rules array should be as small as possible. Else, heavily nested and large Input Objects might cause the rules array to grow too large.
=> [WIP] Only generate minimal needed rules

src/Schema/AST/ASTBuilder.php, src/Schema/AST/DocumentAST.php, src/Schema/Factories/RuleFactory.php, src/Schema/MiddlewareManager.php, src/Schema/SchemaBuilder.php, tests/Unit/Schema/AST/ASTBuilderTest.php
- Optimize setDefinition() to only look at the new definition once
- declare(strict_types=1)
- Add return types and scalar type hints
- Clean up method names to follow the same naming convention that PartialParser follows
- Remove unused methods
=> Refactor and cleanup DocumentAST

src/GraphQL.php, src/Schema/AST/DocumentAST.php, src/Support/Exceptions/DocumentASTException.php
Adding a lock to the DocumentAST allows us to bypass generating clones for nodes (performance). It also prevents accidental schema manipulation after node/field/arg manipulators have been run. A `unlock` method is provided if needed by the user.
=> DocumentAST Lock

src/Providers/LighthouseServiceProvider.php, src/Schema/Directives/Args/RulesDirective.php, src/Schema/Factories/FieldFactory.php, src/Support/Validator/GraphQLValidator.php, src/Support/Validator/ValidatorFactory.php, tests/TestCase.php, tests/Unit/Schema/Directives/Args/RulesDirectiveTest.php
This PR introduces a new custom validator which allows you to grab the `root`, `context` and `resolve` info used on the field in your own custom validation classes. 
Additionally, a new `required_with_mutation` rule has been created to mark certain fields as required with certain mutation fields. For example, with the following schema:
```graphql
input UserInput {
first_name: String @rules(apply: ["required_with_mutation:createUser"])
}
extend type Mutation {
createUser(input: UserInput): User
updateUser(input: UserInput): User
}
```
the `first_name` is only required if the `createUser` mutation is being processed.
This PR also allows `@rules` to be placed on ObjectType field arguments so part of the query can still return a response if a nested field fails validation.
=> Custom Validator

src/Schema/Directives/Args/RulesDirective.php, src/Schema/Factories/FieldFactory.php, src/Schema/Factories/RuleFactory.php, tests/Unit/Schema/Directives/Args/RulesDirectiveTest.php, tests/Unit/Schema/Factories/RuleFactoryTest.php
Enhanced the existing tests and added an additional test for nested Inputs, that were previously only considered on Mutations.
Changed the implementation so that no difference is made between queries and mutations.
=> Add tests and fixes to ensure Query and Mutation fields are treated equally

src/Schema/AST/DocumentAST.php, src/Schema/AST/PartialParser.php, src/Schema/Directives/Fields/PaginationManipulator.php, src/Support/Traits/AttachesNodeInterface.php, src/Support/Traits/CanParseTypes.php
**PR Type**
Performance optimization
**Changes**
The way the DocumentAST was serialized before was way to costly, as the class
structure of the AST was completely serialized. To improve efficiency,
the location information is left out during parsing and the AST is stored
as an Array.
This is the preferred approach for schema caching as described in http://webonyx.github.io/graphql-php/type-system/type-language/#performance-considerations
=> Parse without location info and serialize effectively

src/Schema/Directives/Args/BcryptDirective.php, src/Schema/Directives/Args/EqualsFilterDirective.php, src/Schema/Directives/Args/InFilterDirective.php, src/Schema/Directives/Args/NotEqualsFilterDirective.php, src/Schema/Directives/Args/NotInFilterDirective.php, src/Schema/Directives/Args/RulesDirective.php, src/Schema/Directives/Args/ScoutDirective.php, src/Schema/Directives/Args/ValidateDirective.php, src/Schema/Directives/Args/WhereBetweenFilterDirective.php, src/Schema/Directives/Args/WhereFilterDirective.php, src/Schema/Directives/Args/WhereNotBetweenFilterDirective.php, src/Schema/Directives/Fields/CanDirective.php, src/Schema/Directives/Fields/ComplexityDirective.php, src/Schema/Directives/Fields/EventDirective.php, src/Schema/Directives/Fields/GlobalIdDirective.php, src/Schema/Directives/Fields/InjectDirective.php, src/Schema/Directives/Fields/MiddlewareDirective.php, src/Schema/Directives/Nodes/ModelDirective.php, src/Schema/Directives/Nodes/NodeDirective.php, src/Schema/Directives/Nodes/SecurityDirective.php, src/Schema/Factories/ArgumentFactory.php, src/Schema/Factories/FieldFactory.php, src/Schema/Factories/NodeFactory.php, src/Support/Contracts/ArgMiddleware.php, src/Support/Contracts/FieldMiddleware.php, src/Support/Contracts/NodeMiddleware.php, src/Support/Pipeline.php, tests/Unit/Schema/DirectiveRegistryTest.php, tests/Unit/Support/Validator/ValidatorTest.php
**Changes**
From the original PR notes:
> I have changed Arg directive to use a Laravel Pipeline instead.
This give us the power to actually define if a arg directive should be executed last or if any directive after it should be run also, just like when using Laravel's middlewares.
Originally the value/middleware was intended to be similar to the request/middleware from Laravel. This PR gives us the benefits the middleware pipeline in Laravel provides. There's some additional work to be done on the `FieldResolver` and the generation of Node/Field/Arg values but this provides a great first step.
Any current Node/Field/Arg middleware's handle function(s) will need to pass the value object back into the pipeline for further processing.
For example:
```php
// previous …
```
=> Feature: Middleware Pipeline

src/Schema/Directives/Fields/CanDirective.php, src/Schema/Directives/Fields/CreateDirective.php, src/Schema/Directives/Fields/DeleteDirective.php, src/Schema/Directives/Fields/UpdateDirective.php
Previously, the configuration option for the Model namespace was not considered in
a bunch of cases.
**PR Type**
Bugfix
**Changes**
The common method for getting a model is now reused in all applicable places, thus unifying
the behaviour that a user can expect when referencing models in directives.
Apart from some really far fetched edge cases, no. Should a user reference a model like
@create(model: "App\\Foo")
this would now reference `App\Models\App\Foo` if it exists.
=> Get the model class for the directives in the same way for all directives

src/Schema/Directives/CacheDirective.php, src/Schema/Factories/ValueFactory.php, src/Schema/Values/CacheValue.php, src/Schema/Values/FieldValue.php, src/Schema/Values/NodeValue.php, tests/Integration/Schema/Directives/CacheDirectiveTest.php, tests/Integration/Schema/Directives/Fields/PaginateDirectiveTest.php
**PR Type**
New Feature
**Changes**
This PR introduces a new `@cache` directive to cache resolved fields using Laravel's built in cache management. The directive accepts two optional arguments. `maxAge` will set the amount of seconds the value(s) should stay in cache. `private` will prepend the authenticated user's id to the cache key and should be used on fields that provide different output depending on the authenticated user. The cache key also takes arguments into consideration so queries on the same field but different input arguments (i.e., `users(page:1)` vs `users(page:2)`) are handled appropriately.
Usage example:
```graphql
type Query {
users: [User] @paginate(...) @cache(maxAge: 60)
}
{
users(count: 5) {
}
}
```
*This will store the first 5 users in cache for 1 minute.*
The …
=> Server Side Caching

src/GraphQL.php, src/Providers/LighthouseServiceProvider.php, src/Schema/AST/ASTBuilder.php, src/Schema/Directives/Fields/TraceDirective.php, src/Schema/Extensions/ExtensionRegistry.php, src/Schema/Extensions/ExtensionRequest.php, src/Schema/Extensions/GraphQLExtension.php, src/Schema/Extensions/TraceExtension.php, tests/Integration/GraphQLTest.php, tests/Unit/GraphQLTest.php, tests/Unit/Schema/Extensions/TraceExtensionTest.php
#98 
**PR Type**
Feature
**Changes**
This PR introduces [Apollo Engine Tracing](https://www.apollographql.com/docs/engine/performance.html#trace) (it also works w/ [Prisma's Playground](https://github.com/prismagraphql/graphql-playground)) as well as a draft for implementing [extensions](https://github.com/apollographql/apollo-server/tree/master/packages/graphql-extensions). A new `extensions` config option will be added which accepts an array of extensions to activate.
```php
// lighthouse.php
return [
// ...
'extensions' => ['tracing']
];
```
*Note: The `GraphqlExtension` and `ExtensionRegistry` were only introduced in this PR to get basic functionality working. A PR is already in progress to build out the API*
None
=> [WIP] Apollo Engine Tracing

src/Schema/Directives/Fields/LazyLoadDirective.php
**PR Type**
Feature
**Changes**
Adds a `@lazyLoad` directive to allow users to choose to perform a [lazy eager load](https://laravel.com/docs/5.6/eloquent-relationships#lazy-eager-loading) on a collection (generally used w/ the `@hasMany` directive) like so:
```graphql
type User {
jobs: [Job] @hasMany @lazyLoad(relations: ["company"])
}
```
None
=> add lazyLoad directive

README.md
None
**PR Type**
Docs
**Changes**
Adds one missing character :)
None
=> Fix typo 'compose' => 'composer' in readme

src/Schema/Directives/Args/BcryptDirective.php, src/Schema/Directives/Args/EqualsFilterDirective.php, src/Schema/Directives/Args/InFilterDirective.php, src/Schema/Directives/Args/NotEqualsFilterDirective.php, src/Schema/Directives/Args/NotInFilterDirective.php, src/Schema/Directives/Args/RulesDirective.php, src/Schema/Directives/Args/ScoutDirective.php, src/Schema/Directives/Args/ValidateDirective.php, src/Schema/Directives/Args/WhereBetweenFilterDirective.php, src/Schema/Directives/Args/WhereFilterDirective.php, src/Schema/Directives/Args/WhereNotBetweenFilterDirective.php, src/Schema/Directives/Fields/CanDirective.php, src/Schema/Directives/Fields/ComplexityDirective.php, src/Schema/Directives/Fields/EventDirective.php, src/Schema/Directives/Fields/GlobalIdDirective.php, src/Schema/Directives/Fields/InjectDirective.php, src/Schema/Directives/Fields/MiddlewareDirective.php, src/Schema/Directives/Nodes/ModelDirective.php, src/Schema/Directives/Nodes/NodeDirective.php, src/Schema/Directives/Nodes/SecurityDirective.php, src/Schema/Factories/ValueFactory.php, src/Schema/NodeContainer.php, src/Schema/Resolvers/FieldResolver.php, src/Support/Contracts/ArgMiddleware.php, src/Support/Contracts/FieldMiddleware.php, src/Support/Contracts/NodeMiddleware.php, src/Support/DataLoader/QueryBuilder.php, src/Support/Pipeline.php
This makes it very obvious, which kind of Closure is reffered to when reading
the code and allows us to omit the use statement at the top of the file.
As we are using opis/closure, this change should make the distinction clear.
**PR Type**
Refactor
=> Simplify the type hints for Closure to \Closure

src/Support/DataLoader/QueryBuilder.php, tests/Integration/Support/DataLoader/QueryBuilderTest.php, tests/Utils/Models/Task.php, tests/database/migrations/2018_02_28_000003_create_testbench_tasks_table.php
**PR Type**
Bugfix
**Changes**
Not sure if this is Laravel related (seems to be) but when using the `fromSub` function on a Query Builder it strips out the soft delete check from the first query, thus breaking soft deletes used in the `@hasMany` or `@belongsTo` directives.
None
=> [FIX] Query Parsing

src/Support/DataLoader/QueryBuilder.php
#204 
**PR Type**
Compatibility Fix
**Changes**
Laravel v5.4 doesn't have `fromRaw` so this PR tweaks the `QueryBuilder` to use the `from` and `setBindings` methods available in older versions of Laravel.
None
=> remove fromRaw from compatibility

src/Schema/Values/CacheValue.php
**PR Type**
Bugfix
**Changes**
Remove `sortKeys` method, this was added in [v5.6.6](https://github.com/laravel/framework/blob/5.6/CHANGELOG-5.6.md#v566-2018-02-27)
None
=> remove sortKeys for compatibility

src/Schema/Directives/Nodes/UnionDirective.php, src/Schema/NodeContainer.php, src/Schema/Resolvers/FieldTypeResolver.php, src/Schema/Resolvers/NodeResolver.php, src/Schema/TypeRegistry.php, tests/Integration/Schema/NodeTest.php, tests/Unit/Schema/Directives/Nodes/UnionTest.php
This makes it so the TypeRegistry has a smaller public API and a more
intuitive method name, get() and register() are pretty standard for a registry.
**PR Type**
Refactor
Nope, but the deprecated method will be removed in v3
=> Deprecate instance method in favor of get

src/Schema/Directives/Args/SearchDirective.php, tests/Integration/Schema/Directives/Args/SearchDirectiveTest.php
Resolves #226
**PR Type**
Refactor
Nope, as usage of the directive stays the same
=> Rename the ScoutDirective to SearchDirective to match its actual name

assets/default-schema.graphql
Hey,
I think the idea of having a default schema is wonderful. I, however, ran into an issue, which I tried to address with this PR. 
Straight after installation of Lighthouse on a new Laravel install, I was thrilled to test out the default schema Lighthouse generates by default. Laravel immediately threw an error as User model couldn't be found in App\\Models namespace. While I usually keep my models in a Models directory, User is the only one I leave at the default location.
I believe the default installation of a package immediately throwing an error may present a very wrong picture of Lighthouse being non-functional or poorly maintained. I myself have been subscribed to the package updates long enough to know that it definitely isn't the case.
I, therefore, propose the default schema …
=> Update default-schema.graphql file

src/GraphQL.php, tests/Unit/GraphQLTest.php
#241 
**PR Type**
Bugfix
**Changes**
Adds support for 'named operations in GraphQL Playground / GraphiQL. As described in #241 
Not that I know, Laravel defaults to null so it should still work when it was not passed.
=> Pass operationName through executeQuery function, fixes #241

assets/default-schema.graphql
Thanks for wonderful library. I love it.
I encountered the following error when I first installed this library.
```js
{
"message": "Can only create NonNull of a Nullable GraphQLType but got: null",
"exception": "GraphQL\\Error\\InvariantViolation",
"file": "/var/www/html/vendor/webonyx/graphql-php/src/Type/Definition/NonNull.php",
"line": 25,
"trace": [
{
"file": "/var/www/html/vendor/webonyx/graphql-php/src/Type/Definition/Type.php",
"line": 88,
"function": "__construct",
"class": "GraphQL\\Type\\Definition\\NonNull",
"type": "->"
},
// ....
}
```
**PR Type**
Docs
**Changes**
After I import `DateTime` scalar on the top of `routes/graphql/schema.graphql` the error has gone.
```gql
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")
```
referring the Doc: …
=> add DateTime scalar to default schema

src/Schema/Types/Scalars/DateTime.php
None
**PR Type**
Bugfix
**Changes**
When using the scalar DateTime type in your schema, no description pops up when using introspection. When someone views the docs they will not be able to see which format is returned. 
None
=> Add a description for the default DateTime scalar

src/GraphQL.php
I had the error:
```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function Nuwave\Lighthouse\request() in .../vendor/nuwave/lighthouse/src/GraphQL.php:159
```
**PR Type**
Bugfix
**Changes**
I use `Illuminate\Support\Facades\Request;` as you use `Illuminate\Support\Facades\Cache;`
=> Use Facade\Request instead of request()

config/config.php
I do not see any harm in defaulting this to `true`, it will avoid a
very common issue among new users of Lighthouse.
#202 
**PR Type**
Config change
Nope, the config can easily be changed back
=> Enable using the GraphQL endpoint via GET by default

config/config.php
Internally `graphql-php` use strict checks for this so we need `0` instead of `false`.
=> Fix default config for `disable_introspection`

src/GraphQL.php, src/Schema/Directives/Fields/BelongsToDirective.php, src/Schema/Directives/Fields/HasManyDirective.php, src/Schema/Directives/Fields/HasOneDirective.php, src/Support/DataLoader/BatchLoader.php, src/Support/DataLoader/Loaders/BelongsToLoader.php, src/Support/DataLoader/Loaders/HasOneLoader.php, tests/Integration/Schema/Directives/Fields/AllDirectiveTest.php, tests/Integration/Schema/Directives/Fields/BelongsToTest.php, tests/Integration/Schema/Directives/Fields/HasOneDirectiveTest.php, tests/Integration/Schema/Directives/Nodes/UnionDirectiveTest.php, tests/Utils/Models/Post.php, tests/Utils/Models/Task.php, tests/database/factories/PostFactory.php, tests/database/migrations/2018_02_28_000004_create_testbench_posts_table.php
Resolves #276
**PR Type**
Feature
**Changes**
- Add test case and scenario for a HasOne relationship
- BatchLoader classes are now initialized with a set of immutable params
- Avoid unnecessary steps inbetween for performance & code clarity
- Loaders now indicate clearly what they require as a one-off config and what is required for each field instance
For users that do not reach into internals, nothing changes. Existing directives continue to work as before.
- The API for the BatchLoader abstract class changed so additional Loader implementations have to adapt. `resolve()` is now expected to return a keyed array of results.
- `graphql()->batch()` was changed to `graphql()->batchLoader()` and is now only responsible for returning a unique …
=> Introduce the HasOneDirective and the HasOneLoader, improve BatchLoader semantics

src/Support/DataLoader/QueryBuilder.php
Dot in table name causing sql error
Resolves #285
**PR Type**
Bugfix
**Changes**
Function returns an alias "schema_table" if table name has a dot, like "schema.table".
=> Fix for #285 table alias for query

src/Schema/Factories/FieldFactory.php
The signature for default resolver is not aligned with `@field` directive's.
For more consistency, I would like to recommend make this little change.
=> Align resolver signature with `@field` directive

src/Schema/Directives/BaseDirective.php
Supersedes #298 
**PR Type**
Bugfix + Refactor
**Changes**
Before, the code always prepended the default model namespace and then added on the
extra namespace. Now, each one of those fallbacks is tried seperately.
Nope
=> Do not append default namespace before the configured namespace

src/Exceptions/RendersErrorsExtensions.php, src/Execution/ErrorHandler.php, src/Schema/Source/SchemaSourceProvider.php
None
**PR Type**
Refactor
**Changes**
Removes return types on interfaces that may be implemented by the user. This allows the user to choose to add a return type on their implementation rather than forcing them to do so.
None
=> [Refactor] Remove return types on interfaces

tests/Integration/Schema/Directives/Fields/HasManyDirectiveTest.php, tests/Utils/Models/Post.php, tests/database/factories/PostFactory.php, tests/database/migrations/2018_02_28_000004_create_testbench_posts_table.php
Currently, when querying recursive relationships, relationships in the second recursion become null. 
As discussed in the Slack channel, this is a WIP PR that currently adds a failing test that demonstrates this behaviour.
**PR Type**
Probably a bugfix, maybe a feature?
**Changes**
Support recursive relationships.
As far as I am aware, there are no breaking changes unless someone relies on the "second layer parent is null" behaviour.
=> Add test for recursive relationships

src/Schema/Directives/Nodes/ScalarDirective.php, src/Schema/Factories/NodeFactory.php, tests/Integration/Schema/Types/UnionTest.php, tests/Unit/Schema/Factories/NodeFactoryTest.php
Also, the InterfaceTest shows how Interfaces can use custom type resolvers as well.
#321 
**PR Type**
Regression Fix, Tests
=> Add ScalarDirective back in and tests that show how Scalars and Unions can still use custom classes and resolvers

src/Providers/LighthouseServiceProvider.php, src/Support/DataLoader/Loaders/BelongsToLoader.php, src/Support/DataLoader/Loaders/HasManyLoader.php, src/Support/DataLoader/Loaders/HasOneLoader.php, tests/Integration/Schema/Directives/Fields/HasManyDirectiveTest.php, tests/Integration/Support/DataLoader/QueryBuilderTest.php, tests/Utils/Models/Task.php
Adds test for #319 
Reverts misguided WIP #320 
https://github.com/laravel/framework/issues/16217
**PR Type**
Test/Fix
**Changes**
- Add test to ensure the global scope is called when using the @hasmany directive
- Add TODO for removing custom fetch logic once Laravel resolves their issue with eager loading
Nope
=>  Revert #320 and use fetch() instead of load() again

src/Schema/AST/ASTHelper.php, src/Schema/Directives/BaseDirective.php, src/Schema/Directives/Fields/ComplexityDirective.php, src/Schema/Directives/Fields/FieldDirective.php, src/Schema/Directives/Fields/PaginateDirective.php, src/Schema/Directives/Nodes/NodeDirective.php, src/Schema/Factories/NodeFactory.php, tests/Integration/Schema/Directives/Fields/PaginateDirectiveTest.php, tests/Unit/Schema/Directives/Fields/FieldDirectiveTest.php, tests/Unit/Schema/Directives/Fields/PaginateDirectiveTest.php
Supersedes #302
This enables the user to use the complex logic that is within the @paginate directive
with a completely custom query.
- Add 'builder' argument to @paginate
- Add test that verifies a custom builder can be called
**Deprecation**
Deprecate alternate way of defining a field resolver through class/method
**Breaking changes''
Fail hard if no valid resolver argument was found but an argument for specifying such
was given. This might cause some users to get Errors, but in a good way - since it means
their previous definition did not work.
They can then either fix the directive argument or simply omit it to use the default, if possible.
**Refactor**
- Refactor BaseDirective->getResolver() to a more general getMethodArgument that contains
less magic and is more composable
- Add …
=> Allow passing a custom builder to @paginate instead of a model

src/Providers/LighthouseServiceProvider.php, src/Schema/Source/SchemaSourceProvider.php, src/Schema/Source/SchemaStitcher.php, tests/Integration/Schema/Source/SchemaSourceProviderTest.php, tests/TestSchemaProvider.php
#325
**PR Type**
Refactor
**Changes**
Adds `setRootPath` method to `SchemaSourceProvider` interface to allow users to programmatically change the root path of the schema.
Any user defined implementations of `SchemaSourceProvider` that doesn't currently extend the `SchemaStitcher` will need to add the new method.
=> [Refactor] Allow setting root path of schema

src/Execution/Utils/GlobalId.php, src/Schema/AST/ASTBuilder.php, src/Schema/AST/ASTHelper.php, src/Schema/Directives/Args/BcryptDirective.php, src/Schema/Directives/Fields/GlobalIdDirective.php, src/Schema/NodeRegistry.php, src/Schema/SchemaBuilder.php, tests/Integration/Schema/NodeInterfaceTest.php
**Motivation**
Resolves #236
The docs displayed that usage, but it did not actually work.
**Changes**
The `@globalId` can now be used on Arguments to decode a global id. The value that is then passed along
is an array that consists of [$type, $id].
This is used in the definition of the `node` endpoint, that was simplified as a result:
It is now defined in the ASTBuilder again (going back and forth on this one :D ), which in the end
is a cleaner solution that also allows to leverage caching.
Did some formatting cleanups on the go, as i usually do.
Decoding the global ID on fields is now no longer a configurable option. This is because
global IDs are internal, and fields only ever output values, so all they need is encoding.
=> Allow using @globalID on args for decoding

src/Support/DataLoader/QueryBuilder.php
Resolves [#333](https://github.com/nuwave/lighthouse/issues/333)
**PR Type**
Bugfix
**Changes**
Use the connection set on the model when building the query in the QueryBuilder
=> Fix for #333 - Use connection specified on the model in QueryBuilder

src/Schema/Source/SchemaStitcher.php, tests/Unit/Schema/AST/SchemaStitcherTest.php
Resolves #314 
**PR Type**
Feature
**Changes**
If the file name to import has a wildcard, it loads via `glob`.
=> Allow schema import via glob in SchemaStitcher

src/Schema/AST/PartialParser.php, tests/Unit/Schema/AST/PartialParserTest.php
A quick bug fix for PartialParser.
=> [Bug fix]PartialParser can not parse `argument`

src/Support/DataLoader/QueryBuilder.php
Fixing this issue: https://github.com/nuwave/lighthouse/issues/346
**PR Type**
Bugfix
**Changes**
Forced the $with to be an array
=> Forced the withProperty to an array type.

src/Providers/LighthouseServiceProvider.php, src/Support/DataLoader/QueryBuilder.php
This piece of code may cause problems because some properties may changes when it was converted to the array by using the `toArray` method. 
In my case, because I'm using the binary UUID for primary key, so the `id` property of model will be converted into a string representation of the binary UUID, so if it `toArray` the model, the `id` will never be the binary UUID anymore.
```php
foreach ($models as $model) {
if (isset($dictionary[$model->{$key}])) {
$model->forceFill($dictionary[$model->{$key}]
->toArray());
}
}
```
Also, cleanup the code a bit.
=> [Bugfix & Refactor]`eagerLoadCount` cleanup & potential bug fix

src/Schema/Types/ConnectionField.php, tests/Integration/Schema/Directives/Fields/PaginateDirectiveTest.php
**PR Type**
Bugfix
I am getting the following error when the paginator is empty.
```
Argument 1 passed to Nuwave\Lighthouse\Execution\Utils\Cursor::encode() must be of the type integer, null given
```
=> Do not try to encode a cursor when the result of a Connection is empty

src/Support/DataLoader/QueryBuilder.php, tests/Integration/Support/DataLoader/QueryBuilderTest.php, tests/Utils/Models/Comment.php, tests/Utils/Models/Company.php, tests/Utils/Models/Post.php, tests/Utils/Models/Task.php, tests/Utils/Models/Team.php, tests/Utils/Models/User.php
**PR Type**
Bugfix
**Changes**
Consider the following schema:
```graphql
type Query {
me: User @auth
}
type User {
name: String!
tasks: [Task!]! @hasMany(type: "paginator")
}
type Task {
task: String!
}
```
With the following `User` mode:
```php
class User extends Model {
protected $visible = ['id'];
}
```
And the following query:
```graphql
query {
me {
name
tasks(count: 3) {
paginatorInfo {
total
}
data {
task
}
}
}
}
```
This fails with a `InvariantViolation`: `Cannot return null for non-nullable field PaginatorInfo.total.`.
Because `->toArray()` is being used to get all the attributes from the model and re-setting them on the eager loaded model only the `$visible` attributes are taken, while visibility should be ignored here otherwise the `*_count` fields will not be properly copied …
=> Fix paginator total attribute being null with visibility set on models

.travis.yml, phpunit.xml.dist
We have to generate the coverage report in PHP 7.1, as PHP 7.2 is currently bugged and causes segmentation faults when running PHPUnit with coverage.
=> Fix coverage generation in travis

src/Execution/ContextFactory.php, src/Providers/LighthouseServiceProvider.php, src/Schema/Context.php, src/Support/Contracts/CreatesContext.php, src/Support/Contracts/GraphQLContext.php, src/Support/Http/Controllers/GraphQLController.php, tests/Unit/Schema/Execution/ContextFactoryTest.php
None
**PR Type**
Feature
**Changes**
Allows users to define their own context by implementing the `CreatesContext` interface. A new `GraphQLContext` interface has also been introduced so a Lighthouse can safely make assumptions about how to get an instance of the original request and authenticated user from the `$context` resolver argument.
None, Lighthouse's default Context will created and injected into resolvers just as it currently is.
=> [Feat] Context Contract

src/GraphQL.php, src/Schema/Extensions/ExtensionRegistry.php, src/Schema/Extensions/GraphQLExtension.php, src/Schema/MiddlewareRegistry.php, src/Support/Http/Controllers/GraphQLController.php, tests/Unit/Schema/Extensions/GraphQLExtensionTest.php
None, however I ran into an issue w/ persisted queries and needing to manipulate the output before it was sent out to the client.
Additionally, if no query is sent up to the server (as it does with persisted queries) the MiddlewareRegistry would throw an error before GraphQL execution begins. #363 will resolve this issue as well but simply checking to see if the `$request` parameter is empty will prevent an exception from being thrown in the meantime.
**PR Type**
Feature
**Changes**
This PR allows extensions to manipulate the response data prior to being sent down to the client. This keeps the user from having to extend the `GraphQLController` and instead keep all relevant code tucked away in an extension.
None
=> [Feat] Extension Manipulate Response

src/Exceptions/DefinitionException.php, src/Schema/AST/ASTBuilder.php, src/Schema/AST/ASTHelper.php, src/Schema/AST/DocumentAST.php, tests/Integration/Schema/Directives/Fields/PaginateDirectiveTest.php, tests/Unit/Schema/AST/ASTBuilderTest.php, tests/Unit/Schema/AST/ASTHelperTest.php, tests/Unit/Schema/AST/DocumentASTTest.php, tests/Unit/Schema/Directives/Fields/InjectDirectiveTest.php, tests/Unit/Schema/Directives/Fields/PaginateDirectiveTest.php
Resolves #387 
**PR Type**
Bugfix
**Changes**
Prevent type extension nodes to be added more than once.
I added the unit test that was added by @jbbr and it passes with the provided fix
**Breaking Changes**
The ASTBuilder now throws when merging type extensions that define duplicate fields. Whereas this might cause failures for some users, it uncovers behaviour that was previously bugged. It now fails early instead of adding a hard to find bug, so i think it is a strict improvement over the previous behaviour.
=> Prevent duplicate type extension nodes and duplicate fields

src/Console/stubs/field.stub
Bugfix for #392
No, it un-breaks stuff 😉
=> Change the type annotation for the default field resolver to a nullable GraphQLContext

src/Console/InterfaceCommand.php, src/Console/LighthouseGeneratorCommand.php, src/Console/MutationCommand.php, src/Console/QueryCommand.php, src/Console/ScalarCommand.php, src/Console/UnionCommand.php
This class can be removed if/when https://github.com/laravel/framework/pull/26176 is merged.
**Changes**
This prevents users of the field generator commands that copy-and-paste the field definitions from accidentally creating a lowercased class.
No
=> Capitalize the class name in generator commands

src/Schema/AST/ASTHelper.php, src/Schema/Factories/NodeFactory.php, tests/Unit/Schema/Factories/NodeFactoryTest.php, tests/Unit/Schema/SchemaBuilderTest.php
This simplifies enum definitions that are just string values.
**PR Type**
Feature/Bugfix
**Changes**
Previously, you always had to define a value for enums. This is generally fine, but
leads to unnecessarily verbose code when your enum is composed of strings:
```graphql
enum Role {
ADMIN @enum(value: "ADMIN")
}
```
If the internal value of the enum is the same as the field name, `@enum` can be omitted:
```graphql
enum Role {
ADMIN
}
```
**Bugfix**
During testing, i also discovered a bug where literal values defined via `@enum` were
not always converted to the correct type.
```graphql
enum Role {
ADMIN @enum(value: 1)
}
```
Lead to an internal value of `string('1')`. Now it correctly parses it to a `int(1)`
This did not cause problems for most users because of PHP's …
=> Default to field name if no explicit value is given for an ENUM

src/Schema/Source/SchemaStitcher.php, tests/Integration/Schema/Source/SchemaSourceProviderTest.php, tests/Unit/Schema/AST/SchemaStitcherTest.php
The issue occurs when:
imported file 1
```graphql
union Account = User | Admin
```
imported file 2
```graphql
scalar Email
```
results this:
```graphql
union Account = User | Adminscalar Email
```
which will cause a syntax error.
Adding new line to the end of the imported file can solve this problem.
=> [Bugfix]Add new line to the end of the imported file

src/Support/Http/Controllers/GraphQLController.php
Resolves #411 
**PR Type**
Bugfix (Lumen)
**Changes**
Converts request object to an array before performing an `isset` on a key.
None
=> [Fix] Lumen request array access

src/Providers/LighthouseServiceProvider.php
Just tested this in a local project, everything works as before. This gives the option to
php artisan vendor:publish --provider="Nuwave\Lighthouse\Providers\LighthouseServiceProvider" --tag=schema
or
php artisan vendor:publish --provider="Nuwave\Lighthouse\Providers\LighthouseServiceProvider" --tag=config
to publish only the parts of the assets that you want
=> Allow publishing the schema and config seperately

src/Schema/Directives/Fields/ComplexityDirective.php, tests/Unit/Schema/Directives/Fields/ComplexityDirectiveTest.php, tests/Utils/Queries/Foo.php
**PR Type**
Feature
**Changes**
The default namespace resolution for `@complexity` now works just like `@field`.
This makes them more consistent.
Nope
=> Enable usage of the default field namespace for @complexity

config/config.php
The community has spoken.
Resolves #417
**Changes**
- Change the default schema location to `graphql/schema.graphql`
- Change the default model namespace to `App`
- Change various GraphQL namespaces to `App\GraphQL\...`
Users that did not publish their configuration are affected and have 2 options:
- Change their code to work with the new namespaces
- Publish the configuration before updating
=> Change the default schema location and namespaces as voted for in #417

src/Execution/DataLoader/RelationBatchLoader.php, src/Schema/Directives/Fields/PaginateDirective.php, src/Schema/Directives/Fields/PaginationManipulator.php, src/Schema/Directives/Fields/RelationDirective.php, tests/Integration/Schema/Directives/Fields/HasManyDirectiveTest.php, tests/Integration/Schema/Directives/Fields/PaginateDirectiveTest.php
Resolves #426
The `@hasMany` and `@paginator` directives now support an additional argument `defaultCount` that sets a default value for the generated field argument `count`.
```graphql
type Query {
posts: [Post!]! @paginate(defaultCount: 20)
}
```
This allows the API consumer to omit the count when requesting a paginated list of fields.
```graphql
{
posts {
data {
id
name
}
}
}
```
=> Add support for a default count value for paginators

src/Schema/Directives/Fields/CacheDirective.php, src/Schema/Directives/Fields/TracingDirective.php, src/Schema/Extensions/TracingExtension.php
Lumen doesn't have a now()-helper as Laravel does so this enables Lumen to use cache and tracing.
**PR Type**
Bugfix (Lumen)
**Changes**
Changed now() to Carbon::now()
None
=> Change now()-helper to Carbon::now()

src/Execution/DataLoader/BatchLoader.php, src/GraphQL.php, tests/Integration/Execution/DataLoader/BatchLoaderTest.php
Currently, if a batched query is sent up to Lighthouse that references the same field the same key will be produced in the `BatchLoader` causing an error (the `key` of any subsequent query will be missing). 
**Changes**
To resolve the issue `Nuwave\Lighthouse\GraphQL` now holds a reference to the `currentBatchIndex`. When set, the `BatchLoader` will prepend the index to the key making the field name unique across multiple queries.
None
=> [FIX] Adjust key in BatchLoader for batched queries

src/Execution/MutationExecutor.php, tests/Integration/Schema/Directives/Fields/CreateDirectiveTest.php, tests/database/migrations/2018_02_28_000002_create_testbench_users_table.php, tests/database/migrations/2018_09_30_000006_create_testbench_tags_table.php
Resolves #501
**Changes**
Make sure that values that are set through the database insert
are immediately available for return, e.g. default values.
Add a test for creating nested has many relations on the side.
No
=>  Refresh newly created models before returning them

docs/master/api-reference/directives.md, src/Schema/Directives/Fields/InjectDirective.php, tests/Integration/Schema/Directives/Fields/InjectDirectiveTest.php
Allows inject with dot notation. For example if using input object. This allows to do as follows:
`type Mutation {
createPost($input: CreateObjectInput!): Post
@create
@inject(context: "user.id", name: "input.user_id")
}`
=> Being able to set injected value with dot notation deeper

src/Schema/Directives/Fields/CanDirective.php
Resolves #505
Accentuate the difference between missing authentication and failed authorization through the error messages.
=> Make the error messages returned by @can more friendly

docs/master/guides/relationships.md, src/Execution/MutationExecutor.php, tests/Integration/Schema/Directives/Fields/CreateDirectiveTest.php, tests/database/migrations/2018_02_28_000003_create_testbench_tasks_table.php
Resolves #507
**Changes**
Detect relationships when executing nested mutations by using reflection instead of calling the methods and examining the result.
This prevents non-relationship methods from being called, which may lead to errors and/or side effects.
**Breaking Changes**
Users are required to define the return type of a relationship method in their Eloquent Model for the detection to work.
=> Prevent name conflict between argument names and non-relation methods when executing nested mutations

docker-compose.yml, docs/master/api-reference/directives.md, docs/master/extensions/subscriptions.md, docs/master/the-basics/fields.md, docs/master/the-basics/schema.md, src/Console/SubscriptionCommand.php, src/Console/stubs/subscription.stub, src/Providers/LighthouseServiceProvider.php, src/Schema/Directives/Fields/SubscriptionDirective.php, src/Schema/Types/GraphQLSubscription.php, src/Schema/Values/FieldValue.php, tests/Integration/Subscriptions/SubscriptionTest.php, tests/TestCase.php, tests/Utils/Subscriptions/OnPostCreated.php
Subscriptions now can be defined just like other fields, default namespaces
will work consistently.
**Changes**
- Default namespaces for Subscriptions now work without directives, just like
those for Queries and Mutations do.
- Split subscription docs into defining fields and triggering subscriptions, each with a few examples.
Changed type hints for the methods `resolve` and `encodeTopic` on `Nuwave\Lighthouse\Schema\Fields\SubscriptionField`.
Both methods do have default implementations, so there are probably just a few users who did overwrite them.
=> Treat subscriptions just like other fields

src/Console/stubs/field.stub
Command `lighthouse:query` creates new query class with non valid arguments by [psr-2](https://www.php-fig.org/psr/psr-2/#44-method-arguments) in `resolve` method. 
**Changes**
This PR changes `field.stub` and fixes creation queries with cli
=> Fix field stub by PSR

docs/master/api-reference/directives.md, docs/master/extensions/subscriptions.md, src/Execution/Utils/Subscription.php, src/Schema/Directives/Fields/BroadcastDirective.php
This naming is more in line with the well-known Laravel interface `ShouldQueue` and also clearly expresses the boolean nature of the argument.
=> Rename the "queue" argument for @broadcast to "shouldQueue"

docs/master/getting-started/migrating-to-lighthouse.md, docs/master/sidebar.js
Added a page to the docs that gives a few tips on how to migrate existing GraphQL servers
to Lighthouse.
In the future, some additional sections on how to migrate REST apis or projects from other
programming languages might be helpful.
=> Add migration guide

src/Support/Http/Controllers/GraphQLController.php, tests/Integration/GraphQLTest.php
When an invalid or empty (JSON) `variables` parameter is given (default behaviour of  https://github.com/graphql/graphiql), `json_decode` can return `null`, causing the following exception:
**Changes**
- Adds an empty array as fallback for when json_decode fails / returns null.
None.
=> Prevent crash when invalid JSON variables are given

src/Schema/Factories/RuleFactory.php
Resolves #573
**Changes**
The anonymous function already accounts for `$node = null`, but it now also allows `$node = null` as input.
=> Fix error in RuleFactory.php, closes #573

docs/master/api-reference/directives.md, src/Schema/Directives/Fields/AuthDirective.php, src/Schema/Values/CacheValue.php, src/Support/helpers.php, tests/Unit/Schema/Directives/Fields/AuthDirectiveTest.php
**Changes**
Adds a `guard` argument to the auth directive so one can specify a different guard to resolve the authenticated user
No breaking changes, if the `guard` argument is not specified it uses the default guard resolver
=> Add guard argument to auth directive

src/Subscriptions/Subscriber.php
This way the channels can be easily identified and allows me to hook up some custom authentication so I can use a single Pusher client for "normal" websockets and (Apollo) subscriptions.
Also gives me some indication what the channel is supposed to be doing instead of a completely random string 😄
=> Prefix the Pusher channels to easily identify them

src/Schema/Types/Scalars/DateTime.php, tests/Unit/Schema/Types/Scalars/DateTimeTest.php
Resolves #599 	
**Changes**
The description for DateTime scalars was lying and the behaviour was inconsistent.
Now they are always formatted/parsed as Y-m-d H:i:s
=> Actually use Y-m-d H:i:s for DateTime scalar

.gitattributes, .github/CONTRIBUTING.md, Dockerfile, docker-compose.yml
This adds a Dockerfile as well as the appropriate docker-compose config to run PHP with Xdebug enabled.
=> Add docker config for Xdebug

src/Schema/Directives/Fields/PaginateDirective.php, tests/Integration/Schema/Directives/Args/SearchDirectiveTest.php
Resolves #592
**Changes**
```php
// Nuwave\Lighthouse\Schema\Directives\Fields\PaginateDirective
protected function getPaginatedResults(array $resolveArgs, int $page, int $first): LengthAwarePaginator
{
...
if ($query instanceof \Laravel\Scout\Builder) {
return $query->paginate($first, 'page', $page);
}
return $query->paginate($first, ['*'], 'page', $page);
}
```
Please review my test case, it could be simpler I think.
=> Handle Scout pagination arguments

docs/master/api-reference/events.md, src/Events/BuildExtensionsResponse.php, src/Execution/ExtensionsResponse.php, src/GraphQL.php, src/Subscriptions/SubscriptionRegistry.php, src/Tracing/Tracing.php
Improves type safety on the receiving side of the event.
Also, this handles the case of listeners returning nothing/`null`.
Resolves #671 
Yes, but that is why we are still in beta 😉 It concerns only a feature that was just introduced.
=> Use ExtensionsResponse class for BuildExtensionsResponse

docs/master/guides/plugin-development.md, tests/Integration/Events/BuildSchemaStringTest.php, tests/Integration/Events/RegisterDirectiveNamespacesTest.php
Should make the section on plugin development more straightforward and easier to understand, and it actually has working links now :)
=> Fix the links to the events in plugin development

src/Schema/Directives/Fields/FindDirective.php, src/Schema/Factories/ArgumentFactory.php, tests/Unit/Schema/SchemaBuilderTest.php
This resolves a bug where a schema definition like this:
```graphql
type Query {
foo(
bar: Baz = FOOBAR
): Int
}
enum Baz {
FOOBAR @enum(value: "internal")
}
```
would pass `string("FOOBAR")` to the field resolver instead of the internal value.
=> Convert schema-defined enum default values to internal values

docs/master/api-reference/resolvers.md, docs/master/getting-started/installation.md, docs/master/guides/plugin-development.md, docs/master/the-basics/fields.md, docs/master/the-basics/types.md, src/Defer/DeferrableDirective.php, src/LighthouseServiceProvider.php, src/Schema/Directives/Fields/AllDirective.php, src/Schema/Directives/Fields/AuthDirective.php, src/Schema/Directives/Fields/CanDirective.php, src/Schema/Directives/Fields/EventDirective.php, src/Schema/Directives/Fields/FirstDirective.php, src/Schema/Directives/Fields/InjectDirective.php, src/Schema/Directives/Fields/MethodDirective.php, src/Schema/Factories/FieldFactory.php, src/Schema/ResolverProvider.php, src/Schema/Values/FieldValue.php, src/Subscriptions/SubscriptionResolverProvider.php, src/Subscriptions/SubscriptionServiceProvider.php, src/Support/Contracts/ProvidesResolver.php, src/Support/Contracts/ProvidesSubscriptionResolver.php, tests/Integration/CustomDefaultResolverTest.php, tests/Unit/Schema/ResolverProviderTest.php
Resolves #590
It is now possible to swap out the default resolver for:
- queries and mutations
- subscriptions
- non-root fields
Many people come into Slack and do not understand the basics of how to resolve fields.
I tried to put that in a more prominent position in the docs and hopefully make it easier to spot for newcomers.
**Breaking Changes**
Nope, behaviour is the same.
=> Enhance the basics of resolving fields

src/Defer/DeferrableDirective.php, src/Execution/DataLoader/BatchLoader.php, src/GraphQL.php, src/Schema/AST/ASTBuilder.php, src/Schema/Directives/Fields/AuthDirective.php, src/Schema/Directives/Fields/CreateDirective.php, src/Schema/Directives/Fields/UpdateDirective.php, src/Schema/Types/Scalars/Date.php, src/Schema/Types/Scalars/DateTime.php, src/Support/Http/Controllers/GraphQLController.php, src/Tracing/Tracing.php, tests/Integration/Schema/Directives/CacheDirectiveTest.php
Change all `private` accessors to `protected`.
There is value in having a smaller public API (which `protected` class members are a part of by nature of inheritence), but the current usage of `private` was rather incidental.
Let's at least have it consistent for now.
=> Replace incidental usage of private with protected

docs/3.0/guides/schema-organisation.md, tests/Unit/Schema/SchemaBuilderTest.php
Developers often think that they have to provide dummy queries or mutations in the root schema in order to avoid this error: `Error: Query root type must be provided`
Actually adding an empty `type Query` (without curly braces) is enough.
The same applies for `type Mutation`, to avoid the following error: `"Schema is not configured for mutations."`
**Changes**
Add documentation about the empty Query field in the root schema.
None
**TODO**
=> Add documentation about the empty Query type in the root schema.

tests/Integration/Schema/Directives/FindDirectiveTest.php
When ModelNotFound exception is triggered, assert that an empty object will be returned with a 200 status code.
Closes https://github.com/nuwave/lighthouse/issues/500
**Changes**
=> Assert that a 200 is returned when a model is not found.

CHANGELOG.md, config/config.php, docs/master/getting-started/configuration.md, src/Execution/DataLoader/RelationBatchLoader.php, src/Schema/Directives/ComplexityDirective.php, src/Schema/Directives/PaginateDirective.php, src/Schema/Directives/PaginationManipulator.php, src/Schema/Types/PaginatorField.php, tests/TestCase.php, tests/Unit/Schema/Directives/ComplexityDirectiveTest.php, tests/Unit/Schema/Directives/PaginateDirectiveTest.php
It sets the name to use for the generated argument on paginated fields
that controls how many results are returned.
This will default to "first" in v4.
Resolves https://github.com/nuwave/lighthouse/issues/620
**Changes**
Users can now use `first` instead of `count` when using default pagination.
No, but the default will change in v4.
=> Add config option pagination_amount_argument

CHANGELOG.md, src/Execution/MutationExecutor.php
Resolves #728
Closes #732
**Changes**
Apply the nested operations within a nested mutation in a consistent order
that makes sense.
This makes sure we are in line with what the spec requirement that the argument
order given by the client must not matter: https://graphql.github.io/graphql-spec/draft/#sec-Language.Arguments
Nope, the previous behaviour was inconsistent and flaky.
=> Fixed order for nested operations

CHANGELOG.md, src/Schema/Factories/FieldFactory.php
This avoids unnecessary calls into the container and fixes a bug that prevented
its instantiation.
Resolves #755 ~~(hopefully)~~ definitely!
=> Instantiate the ErrorBuffer directly

src/LighthouseServiceProvider.php, src/Support/Http/Controllers/GraphQLController.php, tests/Integration/MultipleRequestsTest.php, tests/TestCase.php
This prevents a weird error that occurs in tests.
If `GraphQLRequest` is a singleton and test code fires multiple HTTP requests, Lighthouse
always receives the same request.
**Changes**
Forget the  `GraphQLRequest` in the container after resolving each individual HTTP request.
No
=> Refresh GraphQLRequest singleton between multiple requests

CHANGELOG.md, src/Support/Contracts/SubscriptionExceptionHandler.php
Let's bundle all the Subscription related classes together.
We can apply the announced change in v4.
=> Announce deprecation: The class `SubscriptionExceptionHandler` will be moved to the namespace Nuwave\Lighthouse\Subscriptions\Contracts

src/Schema/Directives/GroupDirective.php, src/Schema/Directives/MiddlewareDirective.php, src/Schema/Factories/NodeFactory.php, src/Schema/SchemaBuilder.php, src/Subscriptions/SubscriptionRegistry.php, src/Support/Http/Responses/MemoryStream.php, src/Support/Http/Responses/ResponseStream.php, src/Support/Http/Responses/Stream.php, src/Support/Pipeline.php, tests/Integration/Defer/DeferDBTest.php, tests/Integration/GraphQLTest.php
The `toArray()` function actually calls `toArray()` recursively, which is not actually what we want in all of those cases - we just need the underlying items.
This should improve performance a bit.
=> Avoid calling ->toArray on collections when we just want to unwrap it

CHANGELOG.md, src/Schema/Factories/FieldFactory.php, tests/Unit/Schema/Directives/SpreadDirectiveTest.php
- fixes issue where a where an error occurs if a query that accepts a spreaded input does not actually pass in the input (even if not set as required)
- tests added to verify fix
Resolves #770  
**Changes**
- You can now omit an input from your query that uses the spread directive without getting an error
None
=> Allow Query input argument using `@spread` to be optional

CHANGELOG.md, src/Schema/Directives/CreateDirective.php, src/Schema/Directives/UpdateDirective.php
not sure how to go about this, no tests exist for these classes
no documentation necessary
not sure how to go about this
When using Lighthouse on a Lumen or Laravel project with multiple database connections, the `@create` and `@update` directives use the default database without respecting the model's declared connection. This trivial patch fixes this.
**Changes**
When calling `DatabaseManager::connection()`, provide `Model::getConnectionName()` for the optional `name` argument. This will then open a transaction on the main model's connection. The case where nested models define different database connections for themselves is NOT handled, as in that case, transactional behaviour cannot be guaranteed anyway.
This is a trivial fix and should …
=> Respect the model's connection for database transaction  during `@create` and `@update`

CHANGELOG.md, config/config.php, docs/master/getting-started/configuration.md
This config option is not really necessary and i think nobody is using it, the implementation in the Controller is pretty basic but does enough so that i do not think anyone would want to reimplement it.
It is easy to define another controller thorugh Laravel if needed and call the rest of Lighthouse.
This just marks the config option as deprecated for v4.
=> Deprecate controller config

CHANGELOG.md, composer.json, docs/master/getting-started/migrating-to-lighthouse.md, docs/master/guides/native-php-types.md, docs/master/sidebar.js, docs/master/the-basics/types.md, src/Schema/Types/LaravelEnumType.php, tests/Unit/Schema/Types/LaravelEnumTypeTest.php, tests/Utils/LaravelEnums/UserType.php, tests/Utils/Models/User.php, tests/database/migrations/2018_02_28_000002_create_testbench_users_table.php
Resolves https://github.com/nuwave/lighthouse/issues/771
**Changes**
- Explicitely document how to register native PHP types with the TypeRegistry
- Add convenience wrapper for registering Enum types based on [BenSampo/laravel-enum](https://github.com/BenSampo/laravel-enum)
Nope
=> Document usage of native PHP types, add convencience wrapper for bensampo/laravel-enum

CHANGELOG.md, src/Schema/Directives/DeprecatedDirective.php, tests/Unit/Schema/Directives/DeprecatedDirectiveTest.php
https://graphql.github.io/graphql-spec/draft/#sec--deprecated
=> Use the spec-compliant default deprecation reason for `@deprecate` directive

CHANGELOG.md, src/WhereConstraints/WhereConstraintsDirective.php, tests/Integration/WhereConstraints/WhereConstraintsDirectiveTest.php
Resolves #799 
**Changes**
Searching for an empty string using where constraints use to cause an error, it now searches for an empty string 
If someone was counting on searching for an empty string returning an error it will no longer do that
=> Fix querying for falsy values through `@whereConstraints`

CHANGELOG.md, config/config.php, docs/master/getting-started/configuration.md, src/GraphQL.php
Allow users to customise the expiration time of schema cache.
For example, this is useful when using redis cache with default `maxmemory-policy noeviction`.
**Changes**
Add new config option `cache.ttl`, which mirrors the corresponding parameter of `Cache::remember()`.
The default behaviour of remembering permanently is unaffected.
=> Add config option `cache.ttl` to control expiration time of schema cache

CHANGELOG.md, docs/master/getting-started/installation.md, src/LighthouseServiceProvider.php, src/Support/Facades/GraphQLFacade.php, tests/TestCase.php
Reduce incidental complexity and overhead by offering only one way to do things.
=> The `GraphQL` facade and the container alias `graphql` will be removed in v4

docs/3.6/getting-started/tutorial.md, docs/master/getting-started/tutorial.md
Fixed typo in the file name from `Users.php` to the correct singular name `User.php`
**Changes**
Fixed a typo in name of `User.php`, before it was named as plural `Users.php`
Found in this [Getting started tutorial](https://lighthouse-php.com/3.6/getting-started/tutorial.html#the-models)
=> Typo: Rename model Users to User

CHANGELOG.md, src/Execution/Utils/Subscription.php, src/Subscriptions/Authorizer.php, src/Subscriptions/Contracts/SubscriptionExceptionHandler.php, src/Subscriptions/ExceptionHandler.php, src/Subscriptions/SubscriptionServiceProvider.php
As announced in the deprecation notice:
Move `SubscriptionExceptionHandler` into namespace `Nuwave\Lighthouse\Subscriptions\Contracts`
=> Move subscription exception handler namespace

CHANGELOG.md, config/config.php, docs/master/getting-started/configuration.md, src/Support/Http/routes.php, src/Testing/MakesGraphQLRequests.php, tests/TestCase.php
Remove settings that provide little to no benefit and are unlikely to be used:
- `controller`
- `route_enable_get`
...and reduce the route configuration to 3 clearly named options that are useful, all nested within the `route` key to clearly group them together.
=> Simplify the route configuration

tests/Integration/GraphQLTest.php, tests/Unit/Schema/Factories/DirectiveFactoryTest.php
This PR removes a couple of warnings that show up on test execution about PHPUnit's deprecated assertion methods.
**Changes**
No changes in behaviour.
=> Replace deprecated PHPUnit assertion methods

CHANGELOG.md, src/Execution/MutationExecutor.php, tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php
In `belongsToMany` relationships, when using `sync` nested operation with an empty array no updates are executed. The expected behaviour from Eloquent is to disconnect all related models on an empty sync operation.
**Changes**
A change was made in `MutationExecution` class to correctly validate and pass empty arrays when present on sync operations.
It will behave differently if someone relies on the current behaviour of not executing updates on the relationship when sync is called with an empty array.
I believe Lighthouse should follow Eloquent functionality verbatim and that's why I suggest this change.
=> Allow empty arrays and other falsy values as input for nested mutation operations like "sync"

CHANGELOG.md, src/Schema/Directives/CanDirective.php, tests/Unit/Schema/Directives/CanDirectiveDbTest.php, tests/Unit/Schema/Directives/CanDirectiveTest.php, tests/Utils/Policies/PostPolicy.php, tests/Utils/Policies/UserPolicy.php
`@can` directive fails if an array of `ID` is passed. For example in the `@delete` directive, as it described in the docs. 
```graphql
deletePosts(id: [ID!]!): [Posts!]! @delete @can(ability: "delete")
```
It happens when `[ID!]!` is passed as an input. In this case, we have to handle Collection.
**Changes**
Check if Collection was provided and run `Gate::check` for each item.
Edit by @spawnia:
While i was at it, i removed the deprecated alias `if` of the `@can` directive.
The migration is straightforward:
```diff
type Mutation {
- deletePost(id: ID!): Post @can(if: "delete")
+ deletePost(id: ID!): Post @can(ability: "delete")
}
```
=> Fix @can directive with multiple models and remove deprecated "if" alias

CHANGELOG.md, docs/master/eloquent/nested-mutations.md, src/Execution/MutationExecutor.php, tests/Integration/Execution/MutationExecutor/MorphToTest.php, tests/database/migrations/2018_02_28_000000_create_testbench_hours_table.php
Allows connecting and disconnecting polymorphic associations for a MorphTo relation using nested mutations.
**Changes**
Implement `connect` and `disconnect`
The GraphQL Specification does not support Input Union types,
for now we are limiting this implementation to `connect` and `disconnect` operations.
Let's see which one of the current RFC's makes it and base the implementation of `create` and `update` upon that. https://github.com/graphql/graphql-spec/issues/114
Nope
=> Implement `connect`, `disconnect` and `delete` operations for nested mutations upon MorphTo relationships

CHANGELOG.md, composer.json, docs/master/the-basics/types.md, src/Schema/Types/LaravelEnumType.php, tests/Unit/Schema/Types/LaravelEnumTypeTest.php
When receiving enum values as an input, they are now converted to Enum instances instead of their internal values.
Given a query like this:
```graphql
{
foo(bar: BAZ)
}
```
And an enum like this:
```php
<?php
namespace App\Enums;
use BenSampo\Enum\Enum;
/**
* @method static static BAZ
*/
final class Bar extends Enum
{
const BAZ = 123;
}
```
The argument passed to the resolver is now an enum instance:
```diff
function resolveFoo($root, array $args)
{
var_dump($args['bar'])
-   int(123)
+   class App\Enums\Baz#3120 (3) {
+     public $key =>
+     string(7) "BAZ"
+     public $value =>
+     int(123)
+     public $description =>
+     string(3) "123"
+  }
}
```
Code like this will now work:
```php
function resolveFoo($root, array $args)
{
doSomethingWithBar($args['bar'])
}
function …
```
=> Change the `Nuwave\Lighthouse\Schema\Types\LaravelEnumType` wrapper to map to Enum instances internally

docs/.vuepress/lib/versioning.js
By default when using  `composer require nuwave/lighthouse` you get **latest stable release** , not "master".
For that reason the default entrypoint should point to the "latest stable release" of docs, not "master".
Mainly will change home page buttons links like "READ MORE" and "READ THE DOCS".
NOTE: This PR does not fix a broken link on home page (Eloquent section). Will be fixed by #904.
=> [docs] Change behavior of docs entrypoint

docs/.vuepress/lib/versioning.js
For new upcoming versions this fix will always keep 'master' version on top of list followed by new generated version.
```
yarn docs:version 4.0
```
versions.js
```js
[
"master",
"4.0", // <--- will be inserted in here
"3.7",
"3.6",
"3.5",
"3.4",
"3.3",
"3.2",
"3.1",
"3.0",
"2.6"
]
```
=> [docs] Fix chronological  order for "yarn docs:version"

src/Execution/MutationExecutor.php
This prevents an error that occurs when using an Enum to represent the argument and ensures the actual classname of the Model is passed on.
Nope
=> Cast MorphTo relation argument `type` to string before connect

src/Schema/SchemaBuilder.php, src/Subscriptions/SubscriptionResolverProvider.php, src/Support/Contracts/ProvidesSubscriptionResolver.php, tests/Unit/Subscriptions/Broadcast/BroadcastTest.php, tests/Utils/Subscriptions/TaskUpdated.php
Resolves https://github.com/nuwave/lighthouse/issues/851
**Changes**
=> Eager-load the subscription fields to ensure they are registered

docs/master/api-reference/directives.md
This resolves #888 by directing the reader to check out the `@model` directive when viewing the `@node` directive.
=> Call out @model in @node directive in documentations

src/Exceptions/ValidationException.php, src/Schema/Directives/ValidationDirective.php, src/Schema/Factories/FieldFactory.php, tests/Integration/ValidationTest.php
Resolves https://github.com/nuwave/lighthouse/issues/897
**Changes**
Ensure validation actually runs before the final resolver
I skipped the test `itCombinesFieldValidationAndArgumentValidation` for now, as it would require a larger rework of how we run validation.
This ensures that `v4` does not cause regressions.
=>  Ensure validation actually runs before the final resolver

.travis.yml, CHANGELOG.md, Dockerfile, docker-compose.yml, docs/master/api-reference/directives.md, src/Schema/Directives/WhereJsonContainsDirective.php, tests/DBTestCase.php, tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php, tests/Integration/Schema/Directives/CacheDirectiveTest.php, tests/Unit/Schema/Directives/WhereJsonContainsDirectiveTest.php, tests/database/migrations/2018_02_28_000000_create_testbench_hours_table.php
While the `@where` directive offers flexible clauses, it did not work for a `whereJsonContains` query, as the method does not take a second argument `operator`.
**Changes**
Use an input value as a [whereJsonContains filter](https://laravel.com/docs/queries#json-where-clauses).
```graphql
type Query {
posts(tags: [String]! @whereJsonContains): [Post!]! @all
}
```
You may use the `key` argument to look into the JSON content:
```graphql
type Query {
posts(tags: [String]! @whereJsonContains(key: "tags->recent")): [Post!]! @all
}
```
```graphql
"""
Use an input value as a [whereJsonContains filter](https://laravel.com/docs/queries#json-where-clauses).
"""
directive @whereJsonContains(
"""
Specify the database column and path inside the JSON to compare. 
Only required …
```
=> Add @whereJsonContains directive

CHANGELOG.md, docs/master/api-reference/directives.md, docs/master/testing/phpunit.md, src/Testing/MakesGraphQLRequests.php, src/WhereConstraints/WhereConstraintsDirective.php, src/WhereConstraints/WhereConstraintsServiceProvider.php, tests/Integration/IntrospectionTest.php, tests/Integration/WhereConstraints/WhereConstraintsDirectiveTest.php, tests/Unit/Schema/ClientDirectiveTest.php
Restrict the allowed column names to a well-defined list in `@whereContraints`.
This improves introspection capabilities and security.
**Changes**
Through the `columns` argument on `@whereConstraints`, a user may list allowed columns.
```graphql
type Query {
people(
where: WhereConstraints @whereConstraints(columns: ["age", "type", "haircolour", "height"])
): [Person!]!
}
```
Lighthouse generates definitions for an `Enum` type and an `Input` type
that are restricted to the defined columns.
```graphql
"Dynamic WHERE constraints for the `where` argument on the query `people`.
input PeopleWhereWhereConstraints {
column: PeopleWhereColumn
operator: String = EQ
value: Mixed
AND: [PeopleWhereWhereConstraints!]
OR: [PeopleWhereWhereConstraints!]
NOT: …
```
=> Restrict `@whereConstraints` column names to a well-defined list

CHANGELOG.md, src/Schema/Directives/ValidationDirective.php, tests/Integration/ValidationTest.php, tests/Utils/Directives/ComplexValidationDirective.php
Fixes `$this->args` being `null` inside the `rules()` method of validators extending `ValidationDirective`
**Changes**
Adds $this->setArgs($args) to the `ValidationDirective`. I've updated and added a test to ensure this works.
The test that tested if the `$this->args` was set, did not actually test it. It only tested if the unique rule was being applied. That it did, but it tried to update a different record, which has no effect on the value for the `->ignore()` part. In order to actually test this, I wrote a test that updated the same entity with the same name. Now, it started to complain that it was not unique. This got me to look into to the actual generated rule string, and it turns out the id value was `NULL`, instead of the value we wanted it to be.
After this fix, the rule has the …
=> Fix validators not having access to the given args for the query or mutation

CHANGELOG.md, src/Execution/Builder.php, tests/Unit/Schema/Types/LaravelEnumTypeTest.php
When using laravel-enum based values with builder directives such as `@whereJsonContains`, Laravel did not use the internal value of the Enum.
Fixes a regression caused through https://github.com/nuwave/lighthouse/pull/908
**Changes**
Unbox instances of `\BenSampo\Enum\Enum` when using them in a builder directive.
No
=> Unbox laravel-enum inputs when using the builder directives

docs/pages/resources.md
Package is no longer maintained
=> Remove Lighthouse Utils package from plugins list

docs/master/subscriptions/getting-started.md
Currently, we do not mention the webhook at all. Not using the webhook, causes a pile of subscriptions to build up over time, which increases the Pusher-usage significantly.
=> Add webhook to subscription docs

.travis.yml, CHANGELOG.md, composer.json
This PR adds support for the upcoming Laravel 6.x release.
Resolves https://github.com/nuwave/lighthouse/issues/940
**Changes**
Adds `^6.0` to the `composer.json` version constraints for laravel framework packages. Everything appears to be working fine on a Laravel 6 app I'm using this in.
=> Add support for Laravel ^6.0

CHANGELOG.md, src/Console/IdeHelperCommand.php, tests/Unit/Console/IdeHelperCommandTest.php
- [x ] Added or updated tests
~~- [ ] Added Docs for all relevant version~~
- [x ] Updated the changelog
Resolves #947 
**Changes**
TODO remove if https://gitlab.com/hpierce1102/ClassFinder/merge_requests/16 is merged
The ClassFinder throws if no classes are found. Since we can not know
in advance if the user has defined custom directives, this behaviour is problematic.
No.
=> Prevent throwing in `lighthouse:ide-helper` when no custom directives are defined

CHANGELOG.md, composer.json, src/Defer/DeferServiceProvider.php, src/Schema/Factories/DirectiveFactory.php, src/Tracing/TracingServiceProvider.php, src/WhereConstraints/WhereConstraintsServiceProvider.php, tests/Integration/WhereConstraints/WhereConstraintsDirectiveTest.php
**Changes**
Change the way, how experimental `@whereConstraints` directive is registered. Earlier it was added to directive factory. Thus `@whereConstraints` was not recognised by IDE Helper.
Now directive is registered via adding its namespace to directives namespaces array. Thus IDE helper has additional namespace, when `WhereConstraintsServiceProvider` is enabled.  
I also fixed deprecated notice for `assertArraySubset`. This assertions seems to be deleted in PHPUnit 9, as there were some misunderstood usages over the time. Author gave no suggestions how to replace it, and people just exported this functionality to an extra package. 
No breaking changes
=> Register extension directives only through RegisterDirectiveNamespaces event

CHANGELOG.md, config/config.php, docs/master/getting-started/configuration.md, src/Support/Http/routes.php, tests/Integration/RouteRegistrationTest.php
**Changes**
Adds support for graphql route group, so we can use router group specific config like domain, prefix, etc.
None
=> Allow additional route configurations `prefix` and `domain`

CHANGELOG.md, src/Schema/TypeRegistry.php
~Work in progress still!~
Figures below are by no means scientific but measured in a real app with a large schema on a local machine while running in production mode with `php artisan optimize`. Tested and compared with Blackfire.
- e6655df: ~10%
It looks so far like the most gains to be had are in the underlying GraphQL library itself related to the query validator.
The relatively small query I am testing with (fieldnames are dummies):
```graphql
query userDiscovery($id: String!) {
user(id: $id) {
id
field1
field2
__typename
}
viewer {
id
tenant {
id
settings {
field1
field2
field3
__typename
}
__typename
}
field1
field2
field3
__typename
}
}
```
---
Related #772
**Changes**
Non-breaking changes that should improve the performance of some code paths resulting in faster response times.
=> Performance wins

CHANGELOG.md, docs/master/the-basics/types.md, src/Schema/Types/LaravelEnumType.php, tests/Unit/Schema/Types/LaravelEnumTypeTest.php
This allows aliasing enum classes in case of unclear naming or name conflicts.
**Changes**
By default, the generated type will be named just like the given class.
```php
$enum = new LaravelEnumType(UserType::class);
var_dump($enum->name); // UserType
```
You may overwrite the name if the default does not fit or you have a name conflict.
```php
$enum = new LaravelEnumType(UserType::class, 'UserKind');
var_dump($enum->name); // UserKind
```
No.
=> Allow overwriting the name of Enum types created through `LaravelEnumType`

composer.json, src/Console/IdeHelperCommand.php
**Changes**
No longer needed as of https://gitlab.com/hpierce1102/ClassFinder/merge_requests/16 and the related release of `0.4.0`
No
=> Remove try-catch around ClassFinder call in IdeHelperCommand

CHANGELOG.md, src/Execution/Utils/GlobalId.php
**Changes**
Trim return values from decodeID and decodeType.
I have the following schema.
```graphql
input UpdateCityInput {
cityId: ID! @globalId(decode: "ID")
...
}
```
Sometimes the returned value has a new line at the end, for this reason, the Laravel find method does not find the record.
None.
=> Fix extra new line in GlobalId::decode

CHANGELOG.md, src/Execution/BaseRequest.php, tests/Integration/GraphQLTest.php
Fixes #730 and partially fixes #669.
**Changes**
Now `BaseRequest::query()` returns an empty string when `LighthouseRequest::fieldValue()` returns `null`, which causes a GraphQL syntax error when making an empty request instead of a `FatalThrowableError`.
=> Improve error message when making an empty request

CHANGELOG.md, docs/master/api-reference/directives.md, src/Schema/Directives/CountDirective.php, tests/DBTestCase.php, tests/Unit/Schema/Directives/CountDirectiveTest.php
You could do something close to this by using the paginator, however then you are forced to fetch at least one model, and also you are exposing data your might not wanna expose. This directive solves this by just having a simple count directive.
**Changes**
Adds a new directive for getting the count of a relation.
New directive added, so shouldn't be breaking.
=> [Feat] Added @count directive

docs/4.1/api-reference/directives.md, docs/4.2/api-reference/directives.md, docs/4.3/api-reference/directives.md, docs/4.4/api-reference/directives.md, docs/master/api-reference/directives.md, src/Schema/Directives/BuilderDirective.php
Looks like the builder directive was using the wrong definition as it is applied on arguments not on fields.
=> [Docs] Fix wrong definition in builder directive

composer.json, phpunit.xml.dist, tests/DBTestCase.php, tests/Integration/Console/IdeHelperCommandTest.php, tests/Integration/Console/UnionDirective.php, tests/Integration/Schema/Directives/CanDirectiveDBTest.php, tests/Integration/Schema/Directives/CountDirectiveDBTest.php, tests/Integration/Schema/Directives/InjectDirectiveDBTest.php, tests/Integration/Schema/Directives/OrderByDirectiveDBTest.php, tests/Integration/Schema/Directives/PaginateDirectiveDBTest.php, tests/Integration/Schema/Directives/SpreadDirectiveDBTest.php, tests/Integration/Schema/Directives/WhereJsonContainsDirectiveDBTest.php, tests/Integration/Schema/Types/LaravelEnumTypeDBTest.php, tests/Integration/Subscriptions/Broadcast/BroadcastDBTest.php, tests/Unit/Events/BuildSchemaStringTest.php, tests/Unit/Events/ManipulateResultTest.php, tests/Unit/Events/RegisterDirectiveNamespacesTest.php, tests/Unit/Schema/Directives/CountDirectiveTest.php, tests/Unit/Schema/Directives/PaginateDirectiveTest.php, tests/Unit/Schema/Directives/SpreadDirectiveTest.php, tests/Unit/Schema/Source/SchemaSourceProviderTest.php, tests/Unit/Subscriptions/BroadcastManagerTest.php, tests/Unit/Subscriptions/StorageManagerTest.php
I was getting annoyed.
- Add https://github.com/johnkary/phpunit-speedtrap for measuring slow tests
- Truncate inbetween DB tests instead of migrating
- Move all DB tests into Integration suite
- Split/combine some tests
In my local environment, that brings the execution time for all tests down from +4min to about 2min.
=> Speed up tests

src/Schema/AST/ASTBuilder.php
This might happen when users upgrade to `v4`.
```
$ php artisan lighthouse:validate-schema
ErrorException  : Undefined index: ttl
at /builds/kt7nLJ3G/0/limes/limes-api/vendor/nuwave/lighthouse/src/Schema/AST/ASTBuilder.php:92
88|         $cacheConfig = $this->configRepository->get('lighthouse.cache');
89|         if ($cacheConfig['enable']) {
90|             $this->documentAST = app('cache')->remember(
91|                 $cacheConfig['key'],
> 92|                 $cacheConfig['ttl'],
93|                 function (): DocumentAST {
94|                     return $this->build();
95|                 }
96|             );
Exception trace:
1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: ttl", "/builds/kt7nLJ3G/0/limes/limes-api/vendor/nuwave/lighthouse/src/Sch …
```
=> Add fallback if ttl config is missing

CHANGELOG.md, docs/4.4/api-reference/directives.md, docs/master/api-reference/directives.md, docs/master/eloquent/getting-started.md, docs/master/eloquent/nested-mutations.md, src/Execution/MutationExecutor.php, src/Schema/Directives/CreateDirective.php, src/Schema/Directives/MutationExecutorDirective.php, src/Schema/Directives/UpdateDirective.php, src/Schema/Directives/UpsertDirective.php, tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php, tests/Integration/Execution/MutationExecutor/BelongsToTest.php, tests/Integration/Execution/MutationExecutor/HasManyTest.php, tests/Integration/Execution/MutationExecutor/HasOneTest.php, tests/Integration/Execution/MutationExecutor/MorphManyTest.php, tests/Integration/Execution/MutationExecutor/MorphOneTest.php, tests/Integration/Execution/MutationExecutor/MorphToManyTest.php, tests/Integration/Execution/MutationExecutor/MorphToTest.php, tests/Integration/Schema/Directives/UpdateDirectiveTest.php
Resolves #995 
**Changes**
Use the [@upsert](../api-reference/directives.md#upsert) directive to update a model with 
a given `id` or create it if it does not exist. 
```graphql
type Mutation {
upsertUser(id: ID!, name: String!, email: String): User @upsert
}
```
Since upsert can create or update your data you must have all the minimum fields for a creation as required.
The `id` is always required and must be marked as fillable in the model.
```graphql
mutation {
upsertUser(id: "123" name: "Hillary"){
id
name
email
}
}
```
```json
{
"data": {
"upsertUser": {
"id": "123",
"name": "Hillary",
"email": null
}
}
}
```
You can now expose a nested operation `upsert` in all nested mutations that support the `update` operation.
\-
=> Add `@upsert` directive and nested mutation operations to create or update a model   regardless whether it exists

CHANGELOG.md, src/Schema/TypeRegistry.php, tests/Integration/SchemaCachingTest.php, tests/SerializingArrayStore.php
Fixes #1004
**Changes**
Fix broken behaviour when using union types with schema caching.
The test triggers the behaviour mentioned in #1004
```
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.3.8 with Xdebug 2.7.2
Configuration: /var/www/phpunit.xml.dist
E                                                                   1 / 1 (100%)
Time: 7.09 seconds, Memory: 32.00 MB
There was 1 error:
1) Tests\Integration\SchemaCachingTest::testSchemaCachingWithUnionType
ErrorException: array_map(): Expected parameter 2 to be an array, object given
/var/www/src/Schema/TypeRegistry.php:428
```
No
=> Fix broken behaviour when using union types with schema caching

CHANGELOG.md, src/Execution/Arguments/TypedArgs.php, tests/Unit/Execution/Arguments/TypedArgsTest.php
**Changes**
The new `TypedArgs` wrapper produced an error when a client passes `null` as the value of an argument that is defined as a list of type.
Failing test:
```
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.3.9 with Xdebug 2.7.2
Configuration: /projects/lighthouse/phpunit.xml.dist
.E                                                                  2 / 2 (100%)
Time: 1.29 seconds, Memory: 28.00 MB
There was 1 error:
1) Tests\Unit\Execution\Arguments\TypedArgsTest::testNullableList
ErrorException: Invalid argument supplied for foreach()
/projects/lighthouse/src/Execution/Arguments/TypedArgs.php:149
```
No
=> Handle `null` being passed to a nullable argument that is a list of type

CHANGELOG.md, src/Schema/Factories/ClientDirectiveFactory.php
Resolves #1018
**Changes**
Convert the array_map to a simple foreach because the mappable is not always a pure array.
None.
=> Fix conversion of client directives after the schema was cached

CHANGELOG.md, src/Execution/Arguments/TypedArgs.php, tests/Unit/Execution/Arguments/TypedArgsTest.php
**Changes**
Converting client-given args to an `ArgumentSet` fails when `null` is given for an argument that is defined as an `input`.
Added a failing test:
```
1) Tests\Unit\Execution\Arguments\TypedArgsTest::testNullableInputObject
TypeError: Argument 1 passed to Nuwave\Lighthouse\Execution\Arguments\TypedArgs::wrapArgs() must be of the type array, null given, called in /var/www/src/Execution/Arguments/TypedArgs.php on line 193
/var/www/src/Execution/Arguments/TypedArgs.php:91
```
It works now.
No
=> Handle nullable input objects in TypedArgs conversion

CHANGELOG.md, src/Schema/Types/LaravelEnumType.php, tests/Unit/Schema/Types/LaravelEnumTypeTest.php, tests/Utils/LaravelEnums/LocalizedUserType.php
**Changes**
Description of LaravelEnumType should using `$enum->desciption` for more detail
=> Use detailed `$description` property when generating `enum` values from a `BenSampo\Enum\Enum` class

CHANGELOG.md, src/Console/InterfaceCommand.php, src/Console/LighthouseGeneratorCommand.php, src/Console/MutationCommand.php, src/Console/QueryCommand.php, src/Console/ScalarCommand.php, src/Console/SubscriptionCommand.php, src/Console/UnionCommand.php, tests/Unit/Console/LighthouseGeneratorCommandTest.php
Resolves https://github.com/nuwave/lighthouse/issues/1029
**Changes**
When the configuration holds an array of namespaces, the generator commands currently fail with:
```
QueryCommand::getDefaultNamespace() must be of the type string, array returned
```
This handles the case of multiple default namespaces by identifying the common part of all configured namespaces and uses that to generate the class.
Just like Laravel generator commands, sub-namespaces can be added:
```
php artisan lighthouse:query Sub\\Foo
```
No
=> Handle arrays of namespaces in generator commands

CHANGELOG.md, docs/master/api-reference/directives.md, src/Execution/Arguments/ArgumentSet.php, src/Schema/Directives/CanDirective.php, tests/Integration/Schema/Directives/CanDirectiveDBTest.php, tests/Utils/Policies/AuthServiceProvider.php, tests/Utils/Policies/TaskPolicy.php
Using `@can` on softDeleted models is not working as expected. Within `@can` directive simple query builder gets created without respecting soft deleted models. `@softDeletes` directive ist also doesn't help here, as it is not processed in builder-creation
**Changes**
We should somehow rework, how `@can` fetches model for checking access. Take a look at line 83 in file `Nuwave\Lighthouse\Schema\Directives\CanDirective`. There is the problem. I tried to use following code:
```php
$resolveInfo
->argumentSet
->enhanceBuilder(
$this->getModelClass()::query(),
$this->directiveArgValue('scopes', [])
)
->findOrFail($args[$find]);
```
This piece is from `@find`, `@all` etc. directives. With given changes it works for my test, but failes the `testThrowsIfNotAuthorized` test with following error: …
=> Rework how @can directive fetches model (@softDeletes are not working)

CHANGELOG.md, docs/master/eloquent/nested-mutations.md, src/Execution/MutationExecutor.php, tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php
**Changes**
Adds support for `syncWithoutDetaching` method on BelongsToMany relationships.
Should be no breaking changes.
=> Add `syncWithoutDetaching` option for BelongsToMany and MorphToMany relationships

CHANGELOG.md, docs/master/api-reference/directives.md, src/Schema/Directives/CanDirective.php, tests/Unit/Schema/Directives/CanDirectiveTest.php, tests/Utils/Policies/UserPolicy.php
Resolves #1002 
**Changes**
Added a new argument to avoid breaking changes with the current version.
Saying that I think `args` (getAdditionalArguments) is always a plain string, it doesn't have to much sense to me
=> Add `injectArgs` option to `@can` directive to pass along client defined   arguments to the policy check

CHANGELOG.md, docs/.vuepress/config.js, docs/.vuepress/styles/index.styl, docs/package.json, docs/yarn.lock
**Changes**
Changes the Vuepress theme to be an extension of the default theme with dark mode support using prefers-color-scheme.
Other changes: 
- Switch to Vuepress theme with prefers-color-scheme / dark mode support
- Add CSS variables for lighthouse color scheme
- Migrate font @import into <head> declaration for performance
Docs theme will change when using an OS & browser with dark mode support. Otherwise not that I'm aware of.
=> Add Dark Theme for Docs

docs/.vuepress/styles/index.styl
**Changes**
Fixes `pre` / `code` text color when light color scheme is explicitly set
=> Fix text color on code blocks when light color scheme is explicitly set

.travis.yml, composer.json
Sometime in the last few weeks, travis seems to have changed and now defaults to lower dependencies. This causes a test failure when running against Laravel `5.5.*`.
```
0.16s$ if [[ $LARAVEL = '5.5.*' ]]; then composer remove --dev nunomaduro/larastan --no-update; fi
install.2
61.81s$ composer require "illuminate/contracts:${LARAVEL}" --no-interaction --prefer-dist --no-interaction --no-suggest
36.16s$ vendor/bin/phpunit --colors=always --verbose
PHPUnit 6.0.8 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.1.27
Configuration: /home/travis/build/nuwave/lighthouse/phpunit.xml.dist
...............................................................  63 / 527 ( 11%)
..EE..S..................................................E..... 126 / 527 ( 23%) …
```
=> Avoid old dependencies in Travis CI

CHANGELOG.md, src/Schema/TypeRegistry.php, tests/Unit/Schema/TypeRegistryTest.php
**Changes**
Throw a descriptive error instead of getting an `Undefined index`.
No.
=> Throw DefinitionException when missing a type in the type registry

CHANGELOG.md, docs/3.7/api-reference/directives.md, docs/4.0/api-reference/directives.md, docs/4.1/api-reference/directives.md, docs/4.2/api-reference/directives.md, docs/4.3/api-reference/directives.md, docs/4.4/api-reference/directives.md, docs/4.5/api-reference/directives.md, docs/4.6/api-reference/directives.md, docs/master/api-reference/directives.md, src/Schema/Directives/OrderByDirective.php
Resolves #1048 
**Changes**
Adds `INPUT_FIELD_DEFINITION` to the directive location for `orderBy` directive and provides example on how to use.
None.
=> Add INPUT_FIELD_DEFINITION to orderBy directive location

CHANGELOG.md, docs/4.1/api-reference/directives.md, docs/4.2/api-reference/directives.md, docs/4.3/api-reference/directives.md, docs/4.4/api-reference/directives.md, docs/4.5/api-reference/directives.md, docs/4.6/api-reference/directives.md, docs/4.7/api-reference/directives.md, docs/master/api-reference/directives.md, src/Schema/Directives/BuilderDirective.php
**Changes**
Adds `INPUT_FIELD_DEFINITION ` to `@builder` directive location for use with `@spread`.
=> Add `INPUT_FIELD_DEFINITION` to allowed locations for the `@builder` directive

docs/3.7/api-reference/directives.md, docs/4.0/api-reference/directives.md, docs/4.1/api-reference/directives.md, docs/4.2/api-reference/directives.md, docs/4.3/api-reference/directives.md, docs/4.4/api-reference/directives.md, docs/4.5/api-reference/directives.md, docs/4.6/api-reference/directives.md, docs/master/api-reference/directives.md, src/Schema/Directives/MiddlewareDirective.php
In some IDEs such as PHPStorm, when the middleware directive is used when extending the Query type for example, and error is shown because the directive is only defined on FIELD_DEFINITION.
Example: given the following
```
extend type Query @middleware(checks: ["auth:api"]) {}
```
The error shown is `Query' [@1:1] tried to use a directive 'middleware' in the 'OBJECT' location but that is illegal`
Adding OBJECT to the definition fixes this.
=> Add OBJECT to the @middleware directive

CHANGELOG.md, src/Schema/Directives/RulesDirective.php, tests/Unit/Schema/Directives/RulesDirectiveTest.php
**Changes**
This reifies the fact that passing rules as an array is the only valid syntax: `@rules(apply: ["min:3"])`.
No, this only uncovers latent bugs.
=> Validate at schema build time that the `apply` argument `@rules` is an array

docs/tutorial/README.md
The Post's relation `author` does not work unless you specify the `$foreignKey`. Without it, it will try to guess the foreign key based on the method name (author) so it  will try to find `author_id` instead.
The linked repo does not seem to match the tutorial: https://github.com/nuwave/lighthouse-tutorial/blame/master/app/Post.php#L9-L12
N/A
- ~[ ] Added or updated tests~
- ~[ ] Added Docs for all relevant versions~
- ~[ ] Updated CHANGELOG.md~
**Changes**
Fixed relation issue in tutorial.
N/A
=> Fix Post's author relation

README.md
Fixes 404 error
Resolves #1153
**Changes**
Changes link to contribution guidelines from `https://github.com/nuwave/lighthouse/blob/master/.github/CONTRIBUTING.md` to `https://github.com/nuwave/lighthouse/blob/master/CONTRIBUTING.md`. 
None
=> Update link to contribution guidelines

docs/master/api-reference/directives.md, src/Schema/Directives/AllDirective.php, src/Schema/Directives/CanDirective.php, src/Schema/Directives/CreateDirective.php, src/Schema/Directives/DeleteDirective.php, src/Schema/Directives/FindDirective.php, src/Schema/Directives/FirstDirective.php, src/Schema/Directives/NodeDirective.php, src/Schema/Directives/PaginateDirective.php, src/Schema/Directives/UpdateDirective.php, src/Schema/Directives/UpsertDirective.php, src/SoftDeletes/ForceDeleteDirective.php, src/SoftDeletes/RestoreDirective.php
model field is not generated in the definition causing the IDE to raise alerts
- [x ] Added or updated tests
- [x ] Added Docs for all relevant versions
- [x ] Updated CHANGELOG.md
Resolves non
**Changes**
Added model directive to definition area
None
=> Add `model` argument to `@can` directive definition

CHANGELOG.md, docs/master/api-reference/directives.md, docs/master/eloquent/soft-deleting.md, docs/master/security/authorization.md, src/Schema/Directives/CanDirective.php, src/Schema/Directives/RelationDirective.php, src/Schema/Directives/WithDirective.php, tests/Integration/SoftDeletes/ForceDeleteDirectiveTest.php, tests/Integration/SoftDeletes/RestoreDirectiveTest.php, tests/Unit/Schema/Directives/CanDirectiveTest.php, tests/Utils/Policies/TaskPolicy.php
Resolves #1116 
**Changes**
Fetching model inside `@can` directive was reworked, so query builder gets extended if `@forceDelete` or `@restore` is used;  
No, old behavior still works (using `@softDeletes` with passing `trashed` argument from client). The usage of `@softDeletes` is even more granular and overrides these new implementation, as query still gets enhanced.
Should we write something to changelog? and docs?
=> Exclude or include trashed models in `@can` when `@forceDelete` or `@restore` are used

CHANGELOG.md, docker-compose.yml, docs/master/sidebar.js, docs/master/testing/extensions.md, src/Testing/TestSchemaProvider.php, src/Testing/UsesTestSchema.php, tests/Integration/Execution/MutationExecutor/MorphOneTest.php, tests/TestCase.php, tests/Unit/Schema/Directives/SpreadDirectiveTest.php, tests/Unit/Schema/Source/SchemaSourceProviderTest.php, tests/Utils/Middleware/CountRuns.php
Resolves https://github.com/nuwave/lighthouse/issues/1170
**Changes**
Expose Lighthouse's internal mechanism to use test schemas as a reusable trait. This can be useful for testing Lighthouse extensions, such as custom directives.
I also documented the usage of the `MocksResolvers` trait, which is complimentary to the `UsesTestSchema` trait.
No
=> Add `UsesTestSchema` helper trait for usage in unit tests

CHANGELOG.md, src/Execution/Arguments/ArgumentSet.php, src/Execution/Arguments/NestedBelongsTo.php, src/Execution/Arguments/NestedManyToMany.php, src/Execution/Arguments/NestedMorphTo.php, src/Execution/Arguments/NestedOneToMany.php, src/Execution/Arguments/NestedOneToOne.php, tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php, tests/Integration/Execution/MutationExecutor/BelongsToTest.php, tests/Integration/Execution/MutationExecutor/HasManyTest.php, tests/Integration/Execution/MutationExecutor/HasOneTest.php, tests/Integration/Execution/MutationExecutor/MorphManyTest.php, tests/Integration/Execution/MutationExecutor/MorphOneTest.php, tests/Integration/Execution/MutationExecutor/MorphToManyTest.php, tests/Integration/Execution/MutationExecutor/MorphToTest.php, tests/Unit/Execution/Arguments/ArgumentSetTest.php
(cherry picked from commit 03a6d6bf8bf52217a05d9308a899c437275cadb6)
~~- [ ] Added Docs for all relevant versions~~
**Changes**
When passing `null` into a nested mutation operation, such as `create` or `sync`, Lighthouse throws an error.
Since `null` is an acceptable value, it should be handled gracefully and simply do nothing.
None.
=> Fix handling of nested mutation operations that receive `null`

CHANGELOG.md, src/Schema/Source/SchemaSourceProvider.php
**Changes**
This function is no longer used.
No, removing it won't be either.
=> Deprecate `\Nuwave\Lighthouse\Schema\Source\SchemaSourceProvider#setRootPath()`

CHANGELOG.md, src/Execution/Arguments/ArgumentSet.php, tests/Integration/Execution/ArgBuilderDirectiveTest.php, tests/Integration/Schema/Directives/SearchDirectiveTest.php
~~- [ ] Added Docs for all relevant versions~~
**Changes**
Apply query filters using an `ArgBuilderDirective` such as `@eq` when the argument
is nested deeply within the input
No
=> Nested arg builder directives

src/Pagination/PaginationArgs.php, tests/Integration/Schema/Directives/HasManyDirectiveTest.php, tests/Integration/Schema/Directives/MorphManyDirectiveTest.php, tests/Integration/Schema/Directives/PaginateDirectiveDBTest.php, tests/Unit/Schema/Directives/PaginateDirectiveTest.php
Refactor tests around error messages in `@paginate` and improve information content.
=> Properly test pagination error messages

CHANGELOG.md, docs/master/digging-deeper/schema-organisation.md, src/Schema/AST/ASTBuilder.php, src/Schema/AST/ASTHelper.php, tests/Unit/Schema/AST/ASTBuilderTest.php
=> Add support to extend `input`, `interface` and `enum` types

CHANGELOG.md, UPGRADE.md, docs/master/api-reference/directives.md, docs/master/custom-directives/argument-directives.md, src/Schema/Directives/BcryptDirective.php, src/Schema/Directives/HashDirective.php, tests/Integration/ValidationTest.php, tests/Unit/Schema/Directives/BcryptDirectiveTest.php, tests/Unit/Schema/Directives/HashDirectiveTest.php, tests/Unit/Schema/TypeRegistryTest.php
**Changes**
Adds a directive for Laravel's `Hash::make` facade so Lighthouse uses the defined driver of laravel for password hashing, instead of bcrypt via `@bcrypt` directive.
=> Add `@hash` directive and deprecate `@bcrypt`

CHANGELOG.md, docs/4.9/api-reference/directives.md, src/Schema/Directives/CanDirective.php, tests/Integration/Schema/Directives/CanDirectiveDBTest.php, tests/Unit/Schema/Directives/CanDirectiveTest.php
Resolves #1162
**Changes**
The `find` method of the can directive now uses [Arr::get](https://laravel.com/docs/6.x/helpers#method-array-get), to search the model. This allows to pass a string in a dot notation like `data.foo.bar`.
Previously it would throw an `Undefined Index Error` if the string did not map to a value. Now it will throw a `DefinitionException`.
=> Access nested inputs with dot notation in `find` option of `@can` #1216

CHANGELOG.md, src/Schema/Directives/CanDirective.php, tests/Integration/Schema/Directives/CanDirectiveDBTest.php
**Changes**
Catch `ModelNotFoundException` in `CanDirective` and instead throw `GraphQL\Error\Error`.
Also improved a few tests with GraphQL errors.
Using `@can` no longer throws `ModelNotFoundException` when model is not found. Instead the object returns as null, and a GraphQL error is sent. Status code is also changed to 200.
=> Throw GraphQL error when ModelNotFoundException is thrown in CanDirective

CHANGELOG.md, docs/master/api-reference/commands.md, src/Console/DirectiveCommand.php, src/Console/stubs/directive.stub
Note: I could not find any tests for the other generator command and don't really know what to test or how, so if that's required / wanted I'd definitely like some help on that.
**Changes**
Adds a `lighthouse:directive` command which creates an empty directive class in the appropriate namespace according to the `lighthouse.php` config file.
None.
**Final remarks**
I initially wanted to let the command also implement / include the various directive interfaces, but could not find a way to make that developer-friendly without creating a lot of options for the command. Thus I stuck with an empty class.
=> Add artisan command `lighthouse:directive` to add directive class #1240

CHANGELOG.md, src/Console/LighthouseGeneratorCommand.php, tests/Unit/Console/LighthouseGeneratorCommandTest.php
Resolves #1236 
**Changes**
Without a default namespace, code generation does not work. Fail explicitely when no namespace is set and default to the first one when no shared base can be established.
Previously broken behaviour now fails explicitely.
=> Avoid infinite loop with empty namespace in generator commands

CHANGELOG.md, docs/master/testing/extensions.md, src/LighthouseServiceProvider.php, tests/TestCase.php
Resolves https://github.com/nuwave/lighthouse/issues/1241
**Changes**
Now it just works™.
No.
=> Autoregister `TestingServiceProvider` for `@mock` in unit tests

CHANGELOG.md, docs/master/api-reference/commands.md, phpstan.neon, src/Console/PrintSchemaCommand.php, tests/TestCase.php, tests/Unit/Console/PrintSchemaCommandTest.php
**Changes**
Add flag `--json` to `print-schema` to output JSON instead of GraphQL SDL
No
=> Add flag `--json` to `print-schema` to output JSON instead of GraphQL SDL

CHANGELOG.md, src/Subscriptions/StorageManager.php, src/lighthouse.php
**Changes**
Adds an optional TTL to the subscription storage manager that allows auto-cleanup of subscriptions.
If for some reason a webhook is missed it is nice to have a way to cleanup stale subscription to prevent broadcasting unneeded. Currently topics and subscribers are stored forever (and topics are never cleanup up, but that's for another day), this allows setting a TTL that will let the cache driver know when an item can be removed from storage.
None.
=> Add TTL option for subscriptions storage

.github/workflows/continuous-integration.yml, tests/DBTestCase.php
**Changes**
Read test database connection data from env variables. This makes it easier to run tests locally without docker.
None.
=> Allow setting test database connection data from env vars

src/Schema/Directives/CacheDirective.php, src/Subscriptions/StorageManager.php
As documented in `CacheInterface`:
> NOTE: It is recommended that has() is only to be used for cache warming type purposes
and not to be used within your live applications operations for get/set, as this method
is subject to a race condition where your has() will return true and immediately after,
another script can remove it making the state of your app out of date.
=> Avoid race condition that may occur when using Cache::has()

CHANGELOG.md, src/Execution/Arguments/NestedBelongsTo.php, src/Execution/Arguments/NestedMorphTo.php, src/Execution/Arguments/SaveModel.php, tests/Integration/Execution/MutationExecutor/BelongsToTest.php, tests/Integration/Schema/Directives/CreateDirectiveTest.php
Resolves #1213.
**Changes**
This resolves a bug when inserting a model that relates to multiple belongs to relations that also are being created (using create or upsert wihtout id).
When SaveModel detects a BelongsTo relation, he associates with the relation, and also persist the relation. Since belongsTo means the relation is related with a model that contains the foreign key,
the code will try to persist. What happens is that the model have multiple belongsTo relations, all required and without default value. When this happens, and the code tries to save the model, it's still missing the remaining belongsTo relations id, generating a query error. 
This PR adds a check so when the parent model, related by a BelongsTo relation, doesn't exist, it will not call the save method in that …
=> Fix nested mutations with multiple belongsTo relations at the same level

CHANGELOG.md, src/Execution/Arguments/SaveModel.php, tests/Integration/Execution/MutationExecutor/BelongsToTest.php, tests/Integration/Execution/MutationExecutor/HasManyTest.php
- [ x ] Added or updated tests
Related with #1285 
**Changes**
This solves a problem that I detected related with multiple belongsTo at the same level.
The method used to solve this problem, was the exists method of the class Model. This method makes a query with the current attributes of the model instance and check if such exists. This could lead to a true result even if such instance don't exist on the database. 
To solve this, the use of the exists property of the model should be used instead of the method. This property tells if the instance is associated to a record of the database. 
I added tests to test this specific case.
This breaks the test *testUpsertAcrossTwoNestedBelongsToRelationsAndOverrideExistingModel*. 
I believe this test will create a duplication …
=> Multiple belongs to in the same level with existing records

CHANGELOG.md, src/Execution/Arguments/ArgumentSetFactory.php, src/Execution/Arguments/ListType.php, tests/Unit/Execution/Arguments/ArgumentSetFactoryTest.php
~~- [ ] Added Docs for all relevant versions~~
Resolves https://github.com/nuwave/lighthouse/issues/1264
**Changes**
The way arguments were parsed into an `ArgumentSet` wrongly assumed that lists are flat.
None
=> Fix converting lists of lists into ArgumentSet

CHANGELOG.md, src/WhereConditions/WhereConditionsBaseDirective.php, tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
~~- [ ] Added Docs for all relevant versions~~
Resolves https://github.com/nuwave/lighthouse/issues/1262
**Changes**
Pass the correct boolean operator to `whereNested` call.
No
=> Fix nesting OR within AND condition when using `@whereConditions`

docs/4.12/getting-started/migrating-to-lighthouse.md
without the graphql init 
✖ ".graphqlconfig" file is not available in the provided config directory: /datos/webs/sid/sidapi/sidapi
Please check the config directory.
**Changes**
=> Add graphql init to docs about graphql-cli

CHANGELOG.md, docs/master/digging-deeper/schema-organisation.md, src/Defer/DeferrableDirective.php, src/Schema/AST/ASTBuilder.php, src/Schema/Directives/CacheDirective.php, src/Schema/RootType.php, src/Schema/SchemaBuilder.php, src/Schema/Values/FieldValue.php, tests/Integration/IntrospectionTest.php, tests/Unit/Execution/Arguments/ArgumentSetFactoryTest.php, tests/Unit/Schema/AST/ASTBuilderTest.php, tests/Unit/Schema/AST/DocumentASTTest.php, tests/Unit/Schema/Directives/GlobalIdDirectiveTest.php, tests/Unit/Schema/Directives/MiddlewareDirectiveTest.php, tests/Unit/Schema/ResolverProviderTest.php, tests/Unit/Schema/SchemaBuilderTest.php
**Changes**
Less manual work, one less gotcha!
No
=> Add empty root types automatically when extending them

CHANGELOG.md, docs/master/eloquent/getting-started.md, src/Execution/Arguments/SaveModel.php, tests/Integration/Execution/MutationExecutor/MorphToTest.php, tests/Integration/Schema/Directives/CanDirectiveDBTest.php, tests/Integration/SchemaCachingTest.php, tests/Integration/SoftDeletes/ForceDeleteDirectiveTest.php, tests/Integration/SoftDeletes/RestoreDirectiveTest.php, tests/Unit/Schema/Directives/AuthDirectiveTest.php, tests/Utils/Models/Category.php, tests/Utils/Models/Comment.php, tests/Utils/Models/Company.php, tests/Utils/Models/Contractor.php, tests/Utils/Models/Employee.php, tests/Utils/Models/Image.php, tests/Utils/Models/Post.php, tests/Utils/Models/Role.php, tests/Utils/Models/RoleUserPivot.php, tests/Utils/Models/Tag.php, tests/Utils/Models/Task.php, tests/Utils/Models/Team.php, tests/Utils/Models/User.php, tests/Utils/Models/WithEnum.php
**Changes**
The schema already prevents clients from passing attributes they are not allowed to set.
This avoids forcing the user to mark all their attributes as fillable, allowing
mass-assignment protection to be used for other cases, where it makes sense.
No
=> Use `forceFill()` when mutating models

docs/master/subscriptions/client-implementations.md
I don't think this requires any of the above unless we want to mention it in the changelog, although it is not really a change... more a doc update :)
**Changes**
I noticed the PusherLink for Apollo example does not unsubscribe correctly, this PR aims to resolve that and have a "proper" PusherLink that unsubscribes when Apollo closes the subscription.
None. User paste this code in their project.
=> Update PusherLink example to handle unsubscribes

docs/4.12/performance/server-configuration.md, docs/master/performance/server-configuration.md
**Changes**
Changed a link in `server-configuration.md` to link to the English PHP docs instead of German.
=> update(docs) Link to English PHP manual

CHANGELOG.md, UPGRADE.md, src/Console/ValidateSchemaCommand.php, src/Schema/TypeRegistry.php, tests/Unit/Schema/TypeRegistryTest.php
**Changes**
Adds granular control to prevent accidental overwrites.
Not yet, but the default behaviour will change in v5.
=> Prevent silently overwriting types in `TypeRegistry`

CHANGELOG.md, docs/4.13/api-reference/directives.md, docs/master/api-reference/directives.md, src/Execution/Arguments/UpdateModel.php, tests/Integration/Schema/Directives/UpdateDirectiveTest.php
Resolves https://github.com/nuwave/lighthouse/issues/1372
**Changes**
Compatibility fix for when users relied on the fact that a wrongly named `id` argument is not force filled into models with different primary keys.
I hope not.
=> Pull primary key from arguments in `@update` before force filling them into the Model

CHANGELOG.md, src/Schema/Factories/DirectiveFactory.php, tests/Unit/Schema/Factories/DirectiveFactoryTest.php
- ~[] Documented user facing changes~
Resolves https://github.com/nuwave/lighthouse/issues/1382
**Changes**
Fix the error message when using multiple exclusive directives on a single node
No
=> Fix the error message when using multiple exclusive directives on a single node

CHANGELOG.md, src/Testing/MakesGraphQLRequestsLumen.php
This was forgotten in https://github.com/nuwave/lighthouse/pull/1342
=> Allow passing additional headers to `multipartGraphQL` Lumen test helper too

CHANGELOG.md, UPGRADE.md, src/Execution/Arguments/SaveModel.php, src/lighthouse.php, tests/Integration/Schema/Directives/CreateDirectiveTest.php, tests/TestCase.php
- https://github.com/nuwave/lighthouse/issues/1403
- https://github.com/nuwave/lighthouse/issues/1384
**Changes**
This adds a new config option to allow for a gradual opt-in to circumvent mass assignment protection.
This actually fixes a breaking change, but some users that already relied on the new behaviour must change their configuration.
=> Make mass assignment behavior configurable through `force_fill` option in `lighthouse.php`

docs/master/getting-started/installation.md
When I start a new project and publish the IDE Helpers I always get this error message:
```bash
This command requires haydenpierce/class-finder. Install it by running:
composer require --dev haydenpierce/class-finder
```
It's obvious what needs to be done but some users might still be confused. It would be nice to give them a little heads up ;)
=> Additional information to run the IDE helper

docs/3.0/extensions/deferred.md, docs/3.1/extensions/deferred.md, docs/3.2/extensions/deferred.md, docs/3.3/extensions/deferred.md, docs/3.4/extensions/deferred.md, docs/3.5/extensions/deferred.md, docs/3.6/extensions/deferred.md, docs/3.7/performance/deferred.md, docs/4.0/performance/deferred.md, docs/4.1/performance/deferred.md, docs/4.10/performance/deferred.md, docs/4.11/performance/deferred.md, docs/4.12/performance/deferred.md, docs/4.13/performance/deferred.md, docs/4.14/performance/deferred.md, docs/4.2/performance/deferred.md, docs/4.3/performance/deferred.md, docs/4.4/performance/deferred.md, docs/4.5/performance/deferred.md, docs/4.6/performance/deferred.md, docs/4.7/performance/deferred.md, docs/4.8/performance/deferred.md, docs/4.9/performance/deferred.md, docs/master/performance/deferred.md
**Description** 
Updated the documentation of `defer` extension to link correctly in the apollo documentation page to defer queries
**Issue link**
"Resolves #1441"
**The change was made in: ** 
-`3.1/extensions/deferred.md`
**Change made manually the vue press site. The vue press command I didn't run because it wasn't specified. If any changes are needed let me know.**
Thank you
=> Defer apollo link update

docs/master/security/authentication.md
**Changes**
It's not obvious how to use [Laravel Sanctum](https://laravel.com/docs/7.x/sanctum) as a guard. This PR adds docs to clarify usage. Additionally, this PR covers login / logout mutations with an example, also in conjunction with Laravel Sanctum.
As discussed in #1406.
none
=> docs: clarify usage with laravel sanctum, login / logout mutations

src/Schema/Directives/GlobalIdDirective.php, tests/Integration/Validation/ValidatorDirectiveTest.php, tests/Utils/Validators/WithGlobalIdValidator.php
- ~[ ] Documented user facing changes~
- ~[ ] Updated CHANGELOG.md~
Resolves https://github.com/nuwave/lighthouse/issues/1495
**Changes**
Make sure that `@globalId` runs before validation.
No
=> Decode @globalId before validation

src/WhereConditions/WhereConditionsBaseDirective.php, src/WhereConditions/WhereHasConditionsDirective.php, tests/Integration/WhereConditions/WhereHasConditionsDirectiveTest.php
Relates to: #1470
Test whereHas on belongsToMany relationship results in QueryException.
```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous (SQL: select * from `users` where (exists (select * from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id` where `users`.`id` = `role_user`.`user_id` and `id` = 1)))
```
=> Prefix complex conditions with table name to avoid ambiguous SQL

UPGRADE.md
**Changes**
fixed typo in `@middlware` to `@middleware`
=> Fix typo in upgrade guide from @middlware to @middleware

docs/4.16/security/authorization.md
Otherwise PhpStorm complains `Argument value is not a valid value of scalar "Boolean".`
=> Fix typo in @can docs

docs/4.12/api-reference/commands.md, docs/4.13/api-reference/commands.md, docs/4.14/api-reference/commands.md, docs/4.15/api-reference/commands.md, docs/4.16/api-reference/commands.md, docs/master/api-reference/commands.md
*Disclaimer:* This is my first PR here.
[ComposerScripts::postUpdate](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/ComposerScripts.php#L28) is doing exact same thing [ComposerScripts::postAutoloadDump](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/ComposerScripts.php#L41) doing after running
`$ composer update`. By this reason `ComposerScripts::postUpdate` is no longer being used in default `composer.json` in `Laravel v5.5` (sorry can't find exact commit). This is what I'd call "documentation legacy".
**Changes**
Docs improvement.
=> Remove excessive composer script from docs

docs/4.16/eloquent/nested-mutations.md
Laravel's function is syncWithoutDetaching but it is written syncWithoutDetach in current documentations for nested mutations.
Changed syncWithoutDetach function mentioned in docs to syncWithoutDetaching.
=> Fix docs: Laravel's function is `syncWithoutDetaching`

src/Schema/ResolverProvider.php
Larastan was complaining about that. It's not necessary since, if `$resolverClass` is not null, it goes to a return statement.
**Changes**
None.
None.
=> Remove unnecessary check

CHANGELOG.md, src/lighthouse.php
Hello Lighthouse team! This PR is not related to any issues.
**Changes**
Hardcoded `debug` option in `lighthouse.php` config has been replaced to `env('LIGHTHOUSE_DEBUG')` with default value: `\GraphQL\Error\DebugFlag::INCLUDE_DEBUG_MESSAGE | \GraphQL\Error\DebugFlag::INCLUDE_TRACE`
This will allow changing the logging mode through environment variables without changing the parameters of the configuration file.
There is no breaking changes, just a small tune for usability in k8s.
=> Set `lighthouse.debug` config through env `LIGHTHOUSE_DEBUG'

docker-compose.yml
I improve the default options a bit so that from IDE like PHPStorm you can work with XDebug by default. You just have to configure the server in the IDE.
=> Improve Xdebug in Docker

src/Execution/Arguments/ArgPartitioner.php, tests/Integration/Execution/MutationExecutor/BelongsToTest.php, tests/Unit/Execution/Arguments/ArgPartitionerTest.php
- ~[ ] Documented user facing changes~
**Changes**
Gracefully handle when `null` is passed as the argument of a nested mutation relation.
No.
=> Ignore nested relation mutation when null is given

CHANGELOG.md, docs/master/api-reference/directives.md, docs/master/custom-directives/field-directives.md, src/Execution/Arguments/ArgumentSet.php, src/Schema/Directives/AuthDirective.php, src/Schema/Directives/WhereAuthDirective.php, src/Support/Contracts/FieldBuilderDirective.php, src/Support/Http/Middleware/AttemptAuthentication.php, tests/Integration/Execution/FieldBuilderDirectiveTest.php, tests/Unit/Schema/Directives/AuthDirectiveTest.php
Resolves #1632 
This PR is not completely done, I think I would add more test cases to it first and possibly also allow changing the guard on the `whereAuth`.  
The purpose of this PR was mostly to get support for manipulating the builder on fields, not the new directive. However I feel that this directive shows the power of the new interface.
Was hoping to get some feedback about the idea here before I finished the pr completely.
**Changes**
- Adds a new interface for manipulating the builder on fields
- Adds a new directive for filtering a relationship on the currently authenticated user.
=> Add `FieldBuilderDirective` interface and `@whereAuth` directive

docs/master/getting-started/configuration.md
Minor documentation update to match the default config value that you would see when opening the CORS config file.
=> Add Sanctum cookie endpoint to default CORS paths

CHANGELOG.md, docs/master/api-reference/directives.md, src/Schema/Directives/TrimDirective.php, src/lighthouse.php, tests/Integration/Schema/Directives/TrimDirectiveTest.php
**Changes**
The `@trim` directive can now also be used upon fields.
No.
=> Use the `@trim` directive on fields to sanitize all input strings

.github/workflows/continuous-integration.yml, CHANGELOG.md, docs/master/api-reference/directives.md, docs/master/digging-deeper/relay.md, src/Console/IdeHelperCommand.php, src/GlobalId/GlobalIdDirective.php, src/Pagination/PaginateDirective.php, src/Pagination/PaginationType.php, src/Schema/AST/ASTHelper.php, src/Schema/DirectiveLocator.php, src/Schema/Directives/BelongsToManyDirective.php, src/Schema/Directives/BroadcastDirective.php, src/Schema/Directives/HasManyDirective.php, src/Schema/Directives/MorphManyDirective.php, src/Schema/Directives/ScopeDirective.php, src/Support/Contracts/Directive.php, tests/Integration/Events/FieldDirective.php, tests/Integration/Pagination/PaginateDirectiveDBTest.php, tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php, tests/Integration/Schema/Directives/CacheDirectiveTest.php, tests/Integration/Schema/Directives/HasManyDirectiveTest.php, tests/Integration/Schema/Directives/MorphManyDirectiveTest.php, tests/Integration/Schema/Directives/SearchDirectiveTest.php, tests/Integration/Schema/Types/UnionTest.php, tests/Unit/Pagination/PaginateDirectiveTest.php, tests/Unit/Schema/AST/ASTHelperTest.php, tests/Unit/Schema/Factories/DirectiveFactoryTest.php
https://github.com/nuwave/lighthouse/issues/1644#issuecomment-750307571
**Changes**
It is now possible to include auxiliary types, such as `enum` definitions, to directive definitions return from `Directive::definition()`.
No
=> Allow auxiliary types in directive definitions

docs/tutorial/README.md
**Changes**
This PR updates the tutorial code samples to use the `App\Models` namespace for sample models, instead of `App`. I'm no Laravel expert, but I believe that `App` was used in a previous version of Laravel, but now it's deprecated.
I've tested that `App` does not work whereas `App\Models` does. The `make:model` generates the model file with `App\Models`.
Notice that the documentation says:
> Replace the newly generated `app/Post.php` and the `create_posts_table.php` with this:
An expert Laravel user being introduced to Lighthouse should be able to identify that the tutorial is simply outdated, but to a developer being introduced to Laravel and Lighthouse simultaneously this can cause some confusion.
Thanks for your time!
None
=> Update code samples in the tutorial to the latest Laravel version

UPGRADE.md
https://github.com/nuwave/lighthouse/issues/1247
=> doc: mention `mll-lab/graphql-php-scalars` update in the upgrade guide

CHANGELOG.md, src/GlobalId/NodeRegistry.php, tests/Integration/Schema/NodeInterfaceTest.php
**The problem**
1) Query node() for some object but don't mention its type in the query.
2) This type won't be loaded as it isn't needed to resolve the query.
3) `TypeMiddleware` won't be executed.
4) It won't register itself in the `NodeRegistry`.
5) The query will fail with the `[Class] is not a registered node and cannot be resolved.` error.
**Changes**
This PR forces the type to load during node resolving, so that it can register itself.
=> Force load type when GlobalId\Node is used

CHANGELOG.md, UPGRADE.md, docs/master/api-reference/directives.md, src/Schema/Directives/DeleteDirective.php, src/Schema/Directives/MutationExecutorDirective.php, src/Schema/Directives/UpdateDirective.php, src/SoftDeletes/ForceDeleteDirective.php, src/SoftDeletes/RestoreDirective.php
**Changes**
- Deprecate the `globalId` argument on the `@delete`, `@forceDelete` and `@restore` directives
- Remove non-functional `globalId` argument definition from `@update`
Not breaking stuff now, but v6 will require changes:
The `@delete`, `@forceDelete` and `@restore` directives no longer offer the
`globalId` argument. Use `@globalId` on the argument instead.
```diff
type Mutation {
-   deleteUser(id: ID!): User! @delete(globalId: true)
+   deleteUser(id: ID! @globalId): User! @delete
}
```
=> Deprecate the `globalId` argument on the `@delete`, `@forceDelete` and `@restore` directives

CHANGELOG.md, src/Exceptions/AuthenticationException.php, src/Schema/Directives/GuardDirective.php, src/Schema/Factories/FieldFactory.php, tests/Integration/FieldMiddlewareTest.php, tests/Unit/Schema/Directives/GuardDirectiveTest.php
**Changes**
It is expected that field middleware run in lexical order, as they are defined in the schema. This PR reverses their previous execution order to match that assumption.
In most cases, this makes no difference. If this comes up, the implementation is likely bugged right now and will be fixed by this.
@ipalaus
=> Resolve field middleware in lexical order

CHANGELOG.md, src/Subscriptions/Subscriber.php, src/Subscriptions/SubscriptionBroadcaster.php
Resolves #1682 
**Changes**
The method expects variables, however we previously used arguments. This caused variables to change names before query execution. This is now fixed.
None
=> Fix subscriptions renaming variables

CHANGELOG.md, src/Subscriptions/Storage/RedisStorageManager.php, tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php
Resolves #1684 
**Changes**
When creating a subscription, following exception was thrown:
`Redis::set() expects at most 3 parameters, 4 given`
Phpredis seems to [support simply appending the TTL in seconds](https://github.com/phpredis/phpredis#examples-4). 
Reduced arguments from 4 to 3, by removing "EX" from the Redis-command.
=> Fix TTL for subscriptions

benchmarks/HugeResponseBench.php, src/Schema/Directives/BaseDirective.php, src/Testing/MockDirective.php, src/Testing/MockResolverService.php, src/Testing/MocksResolvers.php, src/Testing/TestingServiceProvider.php, tests/Unit/Schema/Directives/BaseDirectiveTest.php
**Changes**
`BaseDirective` loads all arguments and caches them after the first `directiveHasArgument`/`directiveArgValue` call
no
=> Cache directive arguments in BaseDirective

CHANGELOG.md, src/Schema/Directives/CanDirective.php, tests/Unit/Schema/Directives/CanDirectiveTest.php, tests/Utils/Policies/UserPolicy.php
**Changes**
In order to allow field authorization failures (especially in mutation queries) to return a detailed failure message, this PR changes the `@can` directive in a way, that it uses the `$gate->inspect` method (instead of `$gate->check`, which just returns a boolean) to receive an authorization response, which may hold a custom message returned by a policy method. Those Laravel responses are documented [here](https://laravel.com/docs/8.x/authorization#gate-responses).
This also changes the default error message from `You are not authorized to access {$this->nodeName()}` to the default error message of a Laravel auth access response `This action is unauthorized.` (found [here](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Auth/Access/AuthorizationException.php#L27)). …
=> Use gate response in authorization errors of `@can` directive

CHANGELOG.md, src/Support/Utils.php, src/WhereConditions/WhereConditionsBaseDirective.php, src/WhereConditions/WhereHasConditionsDirective.php, tests/Integration/WhereConditions/WhereHasConditionsDirectiveTest.php, tests/Utils/Models/Category.php, tests/Utils/Models/Post.php, tests/database/migrations/2018_02_28_000000_create_testbench_companies_table.php, tests/database/migrations/2018_02_28_000000_create_testbench_images_table.php, tests/database/migrations/2018_02_28_000001_create_testbench_teams_table.php, tests/database/migrations/2018_02_28_000002_create_testbench_users_table.php, tests/database/migrations/2018_02_28_000002_create_testbench_with_enums_table.php, tests/database/migrations/2018_02_28_000003_create_testbench_tasks_table.php, tests/database/migrations/2018_02_28_000004_create_testbench_posts_table.php, tests/database/migrations/2018_02_28_000005_create_testbench_comments_table.php, tests/database/migrations/2018_09_30_000006_create_testbench_tags_table.php, tests/database/migrations/2018_09_30_000007_create_testbench_taggables_table.php, tests/database/migrations/2018_10_07_000008_create_testbench_acls_table.php, tests/database/migrations/2018_10_07_000009_create_testbench_roles_table.php, tests/database/migrations/2018_10_07_000010_create_testbench_role_user_table.php, tests/database/migrations/2018_11_25_000004_create_testbench_colors_table.php, tests/database/migrations/2018_11_25_000005_create_testbench_products_table.php, tests/database/migrations/2018_12_08_000001_create_testbench_categories_table.php, tests/database/migrations/2019_11_04_000001_create_testbench_contractors_table.php, tests/database/migrations/2019_11_04_000001_create_testbench_employees_table.php, tests/database/migrations/2021_01_30_000000_create_testbench_category_post_table.php
Added failing test for issue [#1677](https://github.com/nuwave/lighthouse/issues/1677)
**Describe the bug**
I'm trying to query for products that are in a category or its subcategories. Categories can have one `parent`, and products can `belongToMany` `categories`. When using an array of `OR` conditions to apply to the relationship `categories` for for the `product` type, the query generated uses `AND` instead of `OR`. See the graphql query here and the SQL output further below.
```graphql
query ($where: WhereConditions) {		
products(where: $where) {
data {
id
title
}
}
} 
variables: {
"where": {
"HAS": {
"relation": "categories",
"condition": {
"OR": [   // Currently both of these conditions must be met, which is incorrect and never returns products
{
"column": "categories.id",
"value": …
```
=> Test case for nested OR conditions for HAS relation

CHANGELOG.md, docs/master/api-reference/directives.md, src/Exceptions/RateLimitException.php, src/Schema/Directives/ThrottleDirective.php, tests/Integration/Schema/Directives/ThrottleDirectiveTest.php, tests/Unit/Schema/Directives/ThrottleDirectiveTest.php
**Changes**
Adds `@throttle` directive. It is adapted from Laravel and works on per-field basis.
=> Add `@throttle` directive to set field rate limit using Laravel rate limiting services

docs/tutorial/README.md
The "author_id" field is a foreign key with a custom name other than the default. It needs to be explicitly stated.
**Changes**
=> Fix docs: explicit foreign key for `author_id`

CHANGELOG.md, docs/master/api-reference/directives.md, docs/master/custom-directives/field-directives.md, docs/master/security/authentication.md, docs/master/the-basics/directives.md, docs/master/the-basics/fields.md, php.dockerfile, src/Schema/AST/ASTHelper.php, tests/Unit/Schema/Directives/GuardDirectiveTest.php
Resolves https://github.com/nuwave/lighthouse/issues/1709
**Changes**
When directives are transferred from the application on a `type` to the contained fields, they are now prepended to the existing directives instead of appending them.
```graphql
type Query @guard {
user: User!
@can(ability: "adminOnly")
}
```
Before this PR:
```graphql
type Query {
user: User!
@can(ability: "adminOnly")
@guard
}
```
After this PR:
```graphql
type Query {
user: User!
@guard
@can(ability: "adminOnly")
}
```
Rather unbreaking #1666.
=> Prepend directives when transferring them from types to fields

CHANGELOG.md, phpunit.xml.dist, src/Subscriptions/Authorizer.php, src/Subscriptions/BroadcastManager.php, src/Subscriptions/Broadcasters/PusherBroadcaster.php, src/Subscriptions/Contracts/Broadcaster.php, src/Subscriptions/Events/EchoSubscriptionEvent.php, tests/DBTestCase.php, tests/Integration/Subscriptions/EchoBroadcaster/AuthorizeRequestsTest.php, tests/Unit/Subscriptions/Broadcasters/EchoBroadcasterTest.php, tests/Unit/Subscriptions/Broadcasters/PusherBroadcasterTest.php
#1724 
**Changes**
- For `echo` driver-based subscriptions, the event name will be 'lighthouse-subscription'. 
- Echo driver will always broadcast through the `private` channel. 
- If want to broadcast a sync event, it will not be queued anymore. 
- Pusher driver can log entries if defined in the `broadcasting` config file.
- The event name can be a breaking change `lighthouse-subscription`
=> Fix broadcasting in the echo subscription driver

CHANGELOG.md, composer.json, src/Subscriptions/BroadcastManager.php, src/Subscriptions/Broadcasters/PusherBroadcaster.php
**Changes**
Pusher 5 now throws an exception when triggering the broadcast fails, we catch that exception and report it to the framework so the user can debug.
See changes: https://github.com/pusher/pusher-http-php/blob/master/CHANGELOG.md#500-2021-02-19
As far is I can tell the catch with the new exception has no actual effect when the exception class doesn't exist and it has no negative effects having it there for 5.x, code still works fine with 4.x (it just doesn't enter the "catch" ever).
None.
=> Support `pusher/pusher-php-server` version 5

src/Subscriptions/SubscriptionRegistry.php
**Changes**
Define a default for when `config('lighthouse.subscriptions.version')` returns `null`.
This will most likely happen for all users with existing `lighthouse.php` files since Laravel does not merge config files deep so although we have defined a default in our own `lighthouse.php` because the user has a `subscriptions` key in their own `lighthouse.php` you need to define `version` otherwise exception is being thrown.
You can consider this behaviour a breaking change so that's why a default must be provided so users don't have to change their config files to prevent an exception.
This fixed a "breaking change", but doesn't introduce a new one.
=> Fix subscription extension version default value

docs/master/eloquent/nested-mutations.md, src/Execution/Arguments/NestedOneToMany.php, tests/Integration/Execution/MutationExecutor/HasManyTest.php, tests/Integration/Execution/MutationExecutor/MorphManyTest.php
**Changes**
Add `connect` and `disconnect` to HasMany and MorphMany relations so now you can connect and disconnect objects as you like.
=> Add `connect` and `disconnect` operations in nested mutations for HasMany and MorphMany relations

CHANGELOG.md, src/Subscriptions/Storage/RedisStorageManager.php, tests/Integration/Subscriptions/Storage/RedisStorageManagerTest.php
Resolves #1757 
**Changes**
Fix the mget call when there are no subscribers
=> Fix mget call with empty subscribers

CHANGELOG.md, src/Console/ClearCacheCommand.php, src/Schema/AST/ASTBuilder.php
The current method only clears the cache for the default cache store of the application and did not read the (optional) custom cache store set in the Ligthouse config.
**Changes**
The current method only clears the cache for the default cache store of the application and did not read the (optional) custom cache store set in the Ligthouse config.
I've used this code as "inspiration":
https://github.com/nuwave/lighthouse/blob/9e37fb38e0430f8594146466b29c6032dbc72650/src/Schema/AST/ASTBuilder.php#L99-L106
None (well, actually clearing the cache now, but that is a good "breaking" change).
=> Use selected cache store on clear-cache command

docs/5.3/api-reference/directives.md, docs/5.3/digging-deeper/adding-types-programmatically.md, docs/5.3/the-basics/types.md, docs/master/api-reference/directives.md, docs/master/digging-deeper/adding-types-programmatically.md, docs/master/the-basics/types.md
Hi, I have discovered that few 'webonyx.github.io/graphql-php' links are broken, I have fixed them for the master branch and for 5.3
=> Fix webonyx.github.io/graphql-php documentation links

CHANGELOG.md, docs/master/subscriptions/getting-started.md, src/Subscriptions/SubscriptionRegistry.php, src/lighthouse.php, tests/Integration/Subscriptions/SubscriptionTest.php
Ref: https://github.com/nuwave/lighthouse/issues/1787
**Changes**
Adds config option 'subscriptions.exclude_empty' (default false). When true, and subscriptions are in use, an API response without a channel will exclude the 'lighthouse_subscriptions' extension response as a small performance optimization.
None - default setting 'false' functions the same as before.
=> Add config option `subscriptions.exclude_empty`

CHANGELOG.md, src/Subscriptions/Storage/RedisStorageManager.php, tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php
Resolves #1779 
**Changes**
Use [setex](https://redis.io/commands/setex) (SETEX is atomic) instead of set with multiple parameters which fails when using predis instead of phpredis (see #1779)
=> Fix subscription redis storage for predis users

CHANGELOG.md, composer.json, src/Schema/Factories/DirectiveFactory.php, tests/Unit/Schema/DirectiveLocatorTest.php, tests/Unit/Schema/Factories/DirectiveFactoryTest.php
Requires `webonyx/graphql-php:^14.6.2`, see https://github.com/webonyx/graphql-php/pull/848
=> Fix overly eager validation of repeatable directive usage

CHANGELOG.md, src/LighthouseServiceProvider.php, src/Pagination/PaginateDirective.php, src/Pagination/PaginationManipulator.php, src/Schema/Directives/CacheDirective.php, src/Schema/Directives/CacheKeyDirective.php, src/Schema/Directives/ModelDirective.php, tests/TestCase.php, tests/TestsSerialization.php, tests/Unit/Pagination/PaginateDirectiveTest.php, tests/Unit/Schema/DirectiveLocatorTest.php, tests/Unit/Schema/Directives/BaseDirectiveTest.php, tests/Unit/Schema/Execution/ContextFactoryTest.php, tests/Unit/Subscriptions/BroadcastManagerTest.php, tests/Unit/Subscriptions/SubscriptionTest.php
**Changes**
Fixes an issue reported by Chris Radigan in Slack.
When validating my schema I get this error:
```
Non-repeatable directive @model used more than once at the same location.
GraphQL request (1:1)
1: @model(class: "App\\Models\\User")
^
GraphQL request (1:1)
1: @model(class: "App\\Models\\User")
^
```
Seems to be caused by having multiple queries that use the same model resolver.
```graphql
type User{
id
email
...
}
type Query{
users: [User] @paginate
admins: [User] @paginate(scopes: ["admin"])
...
}
```
No.
=> Avoid setting multiple `@model` directives on generated paginator types

CHANGELOG.md, src/Schema/Directives/BuilderDirective.php, tests/Integration/Scout/SearchDirectiveTest.php
Resolves https://github.com/nuwave/lighthouse/issues/1846
**Changes**
Make the `BuilderDirective` implement the `ScoutBuilderDirective` interface to allow usage with `@search`.
No.
=> Allow `@builder` in combination with `@search`

src/Exceptions/ValidationException.php, tests/Unit/Exceptions/ValidationExceptionTest.php
**Changes**
Added a static method `withMessage` in [ValidationException](https://laravel.com/api/8.x/Illuminate/Validation/ValidationException.html#method_withMessages) like ValidationException of Laravel core. Sometimes we want to send a validation response with our custom text.
```
use Nuwave\Lighthouse\Exceptions\ValidationException
throw ValidationException::withMessage([
'email' => 'The email or password does not match.',
]);
```
Nothing
=> Add `ValidationException::withMessage()`

CHANGELOG.md, src/GlobalId/GlobalIdDirective.php, tests/Unit/GlobalId/GlobalIdDirectiveTest.php
Resolves https://github.com/nuwave/lighthouse/issues/1861
**Changes**
Using `@globalId` on a nullable argument does not cause a crash now.
When using `@globalId` on a field, `null` is now encoded as `null`.
The encoding for `null` has changed, but actually makes sense now.
=> Handle `null` when encoding or decoding with `@globalId`

CHANGELOG.md, src/Schema/Directives/LazyLoadDirective.php, tests/Integration/Schema/Directives/LazyLoadDirectiveTest.php
**Changes**
Allow `LengthAwarePaginator` as a parameter in `LazyLoadDirective` directive.
None.
=> Fix combining `@lazyLoad` with paginated relations

CHANGELOG.md, src/Schema/Directives/CacheDirective.php, tests/Integration/Schema/Directives/CacheDirectiveTest.php
**Changes**
When caching a boolean, string or integer value using `@cache` directive, falsy value like `false`, `0` or `""` aren't consider as valid cache. This PR resolves this issue.
No
=> Prevent resolver being called when a cached field contains a falsy value

CHANGELOG.md, src/Execution/BatchLoader/BatchLoaderRegistry.php, src/Execution/BatchLoader/RelationBatchLoader.php, src/Execution/ModelsLoader/SimpleModelsLoader.php, tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php, tests/Utils/Models/Task.php
=> Avoid conflicting relation batch loader overlaps when using dot notation in `@with`

docs/master/api-reference/directives.md
Documentation of directive @orderBy in version 5 of docs did not accurately reflect the functionality seen in v5.12.3
Direction is passed in as an enum, not a String
**Changes**
=> Directive @orderBy documentation

src/Subscriptions/Storage/RedisStorageManager.php
**Changes**
Fix incorrect config key for subscriptions redis storage connection.
=> Fix incorrect config key for subscriptions redis storage connection

CHANGELOG.md, UPGRADE.md, docs/5/api-reference/directives.md, docs/master/api-reference/directives.md, src/Pagination/ConnectionField.php, src/Pagination/PaginationManipulator.php, src/Pagination/PaginationServiceProvider.php, src/lighthouse.php, tests/Integration/Schema/Directives/HasManyDirectiveTest.php, tests/Integration/Schema/Directives/MorphManyDirectiveTest.php, tests/TestCase.php, tests/Unit/Federation/SchemaBuilderTest.php, tests/Unit/Pagination/PaginateDirectiveTest.php, tests/Unit/Schema/SchemaBuilderTest.php
Resolves https://github.com/nuwave/lighthouse/issues/1877
**Changes**
- Add config setting `non_null_pagination_results` to mark the generated result type of paginated lists as non-nullable
- Improve descriptions of generated pagination types
Generated types were changed, but only towards more non-nullability.
A config setting was introduced to preserve the current nullability of paginated result types, as validation errors would bubble further up the query when set non-nullable. Lighthouse v6 will always generate them as non-nullable.
=> Mark appropriate generated pagination types as non-nullable

src/Schema/AST/ASTHelper.php, src/Schema/Directives/ModelDirective.php, tests/Integration/Schema/Directives/UpsertDirectiveTest.php
When using interfaces (and a `@model` directive attached to it), the `ASTHelper::modelName` function should also handle instances of `InterfaceTypeDefinitionNode`.
**Changes**
Allows `ASTHelper::modelName` function to also handle instances of `InterfaceTypeDefinitionNode` and change `ModelDirective::modelClass`'s `$node` arg type hint to `GraphQL\Language\AST\Node`.
None.
=> Fix model name determination when using interfaces

CHANGELOG.md, docs/master/digging-deeper/error-handling.md, docs/master/testing/phpunit.md, src/Testing/MakesGraphQLRequests.php, src/Testing/MakesGraphQLRequestsLumen.php, src/Testing/RethrowingErrorHandler.php, tests/Integration/ErrorHandlersTest.php, tests/Unit/Testing/MakesGraphQLRequestsTest.php
Resolves https://github.com/nuwave/lighthouse/issues/1884
=> Add method `rethrowGraphQLErrors()` to testing helper to leverage PHPUnit exception testing

CHANGELOG.md, src/Console/ClearCacheCommand.php, src/Console/PrintSchemaCommand.php, src/Console/ValidateSchemaCommand.php, src/LighthouseServiceProvider.php, tests/TestCase.php
**Changes**
Actually clears the cache in `lighthouse:validate-schema` and `lighthouse:print-schema` when using schema cache version 2.
None
=> Call lighthouse:clear-cache in other commands

CHANGELOG.md, src/Exceptions/ValidationException.php, src/Execution/ExtensionErrorHandler.php, src/Execution/ValidationErrorHandler.php, src/lighthouse.php, tests/Unit/Exceptions/ValidationExceptionTest.php, tests/Unit/Execution/ValidationErrorHandlerTest.php
**Changes**
Native Laravel validation exceptions are now handled gracefully as client safe exceptions, holding the structured validation messages in `extensions.validation`.
None.
=> Add `ValidationException::fromLaravel()` and `ValidationErrorHandler` to include validation messages in extensions

CHANGELOG.md, src/Validation/RulesGatherer.php, tests/Integration/Validation/ValidationTest.php
**Changes**
The Laravel date validation rules (after, after_or_equal, before,
before_or_equal) allow the user to specify a date or another field from
the request to compare.
This didn't work with Lighthouse because the full path to the field
wasn't added to the rule arguments.
In this commit the argument is checked, if it is a date then nothing
happens, otherwise it is assumed to be another field from the request
and so adds the full argument path.
This shouldn't break any existing projects as it uses the same check that Laravel uses when seeing if the argument is a date or a field reference, so it should behave in the same way.
=> Allow using date validation rules that reference other arguments

CHANGELOG.md, docs/5/api-reference/directives.md, docs/master/api-reference/directives.md, src/Validation/ValidateDirective.php
Constructor injection of `Illuminate\Contracts\Validation\Factory` seems to be problematic when using Octane.
=> Fix compatibility with Laravel Octane

CHANGELOG.md, docs/5/api-reference/commands.md, docs/5/api-reference/directives.md, docs/5/security/authorization.md, docs/master/api-reference/commands.md, docs/master/api-reference/directives.md, docs/master/security/authorization.md, src/Console/DirectiveCommand.php, src/Console/stubs/directive.stub
**Changes**
The required method `definition()` is now included and reasonably populated by default.
Use `choice()` for multi-select of interfaces.
=> Include definition when generating directives via `artisan lighthouse:directive`

CHANGELOG.md, src/Exceptions/AuthenticationException.php, src/Exceptions/AuthorizationException.php, src/Execution/AuthenticationErrorHandler.php, src/Execution/AuthorizationErrorHandler.php, src/lighthouse.php, tests/Unit/Execution/AuthenticationErrorHandlerTest.php, tests/Unit/Execution/AuthorizationErrorHandlerTest.php
**Changes**
Handle gracefully laravel `AuthenticationException` and `AuthorizationException` like it has been done for `ValidationException` in #1899 
None.
=> Handle Laravel `AuthenticationException` and `AuthorizationException`

CHANGELOG.md, src/Console/MutationCommand.php, src/Console/QueryCommand.php, src/Console/SubscriptionCommand.php, src/Federation/ASTManipulator.php, src/Federation/FederationPrinter.php, tests/Integration/Federation/FederationSchemaTest.php, tests/Unit/Federation/SchemaBuilderTest.php
**Changes**
When using federation it is possible to have a schema without the `Query` type and only types extensions.
With this change it is possible to omit the `Query` type
none.
=> Support schema without `Query` type when using federation

CHANGELOG.md, src/Schema/Directives/GuardDirective.php, src/Testing/TestResponseMixin.php, src/Testing/TestResponseUtils.php, tests/Integration/Execution/FieldBuilderDirectiveTest.php, tests/Integration/Validation/ValidationTest.php, tests/Unit/Schema/Directives/AuthDirectiveTest.php, tests/Unit/Schema/Directives/GuardDirectiveTest.php
=> Make `TestReponse::assertGraphQLValidationError()` work for fields with multiple messages

CHANGELOG.md, src/Console/PrintSchemaCommand.php, tests/Console/PrintFederationSchemaCommandTest.php
**Changes**
Added a `--federation` option to the `lighthouse:print-schema` command to print the federation subgraph sdl (the same that is returned from `_service { sdl }` query.
This can be useful to statically build the supergraph schema for apollo gateway or to push the subgraph schema to a managed service like apollo studio
Right now I implemented only the sdl output and not the json one (maybe the json output doesn't event make sense for this case)
none
=> Add --federation option to lighthouse:print-schema command

CHANGELOG.md, phpstan.neon
**Changes**
This PR remove the rule to ignore undefined Faker\\UniqueGenerator::.* since the related [PR](https://github.com/FakerPHP/Faker/pull/345) was merged and the version 1.16.0 with fix was released how described on [this](https://github.com/FakerPHP/Faker/issues/365) issue. 
Will throw an error on old version of faker
=> Fix TODO 'Improve type hints in UniqueGenerator'

CHANGELOG.md, UPGRADE.md, src/Execution/Arguments/ArgumentSet.php, src/lighthouse.php, tests/Integration/Schema/Types/LaravelEnumTypeDBTest.php, tests/TestCase.php, tests/Utils/LaravelEnums/AOrB.php, tests/Utils/Models/WithEnum.php
**Changes**
Previous to `v6`, Lighthouse would extract the internal `$value` from instances of
`BenSampo\Enum\Enum` before passing it to `ArgBuilderDirective::handleBuilder()`
if the setting `unbox_bensampo_enum_enum_instances` was `true`.
This is generally unnecessary, because Laravel automagically calls the Enum's `__toString()`
method when using it in a query. This might affect users who use an `ArgBuilderDirective`
that delegates to a method that relies on an internal value being passed.
```graphql
type Query {
withEnum(byType: AOrB @scope): WithEnum @find
}
```
```php
// WithEnum.php
public function scopeByType(Builder $builder, int $aOrB): Builder
{
return $builder->where('type', $aOrB);
}
```
In the future, Lighthouse will pass the actual Enum instance along. You can opt in to
the …
=> Deprecate `BenSampo\Enum\Enum` unboxing

CHANGELOG.md, src/Testing/MakesGraphQLRequests.php, src/Testing/MakesGraphQLRequestsLumen.php, tests/Unit/Testing/MakesGraphQLRequestsTest.php
Implement https://github.com/nuwave/lighthouse/pull/1968 properly
=> Allow specifying headers in `MakesGraphQLRequests` and `MakesGraphQLRequestsLumen` test helpers

CHANGELOG.md, src/Schema/AST/DocumentAST.php, src/Subscriptions/Subscriber.php, tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php, tests/Utils/Subscriptions/DummySubscriber.php
Resolves https://github.com/nuwave/lighthouse/issues/1985
**Changes**
Adds magic methods and deprecates usage of interface.
Not yet, but v6 will remove for pre-PHP 7.4 style serialization through `Serializable`.
=> Deprecate `Serializable` implementation in favor of magic methods

CHANGELOG.md, docs/5/performance/schema-caching.md, docs/master/performance/schema-caching.md, src/Schema/AST/ASTCache.php
**Changes**
We have this config:
```php
'cache' => [
/*
* Setting to true enables schema caching.
*/
'enable'  => env('LIGHTHOUSE_CACHE_ENABLE', !env('APP_DEBUG', false)),
/*
* Allowed values:
* - 1: uses the store, key and ttl config values to store the schema as a string in the given cache store.
* - 2: uses the path config value to store the schema in a PHP file allowing OPcache to pick it up.
*/
'version' => env('LIGHTHOUSE_CACHE_VERSION', 2),
/*
* File path to store the lighthouse schema.
* Only relevant if version is set to 2.
*/
'path'    => env('LIGHTHOUSE_CACHE_PATH', base_path('bootstrap/cache/lighthouse-schema.php')),
],
```
It's missing some keys for the v1 cache strategy which currently breaks even when using version 2.
Refactored it a bit to prevent that.
**Breaking …
=> Fix undefined array key with missing cache config

CHANGELOG.md, src/Schema/TypeRegistry.php, tests/Integration/Schema/Types/InterfaceTest.php
**Changes**
In `TypeRegistry->typeResolverFallback`, use `array_pop` instead of `[0]`, as `array_intersect` might return an array with a key that isn't 0.
This can happen with two renamed models that implement an interface, and a result with the second model is returned (which has key `1`)
None.
=> Fix undefined array key with interfaces and two renamed models

CHANGELOG.md, src/Tracing/Tracing.php, src/Tracing/TracingDirective.php, src/Tracing/TracingServiceProvider.php, tests/Integration/Tracing/TracingExtensionTest.php
Resolves https://github.com/nuwave/lighthouse/issues/2007
**Changes**
Use `StartExection` over `StartRequest` to mark the beginning of an operation in tracing. This has two advantages:
- accurate timing when using batched requests
- works in a non-http context
No, but the timing values will differ.
=> Use `StartExecution` event to determine per-operation Tracing timestamps

src/Schema/AST/ASTCache.php
**Changes**
This PR cast explicitly the cache version as an integer in `ASTCache`, resolving a "Path cannot be empty" error in `ASTCache::put` method when using `LIGHTHOUSE_CACHE_VERSION=1` in `.env` file.
Why this issue wasn't seen before ?
1. Most of user using cache version 1 just use the provided configuration file without any particular `env` override. In this situation, `config('lighthouse.cache.version') === 1`, because of the default value used in config file.
2. In the meantime, users using `LIGHTHOUSE_CACHE_VERSION=2` ends up with a `config('lighthouse.cache.version') === "2"`, which pass fine the switch/case statement in `ASTCache::__construct`, and also isn't an issue, for `if (1 === $this->version)` comparison, because so far 1 != "2".
So when is it an issue ?
This issue is …
=> Fix ASTCache with `LIGHTHOUSE_CACHE_VERSION=1` in env

CHANGELOG.md, src/Federation/Types/Any.php, src/Support/Http/Middleware/EnsureXHR.php, tests/Unit/Support/Http/Middleware/EnsureXHRTest.php
**Changes**
1. Laravel allows [spoofing request method](https://laravel.com/docs/8.x/routing#form-method-spoofing) via the `_method` parameter. I fixed the `EnsureXHR` middleware to handle it
2. Browsers may send additional fields in the `Content-type` header. For example, `multipart/form-data; boundary=-------12345` or `text/plain; encoding=utf-8`. These requests were wrongly considered as XHR. 
No.
=> Fixes in EnsureXHR middleware

CHANGELOG.md, docs/master/api-reference/directives.md, src/Pagination/PaginationServiceProvider.php, src/Pagination/SimplePaginatorField.php, tests/Unit/Pagination/PaginateDirectiveTest.php
**Changes**
As you can see in here, the `simplePaginate` method actually supports `hasMorePages` by just querying an additional line. So I added it (back) in :)
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Builder.php#L833-L836
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Pagination/Paginator.php#L70-L72
=> Add field `hasMorePages` for pagination type `SIMPLE`

src/Execution/Resolved.php, tests/Integration/Schema/Directives/LimitDirectiveTest.php
Resolves #1793
**Changes**
When using the `@limit` in combination with the `@cache`, a SyncPromise object will be saved to the cache.
It will throw an exception in next same query.
With this change it will work fine.
=> Properly handle any kind of deferred resolved value

docker-compose.yml
I had to add a specific platform to mysql to run Docker installation on Apple M1 chip.
=> Add platform to mysql for Apple M1 support

CHANGELOG.md, UPGRADE.md, docs/master/testing/phpunit.md, src/Exceptions/InvalidSchemaCacheContentsException.php, src/Schema/AST/ASTCache.php, src/Testing/ClearsSchemaCache.php, src/Testing/RefreshesSchemaCache.php, tests/Integration/SchemaCachingTest.php
**Changes**
- Add testing trait `RefreshesSchemaCache` https://github.com/nuwave/lighthouse/pull/2076
- Add proper error handling for invalid schema cache file contents https://github.com/nuwave/lighthouse/pull/2076
- Deprecate testing trait `ClearsSchemaCache` https://github.com/nuwave/lighthouse/pull/2076
None.
=> Add parallel-testing compatible way to refresh schema cache in tests

CHANGELOG.md, src/Validation/RulesGatherer.php, src/Validation/ValidateDirective.php, tests/Integration/Validation/ValidatorDirectiveTest.php, tests/Utils/Validators/RulesWithParametersValidator.php
I recently updated to Laravel 9.0 in my application, and these kind of inputs started failing.
`validatesAttributes@validateSize` does not receive correct `$parameters`. Its just receives an empty array.
=> Normalize rules input to ensure Laravel 9 support

CHANGELOG.md, docs/5/digging-deeper/adding-types-programmatically.md, docs/master/digging-deeper/adding-types-programmatically.md, src/Schema/TypeRegistry.php, tests/Integration/Schema/Types/InterfaceTest.php, tests/Integration/Schema/Types/UnionTest.php, tests/Unit/Schema/TypeRegistryTest.php
**Changes**
Adds `TypeRegistry::registerLazy()` and `TypeRegistry::overwriteLazy()` to allow for more performant registration of programmatic types.
None.
=> Allow lazy registration of types

CHANGELOG.md, UPGRADE.md, src/Pagination/PaginationManipulator.php, tests/Integration/Pagination/PaginateDirectiveDBTest.php, tests/Unit/Pagination/PaginateDirectiveTest.php
Reverts the breakage mentioned in https://github.com/nuwave/lighthouse/pull/2093/files/a5e76b202966e988b30760131a50a8fb2fe4989f#diff-76d791c7e3599495909ebc9bff7dc2d6cf89f30d8e33f9bf68d4eb91f935c9ca
=> Revert breaking schema change in generate pagination types

CHANGELOG.md, _ide_helper.php, src/Testing/TestResponseMixin.php, tests/Integration/ErrorTest.php
**Changes**
Adds a new method to the `TestResponseMixin`, it allows to make assertions on internal error messages.
None.
=> Add method `TestResponse::assertGraphQLDebugMessage()` to test internal errors

src/Execution/Arguments/NestedOneToMany.php, tests/Integration/Execution/MutationExecutor/HasManyTest.php, tests/Utils/Models/CustomPrimaryKey.php, tests/Utils/Models/User.php, tests/database/factories/CustomPrimaryKeyFactory.php, tests/database/migrations/2022_04_14_000000_create_testbench_custom_primary_keys_table.php
Resolves #1833 
**Changes**
Solution from #1833, `Changing self::getLocalKeyName($relation) to $relation->make()->getKeyName()`
=> Fix hasMany connect disconnect with non-default primary key

CHANGELOG.md, src/Execution/Arguments/ArgumentSet.php, src/Pagination/PaginateDirective.php, src/Schema/Directives/AllDirective.php, src/Scout/ScoutEnhancer.php, tests/Integration/Pagination/PaginateDirectiveDBTest.php, tests/Integration/Schema/Directives/AllDirectiveTest.php, tests/Unit/Schema/Source/SchemaStitcherTest.php
**Changes**
Recently an assert was added to `@all` & `@paginate` that was incomplete, it was missing the `Relation` type which should also be allowed.
Unrelated, this also fixes the use of `mkdir --parents` that doesn't work under macOS, changed to `mkdir -p` to work on both macOS and Linux OSs.
None.
=> Fix assert for builder argument on @all & @paginate directives

CHANGELOG.md, src/Schema/Directives/RelationDirective.php, tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php, tests/Utils/Models/NullConnection.php, tests/database/factories/NullConnectionFactory.php, tests/database/migrations/2022_04_21_000000_create_testbench_null_connections_table.php
**Changes**
In some cases `Model::getConnectionName()` may return `mysql` (= default connection name), but in other it will return `null` for default connection (not extactly sure when, one of the case `HasOneThrough` + Laravel v9.9.0). Current version will not use batchloading, in this case (because `null !== 'mysql'`). 
Maybe, `RelationDirective::__construct` wants new parameter.
=> `RelationDirective`/`batchload_relations` will consider `null` and default connection name the same connection

CHANGELOG.md, src/Execution/Arguments/Argument.php, src/Schema/Directives/ConvertEmptyStringsToNullDirective.php, tests/Integration/Schema/Directives/ConvertEmptyStringsToNullDirectiveTest.php
https://github.com/nuwave/lighthouse/issues/1459#issuecomment-1106598749
@LastDragon-ru
**Changes**
Omit non-nullable arguments in `@convertEmptyStringsToNull`.
Behavioural fix.
=> Omit non-nullable arguments in `@convertEmptyStringsToNull`

CHANGELOG.md, docs/5/api-reference/directives.md, docs/5/digging-deeper/deprecation.md, docs/master/api-reference/directives.md, docs/master/digging-deeper/deprecation.md, src/Deprecation/DeprecatedUsage.php, src/Deprecation/DetectDeprecatedUsage.php, tests/Unit/Deprecation/DeprecationTest.php
**Changes**
Replaces `true` with an instance of `DeprecatedUsage` in the array of deprecations given to handlers registered with `DetectDeprecatedUsage::handle()`.
Slightly, but this feature is still experimental.
=> Provide additional information about detected usages of deprecated elements

CHANGELOG.md, src/Schema/AST/ASTHelper.php, src/Schema/Values/TypeValue.php, tests/Integration/Schema/Directives/CacheDirectiveTest.php
Resolves #2152 
**Changes**
If `@rename` exist use the attribute value as the cacheKey.
no.
=> Consider `@rename` when picking the value of a key in `@cache`

src/Schema/Directives/MorphToManyDirective.php, tests/Integration/Schema/Directives/MorphToManyDirectiveTest.php
Resolves #2153
`MorphToManyDirective` now implements `FieldManipulator` instead of `FieldResolver`.
=> Allow pagination types for `@morphToMany`

CHANGELOG.md, src/Exceptions/RateLimitException.php, src/Schema/Directives/ThrottleDirective.php, tests/Integration/Schema/Directives/ThrottleDirectiveTest.php
Resolves #2145 
**Changes**
As discussed in #2145, this PR adds the query path to the `RateLimitException` message.
Only the already mentioned message of the exception changes. 😉
=> Include field that produced a `RateLimitException` in its message

CHANGELOG.md, src/Pagination/ConnectionField.php, src/Pagination/PaginateDirective.php, src/Pagination/PaginationArgs.php, src/Pagination/PaginationManipulator.php, src/Pagination/PaginationType.php, src/Pagination/PaginatorField.php, tests/AssertsQueryCounts.php, tests/DBTestCase.php, tests/Integration/Cache/CacheDirectiveTest.php, tests/Integration/Defer/DeferDBTest.php, tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php, tests/Integration/Pagination/PaginateDirectiveDBTest.php, tests/Integration/Schema/Directives/AggregateDirectiveTest.php, tests/Integration/Schema/Directives/BelongsToDirectiveTest.php, tests/Integration/Schema/Directives/CountDirectiveDBTest.php, tests/Integration/Schema/Directives/WithCountDirectiveTest.php
**Changes**
When doing a paginated query we use the `LengthAwarePaginator` from Laravel. This makes total sense but we can optimize in case the query doesn't request the paginator info, then we can fallback to a simple paginator saving a `count(*)` query which is always nice :)
This is especially useful when you want to do something like getting the first object from a paginated list to see if it exists or to show a data but don't want yet another attribute, instead you can do something like this without the `count(*)` query penalty:
```graphql
type User {
auditLogs: [AuditLogEntry!]! @paginate
}
type Query {
viewer: User @auth
}
{
viewer {
auditLogs(first: 1, page: 1) {
data {
id
createdAt
}
}
}
}
```
I think none... maybe API changes I made that are breaking?
=> Optimize paginator query when no page info is requested

CHANGELOG.md, src/LighthouseServiceProvider.php
Larastan requires macros to actually be registered for semi-static analysis. Otherwise, PHPStan fails with errors such as:
```
Call to an undefined method Illuminate\Testing\TestResponse::assertGraphQLErrorMessage()
```
=> Fix TestResponse macros recognition

docs/master/testing/extensions.md
No related issues.
**Changes**
Simply fix a typo where the word "revert" should have been "reverse" in 2 places of the https://lighthouse-php.com/master/testing/extensions.html#mock-resolvers documentation.
No code changes
=> Change `revert` typo to be `reverse`

CHANGELOG.md, docs/5/api-reference/directives.md, docs/5/security/authorization.md, docs/master/api-reference/directives.md, docs/master/security/authorization.md, src/Auth/CanDirective.php, src/GraphQL.php, src/Schema/Directives/ArgTraversalDirective.php, src/Schema/Directives/ConvertEmptyStringsToNullDirective.php, src/Schema/Directives/MutationExecutorDirective.php, src/Schema/Directives/NestDirective.php, src/Schema/Directives/SpreadDirective.php, src/Schema/Directives/TrimDirective.php, src/Support/Utils.php, tests/Integration/Auth/CanDirectiveDBTest.php, tests/Unit/Tests/Unit/Auth/CanDirectiveTest.php
Resolves https://github.com/nuwave/lighthouse/issues/2158
Resolves https://github.com/nuwave/lighthouse/issues/1989
**Changes**
Adds the option `resolved` to `@can` as an alternative to `find` and `query`.
Instead of fetching models to check against before calling the resolver, it will instead use the result of
resolving the field and check against that.
None.
=> Allow checking policies against resolved models in `@can`

src/Auth/CanDirective.php, tests/Integration/Auth/CanDirectiveDBTest.php
This patch addresses an issue where a non-existing instance is queried while a @can directive exists on the field that is resolved. This will result in a type error since PHP expects the first argument of the closure in question to be a Model. The following error is generated
```
Nuwave\\Lighthouse\\Auth\\CanDirective::Nuwave\\Lighthouse\\Auth\\{closure}(): Argument #1 ($model) must be of type Illuminate\\Database\\Eloquent\\Model, null given, called in /***/vendor/nuwave/lighthouse/src/Support/Utils.php on line 117"
```
**Changes**
The fix is to modify the type of the argument into a nullable type. The
operator is available since PHP 7.1, which means this should be a
backwards-compatible fix.
No breaking changes expected.
=> Handle missing models in `@can` with option `resolved`

CHANGELOG.md, src/Pagination/PaginateDirective.php, tests/Integration/Pagination/PaginateDirectiveDBTest.php
Fixes #2189
**Changes**
We calculate an optimal pagination strategy when the paginator info is not requested. But since cursor based pagination needs some special handling to correctly calculate the correct page to retrieve the `PaginationArgs::extractArgs` needs to get the original pagination type instead of the optimal type. We can change the type to the optimal one when applying it to the builder keeping the benefits but fixing the bug :)
Thanks @pyrou for finding and reporting the bug and creating the failing tests!
None.
=> Fix cursor pagination always returning the first page when no fields from the `pageInfo` are requested

CHANGELOG.md, src/Schema/AST/ASTHelper.php, src/Schema/Directives/BaseDirective.php, src/Schema/FallbackTypeNodeConverter.php, tests/Unit/Schema/AST/ASTHelperTest.php, tests/Unit/Schema/Directives/BaseDirectiveTest.php
Resolves https://github.com/nuwave/lighthouse/pull/2195
Resolves https://github.com/nuwave/lighthouse/issues/2194
**Changes**
Adds a fallback to `ASTHelper::getUnderlyingType()` for built-in types.
None.
=> Fix directive option `model` on schema elements using built-in types

CHANGELOG.md, src/Schema/Directives/ConvertEmptyStringsToNullDirective.php, src/Support/Utils.php, tests/Integration/Schema/Directives/ConvertEmptyStringsToNullDirectiveTest.php
#2130 (comment)
**Changes**
Fix `@convertEmptyStringsToNull` on fields and matrices.
None.
=> Fix `@convertEmptyStringsToNull` on fields and matrices

src/Support/Http/Middleware/EnsureXHR.php
**Changes**
This PR makes the ```handle``` method of the ```EnsureXHR``` class to inherit ```FORM_CONTENT_TYPES``` const (when EnsureXHR class is extended).
Use case:
By extending the ```EnsureXHR``` class, one can exclude any content-type (like multipart/form-data) without the need to override the middleware's handle method. 
<details>
<summary>See example code</summary>
```
...
class EnsureXHR extends \Nuwave\Lighthouse\Support\Http\Middleware\EnsureXHR
{
public const FORM_CONTENT_TYPES = [
'application/x-www-form-urlencoded',
'text/plain',
];
public function handle(Request $request, Closure $next)
{
return parent::handle($request, $next);
}
}
```
</details>
=> Open EnsureXHR middleware for extension

CHANGELOG.md, src/lighthouse.php
**Changes**
Allow configuring the disable_introspection setting via the .env file.
I find this feature useful because i like using introspection on local environments only.
On testing/production I disable introspection, so having the ability to configure introspection from the  ```.env``` file might be useful.
none
=> Allow configuring `security.disable_introspection` through the env variable `LIGHTHOUSE_SECURITY_DISABLE_INTROSPECTION`

src/Schema/Directives/UploadDirective.php
**Issue**
Our application requires different filename generation for uploads. We could not easily override the original behaviour.
**Changes**
No behaviour changes.
=> Extract uploaded file name calculation to method in @upload directive

CHANGELOG.md, src/Support/Traits/GeneratesColumnsEnum.php, src/Support/Utils.php, tests/Integration/Execution/ArgBuilderDirectiveTest.php, tests/Unit/Support/UtilsTest.php
Resolves #2216
**Changes**
GeneratesColumnsEnum trait now uses static method columnNameToGraphQLName added to Utils. This should prevent the generation of invalid GraphQL names from column names.
=> Complex where conditions custom column names fix

docs/master/digging-deeper/file-uploads.md, docs/master/security/csrf.md, src/Support/Http/Middleware/EnsureXHR.php, tests/Unit/Support/Http/Middleware/EnsureXHRTest.php
Resolves #2206
**Changes**
Wrap current logic with an `if` statement to check if header `X-Requested-With` is passed with value `XMLHttpRequest`
Shouldn't break any of the current logic.
=> Update EnsureXHR to allow X-Requested-With header

docs/5/digging-deeper/extending-lighthouse.md, docs/master/digging-deeper/extending-lighthouse.md
The link towards the Integration test example is no longer valid. PR of refactoring to use RegisterDirectiveNamespaces started here https://github.com/nuwave/lighthouse/pull/950.
Took me a while to figure out how to add my custom directive namespace for a package. This might help others :)
**Changes**
none.
none.
=> Update Adding Directives in extending-lighthouse.md

CHANGELOG.md, src/Execution/ModelsLoader/PaginatedModelsLoader.php, tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php
Resolves https://github.com/nuwave/lighthouse/issues/2264  
Supersedes https://github.com/nuwave/lighthouse/pull/2275  
Supersedes https://github.com/nuwave/lighthouse/pull/2273  
Supersedes https://github.com/nuwave/lighthouse/pull/2278  
**Changes**
=> Fix batch loading a paginated BelongsToMany relation with duplicates

CHANGELOG.md, benchmarks/ASTUnserializationBench.php, benchmarks/HugeResponseBench.php, src/Federation/EntityResolverProvider.php, src/GlobalId/GlobalIdDirective.php, src/Schema/TypeRegistry.php, tests/Integration/Federation/FederationEntitiesModelTest.php
**Changes**
Adds decoding of the global id when using the model entity resolver
This will break everyone who used the global id directive and expecting to be able to use database id's when using `_entities`. I would however argue that it is almost a bug :)
=> Feat: Add support for global id in entity resolver

CHANGELOG.md, src/Pagination/PaginateDirective.php, tests/Unit/Pagination/PaginateDirectiveTest.php
This is an update on https://github.com/nuwave/lighthouse/pull/2232
**Changes**
When using maxCount the validation wasn't applied now it is so you can get errors like:
```
"Maximum number of 20 requested items exceeded, got 30. Fetch smaller chunks."
```
Nothing.
=> Add validation support for pagination resolver mode

CHANGELOG.md, UPGRADE.md, docs/master/api-reference/directives.md, docs/master/eloquent/getting-started.md, docs/master/eloquent/soft-deleting.md, src/Schema/Directives/DeleteDirective.php, src/Schema/Directives/ModifyModelExistenceDirective.php, src/Schema/Directives/WhereKeyDirective.php, src/SoftDeletes/ForceDeleteDirective.php, src/SoftDeletes/RestoreDirective.php, tests/Integration/Auth/CanDirectiveDBTest.php, tests/Integration/Schema/Directives/DeleteDirectiveTest.php, tests/Integration/SoftDeletes/ForceDeleteDirectiveTest.php, tests/Integration/SoftDeletes/RestoreDirectiveTest.php
Resolves https://github.com/nuwave/lighthouse/issues/2288
**Changes**
Prior to this PR, `@delete`, `@forceDelete` and `@restore` relied upon the field they were used upon just defining a single
argument to use as the ID/IDs to find the models to modify.
Now, they will leverage the same mechanisms as other directives like `@all` or `@find` do to find the models:
- scopes
- argument filter directives such as `@eq`
- any other way of influencing the query builder
A new directive `@whereKey` has been added to support the most common use case of finding by primary key.
In addition, this change opens up many new possibilities to leverage those directives, e.g. deleting all models that match
a set of conditions.
TODO: determine if the same change can be made to `@update` and `@upsert`, see …
=> Require filter directives such as `@whereKey` in `@delete`, `@forceDelete` and `@restore`

docs/master/performance/schema-caching.md, src/Schema/AST/ASTCache.php, src/lighthouse.php, tests/Console/CacheCommandTest.php, tests/Console/ClearCacheCommandTest.php, tests/Integration/SchemaCachingTest.php, tests/TestsSchemaCache.php
**Changes**
Schema cache v1 is dead, long live schema cache v2.
Shouldn't really break things, but it could for some people who have a hard dependency of the schema appearing in their configured cache storage.
=> Remove schema cache v1

src/Subscriptions/Storage/RedisStorageManager.php, tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php
After you have set env
```env
LIGHTHOUSE_SUBSCRIPTION_STORAGE_TTL=3600
```
And run this:
```bash
php artisan lighthouse:ide-helper
```
you get:
```
Cannot assign string to property Nuwave\Lighthouse\Subscriptions\Storage\RedisStorageManager::$ttl of type ?int
```
That's because env() function of laravel returns string even if you have a number in your env, it can't understand that's an integer that's why this pull request fixes that bug, any where else in your codebase that you've done the same thing the same error might appear.
**Changes**
A little cast to fix a little bug.
No
=> Cast storage_ttl from env to int

src/Schema/AST/ASTCache.php
**Changes**
When [setting `LIGHTHOUSE_SCHEMA_CACHE_ENABLE` to `false` in a PHPUnit configuration](https://github.com/nuwave/lighthouse/blob/master/docs/master/performance/query-caching.md#testing-caveats), it seems that this get's parsed as an empty string. This then causes the env to be loaded incorrectly and ends up throwing an error with `Cannot assign string to property Nuwave\\Lighthouse\\Schema\\AST\\ASTCache::$enable of type bool` since the ASTCache was changed to be strictly typed properties.
I'm not sure if this would be considered an issue with PHPUnit (9) not parsing the XML correctly, however this hasn't been an issue until the properties were typed. I guess because before the empty string was treated as `false`. 🤷🏻
=> chore: cast `schema_cache.enable` to boolean

CHANGELOG.md, UPGRADE.md, docs/master/api-reference/directives.md, docs/master/security/authentication.md, src/Auth/AuthDirective.php, src/Auth/AuthServiceProvider.php, src/Auth/GuardDirective.php, src/Auth/WhereAuthDirective.php, src/Schema/Context.php, src/Subscriptions/Iterators/AuthenticatingSyncIterator.php, src/Support/Http/Middleware/AttemptAuthentication.php, src/lighthouse.php, tests/Integration/Execution/FieldBuilderDirectiveTest.php, tests/TestCase.php, tests/Unit/Auth/AuthDirectiveTest.php, tests/Unit/Auth/UserContextTest.php, tests/Unit/Support/Http/Middleware/AttemptAuthenticationTest.php
**Changes**
When using a query or mutation without `@guard` directive, to allow guest users, only one single default guard was attempted for $context->user. Specifying multiple guards with `@guard(with:)` allow to attempt multiples guard, but this would disallow guest users.
This PR propose to change the `lighthouse.guard` configuration to support multiple guards.
- `lighthouse.guard` configuration key has been renamed `lighthouse.guards` and expect now an array.
- `@auth(guard: String)` has been changed to `@auth(guards: [String!])`
- `@whereAuth(guard: String)` has been changed to `@whereAuth(guards: [String!])`
=> Support multiple default guards

CHANGELOG.md, src/Schema/TypeRegistry.php, src/Subscriptions/SubscriptionResolverProvider.php
**Changes**
Because the $className variable is overwritten in the TypeRegistry and SubscriptionResolverProvider, using it in an exception when the className could not be found results in it being null. ```Failed to find class  extends....``` This PR fixes that by assigning the resulting FQN to a new variable.
None
=> Fix empty classnames in definitionExceptions

CHANGELOG.md, src/Pagination/PaginateDirective.php, src/Subscriptions/SubscriptionRegistry.php, tests/Integration/Pagination/PaginateDirectiveDBTest.php
Fix #2354 
**Changes**
If a cache directive exists, do not manipulate the paginator type.
=> Prevent regression to simple paginator type on fields using `@cache` directive

CHANGELOG.md, src/Federation/EntityResolverProvider.php, tests/Integration/Federation/FederationEntitiesModelTest.php
See https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/352
=> Fixed resolving composite object `@key` in default model entity resolver for federation

CHANGELOG.md, docs/4/subscriptions/client-implementations.md, docs/5/subscriptions/client-implementations.md, docs/6/subscriptions/client-implementations.md, docs/master/subscriptions/client-implementations.md, src/Console/IdeHelperCommand.php
#2099 requested a way to not clash with built-in types of IDE's (mainly the Jetbrains GraphQL plugin) and #2362 partially solved that. However default scalars and introspection types were still outputted to programatic-types.graphql, this solves that.
This also fixes the `--omit-built-in` accepting a value which it probably shouldn't have since it's a boolean flag (there or not there).
=> Fix `--omit-built-in` option on `ide-helper` command not excluding default scalars and introspection types

UPGRADE.md, src/lighthouse.php, tests/Utils/Models/User.php
**Changes**
Adds the middleware `Nuwave\Lighthouse\Http\Middleware\EnsureXHR` to the default configuration commented.
This makes it easier to add it.
No, but planned for v7. HTTP `GET` and simple `POST` requests stop working when the middleware is added.
=> Add middleware `EnsureXHR` by default

CHANGELOG.md, src/Console/PrintSchemaCommand.php, src/lighthouse.php
**Changes**
- Add the ability to specify the disk the schema will print to via the `--disk` option OR the config option `lighthouse.print_schema_disk`
=> Add the ability to specify the disk the artisan command `lighthouse:print-schema` will write to via the `--disk` option

src/Console/PrintSchemaCommand.php, src/Deprecation/DetectDeprecatedUsage.php, src/Exceptions/DefinitionException.php, src/Execution/Arguments/ArgPartitioner.php, src/Federation/BatchedEntityResolver.php, src/Federation/EntityResolverProvider.php, src/GraphQL.php, src/Pagination/PaginationArgs.php, src/Pagination/PaginatorField.php, src/Pagination/SimplePaginatorField.php, src/Schema/AST/ASTHelper.php, src/Schema/AST/ExecutableTypeNodeConverter.php, src/Schema/AST/FallbackTypeNodeConverter.php, src/Schema/Directives/AggregateDirective.php, src/Schema/Directives/BaseDirective.php, src/Schema/Directives/ComplexityDirective.php, src/Schema/ResolverProvider.php, src/Schema/TypeRegistry.php, src/Validation/RulesGatherer.php, src/Validation/Validator.php, tests/Integration/Schema/Directives/AggregateDirectiveTest.php, tests/Integration/Subscriptions/Storage/RedisStorageManagerTest.php, tests/Unit/Pagination/PaginationTypeTest.php, tests/Unit/Subscriptions/Broadcasters/PusherBroadcasterTest.php, tests/Utils/Models/Task.php, tests/Utils/Models/User.php, tests/Utils/Models/WithEnum.php
Parts of https://github.com/nuwave/lighthouse/pull/2389
=> Clean up docblocks

CHANGELOG.md, Makefile, docs/6/api-reference/directives.md, docs/master/api-reference/directives.md, src/Auth/CanDirective.php, tests/Integration/Auth/CanDirectiveDBTest.php
Resolves https://github.com/nuwave/lighthouse/issues/1642
**Changes**
Allow `@can` with `find` to not throw.
None.
=> Add option `findOrFail` to `@can` directive

CHANGELOG.md, src/Pagination/PaginationManipulator.php, src/Pagination/PaginationServiceProvider.php, tests/Unit/Pagination/PaginateDirectiveTest.php
Resolves #2388
**Changes**
Currently pagination-related types are registered in the document ast even if they're never used. After this PR, these types will only be registered if they're actually needed.
None as far as I can tell.
=> Add `PaginatorInfo`, `SimplePaginatorInfo`, `PageInfo` only when required

CHANGELOG.md, src/Schema/Directives/BaseDirective.php, tests/Unit/Schema/Directives/BaseDirectiveTest.php
**Changes**
`BaseDirective::hydrate()` doesn't reset cached args. Not sure when/where it can be critical, just found in my notes....
Nope.
=> Reset cached values of arguments in `BaseDirective::hydrate()`.

.github/workflows/validate.yml, CHANGELOG.md, benchmarks/QueryBench.php, composer.json, docs/master/api-reference/directives.md, docs/master/digging-deeper/feature-toggles.md, phpstan.neon, phpunit.xml.dist, src/Pennant/FeatureDirective.php, src/Pennant/PennantServiceProvider.php, tests/Integration/Pennant/FeatureDirectiveTest.php, tests/TestCase.php
**Changes**
This PR introduces a new `@feature` directive, which can be used to conditionally add a field to the schema based on the state of a feature flag:
```graphql
query {
fieldWhenFeatureInactive: String! 
@feature(name: "new-api", when: INACTIVE)
fieldWhenFeatureActive: String!
@feature(name: "new-api")
}
```
The `fieldWhenFeatureInactive` will only be available if the feature called `new-api` is inactive, whereas fieldWhenFeatureActive will only be available when the feature is active.
I've been using this in a codebase for a client, and thought it might be useful in other projects as well. Let me know if you guys like this ;)
There are no breaking changes.
=> Add `@feature` directive to conditionally add a field based on a feature state (using Laravel Pennant)

CHANGELOG.md, src/Schema/Directives/InDirective.php, tests/Integration/Schema/Directives/InDirectiveTest.php
Resolves https://github.com/nuwave/lighthouse/issues/2444
**Changes**
Do not apply `@in` when `null` is passed.
None.
=> Handle explicit `null` in `@in` directive

CHANGELOG.md, docs/6/api-reference/directives.md, docs/6/digging-deeper/relay.md, docs/master/api-reference/directives.md, docs/master/digging-deeper/relay.md, src/GlobalId/NodeDirective.php, src/GlobalId/NodeRegistry.php, src/Schema/AST/ASTHelper.php, tests/Integration/GlobalId/NodeDirectiveDBTest.php, tests/Integration/Schema/Directives/WhereBetweenDirectiveTest.php, tests/Integration/Schema/Directives/WhereNotBetweenDirectiveTest.php
**Changes**
This change allows customizing the behaviour of the automatically added `Query.node`.
Custom definitions of field `Query.node` are no longer overwritten, I consider this more of a bugfix though.
=> Allow customizing the definition of the root `Query` field `node` added by `@node`

docs/6/api-reference/directives.md, docs/master/api-reference/directives.md, src/Schema/Directives/WhereDirective.php, tests/Integration/Schema/Directives/WhereDirectiveTest.php
Treat null values the same as if they're not present, useful to prevent InvalidArgumentException if the operator is not on of `=`, `<>` or `!=`.
**Changes**
Added the optional `ignoreNull` attribute to `@where` directive.
No
=> `@where` ignoreNull attribute

docs/6/api-reference/directives.md, docs/master/api-reference/directives.md, src/Auth/CanDirective.php, tests/Unit/Auth/CanDirectiveTest.php
No issue for this that I'm aware of, but it's a feature I've built into a custom directive I thought would be useful in the upstream as it came up recently in the community Slack.
**Changes**
This PR allows users to check the root value against a Policy so a field can be controlled by its parent model Policy.
None
=> Allow checking root model in @can directive

docs/6/the-basics/best-practices.md, docs/master/the-basics/best-practices.md, tests/Integration/Schema/ResolverProviderTest.php
Resolves #2458 
**Changes**
Changes all links in documentation from graphql-rules.com to their github as the domain graphql-rules.com is dead
=> Change all links from graphql-rules.com to github 

docs/master/api-reference/directives.md, src/Schema/Directives/NamespacedDirective.php
Helps to address #2266 in the main package without users having to create a custom field resolver.
- [ X ] Documented user facing changes
**Changes**
Adds a `@namespaced` directive; allowing mutations and queries to be posted.
Allows:
```
type Mutation {
createPost(input: CreatePostInput! @spread): Post! @create
updatePost(input: UpdatePostInput! @spread): Post! @update
deletePost(input: DeletePostInput! @spread): Post @delete
}
```
to become:
```
type Mutation {
posts: PostMutations! @namespaced
}
type PostMutations {
create(input: CreatePostInput! @spread): Post! @create
update(input: UpdatePostInput! @spread): Post! @update
delete(input: DeletePostInput! @spread): Post @delete
}
```
ref: https://www.apollographql.com/docs/technotes/TN0012-namespacing-by-separation-of-concern/
=> namespaced directive ISO #2266

src/Federation/SchemaPrinter.php, tests/Console/PrintFederationSchemaCommandTest.php
**Changes**
Fix a bug in the federation printer introduced in #2460.
It was always printing `extend schema` even when there are no extensions.
=> fix federation schema printer

docs/master/security/authentication.md
Logout sanctum example is missing a Arr::first() call, which causes an illegal offset exception
=> Fix guard type in stateful authentication example

CHANGELOG.md, composer.json, docs/6/api-reference/directives.md, docs/6/custom-directives/input-field-directives.md, docs/master/api-reference/directives.md, docs/master/custom-directives/input-field-directives.md, src/Async/AsyncDirective.php, src/Async/AsyncMutation.php, src/Async/AsyncRoot.php, src/Async/AsyncServiceProvider.php, src/Execution/ContextSerializer.php, src/GraphQL.php, src/LighthouseServiceProvider.php, src/Schema/AST/ASTBuilder.php, src/Schema/Types/LaravelEnumType.php, src/Subscriptions/Storage/CacheStorageManager.php, src/Subscriptions/Storage/RedisStorageManager.php, src/Subscriptions/Subscriber.php, src/Subscriptions/SubscriptionRegistry.php, src/Subscriptions/SubscriptionServiceProvider.php, src/Support/Contracts/SerializesContext.php, tests/Integration/Async/AsyncDirectiveTest.php, tests/Integration/Subscriptions/SerializerTest.php, tests/TestCase.php, tests/TestsSerialization.php, tests/Utils/Models/User.php, tests/Utils/Queries/MissingInvoke.php
**Changes**
Add the `@async` directive to postpone execution of a mutation through a job.
None in public APIs, but I did change the following:
- Move and rename `Nuwave\Lighthouse\Subscriptions\Contracts\ContextSerializer` to `Nuwave\Lighthouse\Support\Contracts\SerializesContext`
- Do not bind `CreatesContext` and `CanStreamResponse` as singletons
=> Add `@async` directive

Makefile
Resolves #2503
If updating `CHANGELOG.md` is necessary, could you tell me that?
I'll update it, too.
**Changes**
Changed `id` command options in `Makefile` to finish successfully both macOS and Linux.
**Notes**
I checked that `make setup` finished successfully on macOS, but I've not checked whether `make setup` also finish successfully on Linux.
The environment I checked is below.
- OS: macOS 13.6.4 (22G513)
- processor: 2.3 GHz Dual-Core Intel Core i5
- docker-compose: v2.23.3-desktop.2
- make: GNU Make 3.81
=> Fixed build command in Makefile

CHANGELOG.md, docs/6/api-reference/directives.md, docs/master/api-reference/directives.md, src/Auth/CanFindDirective.php, tests/Integration/Auth/CanFindDirectiveDBTest.php
Resolves https://github.com/nuwave/lighthouse/issues/2513
**Changes**
Fixes the directive definition.
None.
=> Allow custom model name in @canFind

CHANGELOG.md, src/Console/stubs/typeResolver.stub
Resolves https://github.com/nuwave/lighthouse/issues/2517
**Changes**
Fixes the import of `ResolveInfo`.
None.
=> Fix stub for type resolvers used in `lighthouse:union` and `lighthouse:interface` artisan commands

CHANGELOG.md, src/Schema/AST/ASTBuilder.php, tests/Unit/Schema/AST/ASTBuilderTest.php
**Changes**
Directives defined in Scalar/Enum/Input/Type/Interface type extensions will be merged into target. The following schema will create type `A` with two directives `@foo` and `@bar` (previously only with `@foo`).
```graphql
type A @foo {
field: String
}
extend type A @bar
```
Custom scalars seems fine, but for standard (`Int`/`String`/etc) the AST node is required. And I'm not sure how it should work.
Technically, it is possible to add `scalar Int`, but it will not work without `@scalar`[^1]. Adding `@scalar(class: "GraphQL\Type\Definition\IntType")` for standard scalars looks superfluous, IMHO. Moreover despite `scalar Int @scalar(class: "My\Custom\Class")` is fully valid, but seems useless, because `Type::getStandardTypes()` has a bigger priority and thus `My\Custom\Class` will …
=> Directives from Scalar/Enum/Input/Type/Interface extensions

CHANGELOG.md, src/Auth/CanDirective.php, src/Auth/CanFindDirective.php, src/Exceptions/ClientSafeModelNotFoundException.php, tests/Integration/Auth/CanDirectiveDBTest.php, tests/Integration/Auth/CanFindDirectiveDBTest.php
Resolves #2521 
**Changes**
Added custom `ClientSafeModelNotFoundException` to wrap around `ModelNotFoundException` in `@can` and `@canFind` directives.
New exception is linked to previous exception, allowing for usage in custom error handlers. With this change developers could be able to modify original exception how they want, formatting or replacing conditionally
Probably none, as new exception being safely catched into same `GraphQL\Error` and maintain original message
=> Introduce ClientSafeModelNotFoundException for `@can` and `@canFind` directives

phpstan.neon
Related to #2508 
**Changes**
This PR silences the errors raised by PHPStan after removing Lumen from the `devDependencies`.
Checks are expected to fail here, because the PR does not address the other PHPStan errors.
=> Silence Lumen errors for Laravel 11 support

CHANGELOG.md, phpstan.neon, src/Execution/Arguments/NestedMorphTo.php, tests/Integration/Execution/MutationExecutor/MorphToTest.php, tests/Utils/Enums/ImageableType.php
Resolves https://github.com/nuwave/lighthouse/pull/2544/files
=> Native PHP Enums registered through the `TypeRegistry` may be used as morph type in nested `MorphTo` relations

CHANGELOG.md, src/Execution/ModelsLoader/PaginatedModelsLoader.php
**Changes**
Right now, `toJson` is used which "is recursive, so all attributes and relations will be converted to JSON" (see https://laravel.com/docs/11.x/eloquent-serialization#serializing-to-json). This means that all accessors are executed as well which can affect the performance of an application. The new approach simply compares the raw attributes of the models which should be enough in almost all cases as far as I can see.
There might be a tiny chance that something doesn't work as before because accessors are not compared anymore.
=> Compare raw attributes only when ensuring uniqueness of paginated related models

CHANGELOG.md, src/Execution/Arguments/NestedBelongsTo.php, src/Execution/Arguments/NestedManyToMany.php, src/Execution/Arguments/NestedMorphTo.php, src/Execution/Arguments/NestedOneToMany.php, src/Execution/Arguments/NestedOneToOne.php, src/Execution/Arguments/SaveModel.php, src/Schema/Directives/DeleteDirective.php, src/Schema/Directives/MutationExecutorDirective.php, tests/Integration/Execution/MutationExecutor/BelongsToTest.php
**Changes**
Because `NestedBelongsTo` unnecessarily passed through the `$parentRelation` to `SaveModel`, updating multiple `BelongsTo` relations of a model in a single nested mutation resulted in multiple save operations. See the repeated calls to ``update `users` set`` in the following log:
```
"select * from `users` where `users`.`id` = ? limit 1" // /workdir/tests/Integration/Execution/MutationExecutor/BelongsToTest.php:518
"select * from `companies` where `companies`.`id` = ? limit 1" // /workdir/tests/Integration/Execution/MutationExecutor/BelongsToTest.php:518
"update `companies` set `name` = ?, `companies`.`updated_at` = ? where `id` = ?" // /workdir/tests/Integration/Execution/MutationExecutor/BelongsToTest.php:518
"update `users` set `name` = ?, `company_id` = ?, …
```
=> Eliminate redundant `Model::save()` calls in nested mutations

CHANGELOG.md, docs/6/api-reference/directives.md, docs/6/custom-directives/input-value-directives.md, docs/master/api-reference/directives.md, docs/master/custom-directives/input-value-directives.md, src/Schema/Directives/LimitDirective.php, tests/Integration/Auth/CanFindDirectiveDBTest.php, tests/Integration/Auth/CanQueryDirectiveDBTest.php, tests/Integration/Auth/CanResolvedDirectiveDBTest.php, tests/Integration/Execution/MutationExecutor/BelongsToTest.php, tests/Integration/Schema/Directives/InDirectiveTest.php, tests/Integration/Schema/Directives/LimitDirectiveTest.php, tests/Integration/Schema/Directives/NotInDirectiveTest.php, tests/Integration/Schema/Directives/WhereBetweenDirectiveTest.php, tests/Integration/Schema/Directives/WhereNotBetweenDirectiveTest.php, tests/Integration/Schema/Directives/WhereNotNullDirectiveTest.php, tests/Integration/Schema/Directives/WhereNullDirectiveTest.php, tests/Unit/Auth/CanModelDirectiveTest.php, tests/Unit/Auth/CanRootDirectiveTest.php
**Changes**
If your field is resolved through a database query, you may add the `builder` argument to apply
an actual `LIMIT` clause to your SQL:
```graphql
type Query {
users(limit: Int @limit(builder: true)): [User!]! @all
}
```
None, the default behaviour is the same.
=> Add option `builder` to `@limit` to apply an actual `LIMIT` clause

CHANGELOG.md, src/Schema/Directives/ThrottleDirective.php, tests/Integration/Schema/Directives/ThrottleDirectiveTest.php
Resolves https://github.com/nuwave/lighthouse/issues/2569
**Changes**
Fix bug when converting seconds to minutes - use `/` instead of `*`
n/a
=> Correct decay value calculation in `@throttle` directive

src/GraphQL.php
**Changes**
This PR will remember persisted queries locally. The idea is related to https://github.com/nuwave/lighthouse/discussions/2561. Right now, I use the `StartOperationOrOperations` event to determine whether the query is allowed or not. This works fine but previously defined queries will not work anymore as soon as I release another version. Hence, I would like to check first if the query was persisted before:
```php
$query = rescue(fn () => $graphql->loadPersistedQuery($operationId), null, false);
if ($query) {
return true;
}
```
This PR makes `loadPersistedQuery` public and also remembers persisted queries locally to avoid hitting the cache twice.
Please let me know what you think and I can try to implement tests as well.
n/a
=> feat: make `loadPersistedQuery` public

CHANGELOG.md, docs/6/digging-deeper/extending-lighthouse.md, docs/master/digging-deeper/extending-lighthouse.md, src/Async/AsyncServiceProvider.php, src/Auth/AuthServiceProvider.php, src/Cache/CacheServiceProvider.php, src/CacheControl/CacheControlServiceProvider.php, src/Defer/DeferServiceProvider.php, src/Federation/FederationServiceProvider.php, src/GlobalId/GlobalIdServiceProvider.php, src/GraphQL.php, src/LighthouseServiceProvider.php, src/OrderBy/OrderByServiceProvider.php, src/Pagination/PaginationServiceProvider.php, src/Pennant/PennantServiceProvider.php, src/Scout/ScoutServiceProvider.php, src/SoftDeletes/SoftDeletesServiceProvider.php, src/Subscriptions/SubscriptionServiceProvider.php, src/Testing/TestingServiceProvider.php, src/Tracing/TracingServiceProvider.php, src/Validation/ValidationServiceProvider.php, src/WhereConditions/WhereConditionsServiceProvider.php, tests/Integration/ErrorTest.php, tests/Unit/Events/BuildSchemaStringTest.php
Resolves https://github.com/nuwave/lighthouse/issues/2583
**Changes**
Handle errors during handling of individual GraphQL operations gracefully and include them in per-operation errors.
Error responses are now improved in certain cases.
=> Handle errors thrown in lifecycle events per operation

CHANGELOG.md, src/Schema/Factories/ArgumentFactory.php, tests/Integration/Schema/ValidatorTest.php, tests/Unit/Http/Middleware/LogGraphQLQueriesTest.php
Resolves https://github.com/nuwave/lighthouse/issues/2593
**Changes**
The following schema will now trigger a better error message when calling `php artisan lighthouse:validate-schema`:
```graphql
type Query {
foo(foo: Foo): Int
}
type Foo {
foo: Int
}
```
Before:
```
AssertionError 
assert($type instanceof Type && $type instanceof InputType)
at vendor/nuwave/lighthouse/src/Schema/Factories/ArgumentFactory.php:52
```
After:
```
GraphQL\Error\InvariantViolation: The type of Query.foo(foo:) must be Input Type but got: Foo.
```
None.
=> Improve validation message when using output types as inputs

composer.json, tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php
Some workflows errors out even for unchanged source code.
It is required for creating Laravel Scout manager. It was restricted to "^3" by something else (see previous successful run at https://github.com/nuwave/lighthouse/actions/runs/10253420278/job/28365987820)
the last items of full phpstan stack trace:
```
Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.yaml:
#0 /app/koka/lighthouse/vendor/laravel/scout/src/EngineManager.php(40): Laravel\Scout\EngineManager->ensureAlgoliaClientIsInstalled()
#1 /app/koka/lighthouse/vendor/laravel/framework/src/Illuminate/Support/Manager.php(105): Laravel\Scout\EngineManager->createAlgoliaDriver()
#2 /app/koka/lighthouse/vendor/laravel/framework/src/Illuminate/Support/Manager.php(80): …
```
=> Fix current workflow issues

src/Subscriptions/Storage/RedisStorageManager.php, tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php
**Changes**
When lighthouse subscriptions storage TTL is set every new subscription to channel will create a redis key with channel serializzed information and add the channel id to a map set related to specific topic and both keys will have TTL, but when channel is expired or closed without a webhook triggered the map set will keep filling with "dead" channels, `subscribersByTopic` method will already filter out the channel ids that expired, so this PR is going to collect those missing channel keys and then run SREM command to remove them from set map
=> Remove expired members from subscription topic stored in Redis set map

CHANGELOG.md, docs/6/api-reference/directives.md, docs/master/api-reference/directives.md, src/Schema/Directives/DeprecatedDirective.php
Resolves https://github.com/nuwave/lighthouse/issues/2081
**Changes**
Updates the directive definition for `@deprecated` to align with https://spec.graphql.org/draft/#sec--deprecated.
None.
=> Allow `@deprecated` directive on arguments and input fields

CHANGELOG.md, src/Schema/AST/ASTHelper.php, src/Schema/Factories/ArgumentFactory.php
**Changes**
Without this, the `deprecationReason` is never set, and `@deprecated` directives for input fields / arguments are stripped from `lighthouse:print-schema` output.
=> fix: ensure `deprecationReason` is set for arguments

tests/Integration/Schema/Directives/ConvertEmptyStringsToNullDirectiveTest.php, tests/Utils/Mutations/ReturnReceivedInput.php
This MR merely serves as a means to reproduce the error described in https://github.com/nuwave/lighthouse/issues/2610
=> Add two failing tests to reproduce failing ConvertEmptyStringsToNullDirective

CHANGELOG.md, src/Schema/Directives/ConvertEmptyStringsToNullDirective.php, tests/Integration/Schema/Directives/ConvertEmptyStringsToNullDirectiveTest.php
@spawnia Terribly sorry to have to bother you once more, but I think I now have two tests that lay out exactly the scenario that I am facing. The difference with the previous tests is in this case, an input type is used.
This relates to https://github.com/nuwave/lighthouse/issues/2610. Would you like me to create a new issue or can we reopen that one? Thanks again!
=> Add failing test for ConvertEmptyStringsToNullDirective when used on mutation with input type

docs/master/eloquent/complex-where-conditions.md
**Changes**
Updated the documentation. Laravel 11 has new location for registering service providers: `bootstrap/providers.php`
None.
=> for Laravel 11: add service provider to bootstrap/providers.php

CHANGELOG.md, docs/6/digging-deeper/feature-toggles.md, docs/master/digging-deeper/feature-toggles.md, src/Pennant/FeatureDirective.php, src/Schema/Directives/HideDirective.php, src/Schema/Directives/ShowDirective.php, tests/Unit/Schema/Directives/HideDirectiveTest.php
**Changes**
Directives `@show`, `@hide` and `@feature` can now be used on types, arguments and input types.
Allow `FeatureDirective` class to be extended in user-land.
None.
=> Allow `@show`, `@hide`, and `@feature` directives to be used on types, arguments and input types

CHANGELOG.md, benchmarks/QueryBench.php, phpstan.neon, src/Subscriptions/BroadcastDriverManager.php, src/Subscriptions/SubscriptionBroadcaster.php, src/Subscriptions/SubscriptionController.php, src/Subscriptions/SubscriptionRouter.php, src/Subscriptions/SubscriptionServiceProvider.php, src/Testing/MakesGraphQLRequests.php, src/Testing/MakesGraphQLRequestsLumen.php, src/Testing/TestResponseMixin.php, src/Testing/TestsSubscriptions.php, src/lighthouse.php, tests/Integration/Subscriptions/SubscriptionTest.php, tests/Unit/Subscriptions/BroadcastDriverManagerTest.php, tests/Unit/Subscriptions/Broadcasters/PusherBroadcasterTest.php
Resolves https://github.com/nuwave/lighthouse/issues/2564
Supersedes https://github.com/nuwave/lighthouse/pull/2612
**Changes**
Adds a configuration option for `lighthouse.subscriptions.broadcasters` to support Laravel Reverb.
Some internals were renamed, they should not be publicly used.
=> Support reverb as a broadcasting driver

src/Execution/ModelsLoader/CountModelsLoader.php
When dealing with **legacy databases**  the count for this related model returns a string like `"88"`, not `88`.
```
comments: [Comment] @hasMany(type: PAGINATOR)
```
After upgrading to PHP 8.4 this does not work anymore. And it throws a error 
_"Nuwave\Lighthouse\Execution\ModelsLoader\CountModelsLoader::extractCount(): Return value must be of type int, string returned"_
**Changes**
Always cast to integer. Because, this count must be an integer, always.
No.
=> Force `int` cast on ModelsLoader count

src/Execution/Arguments/UpsertModel.php, tests/Utils/Models/Post.php
**Changes**
This avoids passing empty IDs (`0`, `''` or `null`) along and filling them into the model.
I hope not.
=> Pull empty IDs instead of filling them with upsert

CHANGELOG.md, src/Schema/Directives/RelationDirective.php, tests/Integration/Schema/Directives/BelongsToDirectiveTest.php
**Changes**
When selecting the foreign key of a belongs to relation and including  `__typename` in the related models field selection no queries will be fired.
None.
=> Fix shortcut foreign key selection when including __typename

src/Schema/Directives/RelationDirectiveHelpers.php, tests/Integration/Schema/Directives/BuilderDirectiveTest.php
In the PaginatedModelsLoader, the decorateBuilder closure has an optional second parameter to pass a specific model:
https://github.com/nuwave/lighthouse/blob/master/src/Execution/ModelsLoader/PaginatedModelsLoader.php#L58C17-L58C18 
Currently, this option does not work as expected. The builder always uses the first model that created the batch loader instance, instead of the provided model.
**Changes**
Updated the decorateBuilder closure to correctly use the specific model when provided.
None
=> Fix using incorrect root for decorator when paginating

docs/master/subscriptions/getting-started.md, src/Schema/AST/DocumentAST.php, src/Subscriptions/Subscriber.php, src/lighthouse.php, tests/Unit/Subscriptions/SubscriberTest.php
**Changes**
Pusher and Echo support private encrypted channels. This allows the data to be encrypted in transit, and the shared secret will be provided by default by the SDK when the channel is prefixed with `private-encrypted-`.  
This PR aims to add a configuration to enable the generation of all channels with that prefix instead of only `private-`.
The flag is `false` by default, so no breaking change.
=> Encrypted subscription channels

CHANGELOG.md, src/Execution/Arguments/Argument.php, src/Execution/Arguments/ArgumentSetFactory.php, tests/Unit/Execution/Arguments/ArgumentSetTest.php
Resolves https://github.com/nuwave/lighthouse/issues/2681
**Changes**
Initialize `Argument::$type` with `null` and make it nullable.
None.
=> Ensure Argument::$type is initialized

CHANGELOG.md, src/Schema/AST/ASTCache.php
**Changes**
Added a public `path()` getter method to the `ASTCache` class to improve API consistency and make the class easier to extend. The method returns the current schema cache file path and allows clean external access to override the cache path without relying on direct property access.
This change:
- Exposes the internal `$path` property via a consistent public API
- Improves extensibility for use cases with dynamic schema caching (e.g. multi-tenant or per-request schemas)
- Aligns with object-oriented encapsulation best practices
None. This is a fully backward-compatible addition that does not affect existing behavior or usage.
=> feat(ast): add path() getter method to ASTCache class

CHANGELOG.md, src/Schema/Directives/LazyLoadDirective.php, tests/Integration/Schema/Directives/LazyLoadDirectiveTest.php
**Changes**
Previously #1867 removed the `Collection` type-hint from the `LazyLoadDirective` field `resultHandler`. This had the primary intent of accepting `LengthAwarePaginator` (as can be seen in the added PHPdoc), but would implicitly handle all Laravel paginators. When the PHPdoc got converted back into a type-hint utilizing DNF types in #1706, this accidentally stopped working.
I believe the type-hint can be widened to `AbstractPaginator` without issue, allowing `@lazyLoad` to combine with `@paginate` once more.
Since this widens the accepted parameters, no compatibility break expected.
=> Allow combining `@lazyLoad` and `@paginate`

CHANGELOG.md, UPGRADE.md, src/Testing/MakesGraphQLRequests.php, src/Testing/MakesGraphQLRequestsLumen.php, src/Testing/RefreshesSchemaCache.php, tests/Unit/Testing/TestingTraitDummyLumen.php
**Changes**
Make `RefreshesSchemaCache` non-bootable by renaming its main method.
The schema cache is now refreshed only when methods from `MakesGraphQLRequests` that use the schema are called.
Only test code is potentially affected, so no issues in production can occur.
When `RefreshesSchemaCache` is used and relied upon in test cases that use other methods than the ones in `MakesGraphQLRequests`, the schema cache will not be refreshed.
I reckon few if any users could have such a setup, they can fix their tests by calling `refreshSchemaCache` manually.
=> Refresh schema cache lazily when GraphQL requests are made through `MakesGraphQLRequests`
