.travis.yml

Also test on PHP 7 and PHP 7.1.

Also test on PHP 7 and PHP 7.1.

---

.gitattributes
.styleci.yml

The service has to be enabled first : https://styleci.io/
(free for public repos)

Enable StyleCI.

---

.editorconfig
.gitattributes

Add a editorconfig file.

---

composer.json

Add keywords to composer.

---

src/Schema/Generators/ConnectionGenerator.php
src/Schema/QueryParser.php

Remove useless is_object check.

Remove useless is_object check.

---

src/Schema/FieldParser.php
src/Support/Traits/Container/SchemaClassRegistrar.php

Add missing properties.

---

src/GraphQL.php

Optimize eager-load.

---

.gitattributes

No need to export tests and assets.

No need to export tests and assets.

---

composer.json

Refactor composer.json

---

.travis.yml
src/Schema/Registrars/BaseRegistrar.php

Let TravisCI run tests
---
It would be good to enable TravisCI for this repo, and enable TravisCI PR status too, so that anyone can check that the builds pass

Let TravisCI run tests

---

composer.json

Add composer support section

---

src/GraphQL.php
src/LaravelServiceProvider.php
src/Schema/Generators/ConnectionGenerator.php
src/Schema/Generators/ConnectionResolveGenerator.php
src/Schema/QueryParser.php
src/Schema/Registrars/BaseRegistrar.php
src/Schema/Registrars/ConnectionRegistrar.php
src/Schema/Registrars/CursorRegistrar.php
src/Schema/Registrars/EdgeRegistrar.php
src/Schema/Registrars/TypeRegistrar.php
src/Support/Cache/FileStore.php
src/Support/DataLoader/GraphQLDataFetcher.php
src/Support/DataLoader/GraphQLDataLoader.php
src/Support/DataLoader/QueryBuilder.php
src/Support/Definition/EloquentType.php
src/Support/Definition/GraphQLField.php
src/Support/Definition/GraphQLType.php
tests/Definition/EloquentTypeTest.php

Avoid using collect helper.
---
The imports sort do not respect Laravel syntax as https://styleci.io does not seem to be enabled (this is free for public repositories)

Avoid using collect helper.

---

.travis.yml
composer.json

Let lighthouse also support Laravel 5.3

Let lighthouse also support Laravel 5.3

---

.php_cs

Switch to new Config class

---

src/GraphQL.php
src/Schema/Registrars/EdgeRegistrar.php
src/Support/Cache/FileStore.php
src/Support/DataLoader/GraphQLDataFetcher.php
src/Support/Definition/EloquentType.php
src/Support/Definition/GraphQLField.php
src/Support/Definition/GraphQLType.php
src/Support/Definition/PageInfoType.php
src/Support/Definition/RelayConnectionType.php

Avoid useless return

---

.gitignore
.travis.yml
composer.json
phpunit.xml.dist

Provide some code coverage

---

tests/Definition/EloquentTypeTest.php
tests/Definition/GlobalIdTest.php
tests/Definition/GraphQLTypeTest.php
tests/Queries/CursorTest.php
tests/Queries/QueryTest.php
tests/Schema/Generators/EdgeTypeGeneratorTest.php
tests/Schema/Registrars/ConnectionRegistrarTest.php
tests/Schema/Registrars/TypeRegistrarTest.php

Use stricter assertions

---

src/Schema/Generators/ConnectionGenerator.php
src/Schema/Generators/ConnectionResolveGenerator.php
src/Schema/Generators/EdgeTypeGenerator.php
src/Schema/Generators/SchemaGenerator.php
src/Schema/Generators/TypeGenerator.php

Fix all generators docblocks

---

src/Schema/Registrars/BaseRegistrar.php
src/Schema/Registrars/ConnectionRegistrar.php
src/Schema/Registrars/CursorRegistrar.php
src/Schema/Registrars/DataFetcherRegistrar.php
src/Schema/Registrars/DataLoaderRegistrar.php
src/Schema/Registrars/EdgeRegistrar.php
src/Schema/Registrars/MutationRegistrar.php
src/Schema/Registrars/QueryRegistrar.php
src/Schema/Registrars/SubscriptionRegistrar.php
src/Schema/Registrars/TypeRegistrar.php

Fix registars docblocks

---

phpunit.xml.dist

Remove deprecated tap coverage

Remove deprecated tap coverage

---

.travis.yml

Only run code-coverage once per build.

Only run code-coverage once per build.

---

src/Schema/Connection.php
src/Schema/Field.php
src/Schema/FieldParser.php
src/Schema/QueryParser.php
src/Schema/SchemaBuilder.php

Fix schema docblocks

---

phpunit.xml.dist

Format phpunit.xml.dist

---

composer.json
src/Schema/Utils/SchemaStitcher.php

Got an error after install, 
My suggestion its to publish a demo file if not found with the user model with a login and a create mutation, maybe also a relationship as you got in the v2 roadmap.
Have also added the package auto discovery functionality including the Alias, I think its cool feature.
Does project needs anything else than a initial .graphql file to make a working demo? 
Maybe 1 .graphql with a couple imports?
BTW: as far as I got, your code its crystal clear, congrats!

Installation error fix.

---

tests/Integration/Schema/Directives/Fields/BelongsToTest.php
tests/Utils/Models/User.php
tests/database/migrations/2018_02_28_000001_create_testbench_users_table.php

Hey @chrissm79 ,
I found issue with belongsTo directive: if use more than one(I test with two) relation in query only last relation is queried and result used in other relation. 
In PR I add test with two different relations and belongsTodirective that failed at this moment.
Thank you for your awesome job.

add testcase for belongsTo directive with two different relations

---

src/Providers/LighthouseServiceProvider.php

Fixed a bug with lumen not having support for loadRoutesFrom method.

[Fix] Fixed a bug with Lumen support

---

src/Support/DataLoader/Loaders/BelongsToLoader.php
src/Support/DataLoader/Loaders/HasManyLoader.php

Fixes relations not set when the model primary key is not 'id'.

Handle custom model primary key

---

docker-compose.yml

This should be helpful when developing with lighthouse.
Maybe we can put some additional info about contributing into the readme, or a seperate contributing.md?
I would be willing to write something up if you are interested.

Add docker-compose file for easily setting up a local dev environment for running tests

---

src/Console/ClearCacheCommand.php
src/Console/PrintSchemaCommand.php
src/Console/ValidateSchemaCommand.php
src/Providers/LighthouseServiceProvider.php

- Clear the cache
- Validate the schema
- Print the schema to console or a file

Add in console commands for schema interaction

---

src/Schema/AST/ASTBuilder.php
src/Schema/AST/ASTHelper.php
src/Schema/AST/DocumentAST.php
src/Support/Traits/AttachesNodeInterface.php
tests/Unit/Schema/AST/ASTBuilderTest.php
tests/Unit/Schema/Directives/Nodes/GroupDirectiveTest.php

Immutable DocumentAST

---

.php_cs

Supersedes #55 
This PR only adds the rule to the php-cs-fixer config. I would actually apply the rules when we have the currently open PR's merged, so we can do it easily and free of conflicts.

Sort import by length

---

src/Schema/AST/DocumentAST.php
tests/Integration/Schema/Directives/Fields/HasManyDirectiveTest.php

Use original definition hash if provided

---

src/Schema/Directives/Args/RulesDirective.php
src/Schema/Directives/BaseDirective.php
src/Schema/Factories/FieldFactory.php
src/Schema/Factories/RuleFactory.php
tests/Unit/Schema/Directives/Args/RulesDirectiveTest.php
tests/Unit/Schema/Factories/RuleFactoryTest.php

This PR provides users w/ a way to add custom messages to the new `@rules` directive. 
```graphql
input UserInput {
email: String @rules(
apply: ["required", "email"]
messages: {
required: "Email address is required.",
email: "Please use a valid email address."
}
)
}
```

[WIP] Custom Rule Messages

---

assets/default-schema.graphql
src/Providers/LighthouseServiceProvider.php

The schema is oriented at the default user class the Laravel Framework provides.
It should work out of the box for most users and hopefully give a nice example
for a smooth onboarding and getting started.
**PR Type**
Feature

Add in default schema and publish it

---

src/GraphQL.php
src/Schema/Factories/FieldFactory.php
src/Schema/Factories/NodeFactory.php
src/Schema/Factories/ValueFactory.php
src/Schema/SchemaBuilder.php
src/Schema/Values/FieldValue.php
src/Support/Traits/HandlesTypes.php
tests/Unit/Schema/Factories/ValueFactoryTest.php

**Changes**
This PR allows users to define their own Node/Field/Arg Value resolvers. This opens the door to adding domain logic to these values as they are passed through the pipeline (#185). Custom values do need to extend Lighthouse's.

Feature: Value Factory

---

config/config.php

**PR Type**
Docs
**Changes**
The behaviour of the route configuration options was not clear to me. I investigated a bit
and added comprehensive comments, detailing the behaviour.
Nope

Expand the comments for config.php and clarify the options

---

src/Schema/DirectiveRegistry.php
src/Schema/Directives/Fields/AllDirective.php
tests/Integration/Schema/Directives/Fields/AllDirectiveTest.php
tests/Unit/Schema/DirectiveRegistryTest.php

Resolves #173 #187 
**PR Type**
Feature
No

Introduce @all directive which simply gets all models for a field

---

src/Schema/AST/ASTHelper.php
src/Schema/Directives/BaseDirective.php
tests/Integration/Schema/Directives/Fields/DeleteDirectiveTest.php
tests/Integration/Schema/Directives/Fields/FindDirectiveTest.php
tests/TestCase.php

Resolves #193
**PR Type**
Feature
**Changes**
See #193 
No

Default to field type when no model argument is given

---

src/Schema/DirectiveRegistry.php

#195 
**PR Type**
Refactor
**Changes**
Lighthouse will now resolve directives via the Laravel's service container.
None

Use Service Container to resolve directives

---

src/Schema/Directives/Nodes/InterfaceDirective.php
src/Schema/Directives/Nodes/ScalarDirective.php
src/Schema/Directives/Nodes/UnionDirective.php
src/Schema/Factories/ArgumentFactory.php
src/Schema/Factories/FieldFactory.php
src/Schema/Factories/NodeFactory.php
tests/Unit/Schema/Directives/Nodes/ScalarDirectiveTest.php
tests/Unit/Schema/SchemaBuilderTest.php

**PR Type**
Refactor/Tests
**Changes**
This makes handling much easier through the utility already present in BaseDirective.
I created additional tests to fully detail the expected behaviour when no class
or even no directive is given.
Nope

Always resolve scalar types through the ScalarResolver

---

tests/Unit/Schema/Directives/Args/BcryptDirectiveTest.php

#224
**PR Type**
Tests
**Changes**
Just added a test that proves the current implementation is working

Add a test for the bcrypt directive

---

src/Schema/Directives/BaseDirective.php
src/Schema/Factories/ValueFactory.php
src/Schema/Values/CacheValue.php
src/Schema/Values/FieldValue.php
src/Support/Traits/HandlesTypes.php
tests/Unit/Schema/Directives/Args/RulesDirectiveTest.php
tests/Utils/Scalars/Email.php

**PR Type**
Reformat, fix some tiny issues such as typos, phpdocs etc

Fix some trivial issues

---

src/Support/Database/QueryFilter.php
src/Support/Traits/HandlesQueryFilter.php
tests/Integration/Schema/Directives/Args/QueryFilterDirectiveTest.php

#231 
**PR Type**
Bugfix
**Changes**
I create a composed key for the where directive based in the argument name and key name.
None

fix filters when use the same key multiple times. closes #231

---

src/Schema/Directives/Fields/AuthDirective.php
src/Schema/Directives/Fields/CanDirective.php
tests/TestCase.php
tests/Unit/Schema/Directives/Fields/AuthDirectiveTest.php
tests/Unit/Schema/Directives/Fields/CanDirectiveTest.php
tests/Utils/Policies/AuthServiceProvider.php
tests/Utils/Policies/UserPolicy.php

#244 #239 
**PR Type**
Fix/Cleanup
**Changes**
Cleanup the behaviour of the @can and @auth directive and add unit tests
for @can.
Nope

Auth and can

---

src/Schema/AST/ASTBuilder.php

Convert the descriptions of built-in types to the new syntax

---

src/Schema/Directives/Nodes/InterfaceDirective.php
tests/Integration/Schema/Directives/Nodes/InterfaceDirectiveTest.php
tests/Integration/Schema/Directives/Nodes/UnionDirectiveTest.php

Simplify InterfaceDirective and add tests for it & UnionDirective

---

tests/TestCase.php
tests/Unit/Schema/Factories/NodeFactoryTest.php

Use the PartialParser to simplify the NodeFactory tests

---

src/Support/Validator/GraphQLValidator.php
src/Support/Validator/Validator.php
src/Support/Validator/ValidatorFactory.php
tests/Unit/Support/Validator/ValidatorTest.php

**PR Type**
Refactor
Minor, custom validator classes may need to add the type hints

Add type hints to the validator class

---

src/GraphQL.php
src/Schema/Resolvers/NodeResolver.php
src/Support/Contracts/ExceptionHandler.php

could not fit those in other prs

Type hints, formatting, removing dead code

---

docker-compose.yml
tests/Integration/Support/Exceptions/HandlerTest.php

This makes it so the tests also pass in the local docker-compose dev env

fix issue where the debug setting was affecting local tests

---

src/Support/DataLoader/BatchLoader.php

#253 
**PR Type**
Fix for batch loader path name.
None

[FIX] Path name for batch loader

---

composer.json
src/GraphQL.php
src/Schema/Extensions/ExtensionRequest.php
src/Schema/Extensions/GraphQLExtension.php
src/Schema/Extensions/TraceExtension.php

- Add type hints to the extensions classes
- fix up inconsistent config option keys
- require ext-json in composer.json
Minor changes for custom Extensions implementations
ext-json is implicetely required already, better to make it a hard requirement.

Fix some inconsistencies with Extensions

---

composer.json

Suggest installing mll-lab/laravel-graphql-playground

---

src/Execution/MutationExecutor.php
src/Schema/Directives/Fields/PaginateDirective.php
src/Support/DataLoader/Loaders/HasManyLoader.php
src/Support/DataLoader/Loaders/HasOneLoader.php

Resolves #319 
**PR Type**
Bugfix

[WIP] Use Laravel native load functionality instead of rolling our own

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add checklist to issue templates

---

.github/CONTRIBUTING.md

Add code guideline to not use Facades

---

assets/default-schema.graphql
src/Schema/Types/Scalars/Date.php
tests/Unit/Schema/Types/Scalars/DateTest.php

added Date as new scalar type

---

README.md

While sitting with a co-worker, i saw him scrambling to find the docs link. I made it bigger.

Make the docs link appear more visible in the README

---

src/Support/Http/Controllers/GraphQLController.php

#378
**PR Type**
Bugfix
**Changes**
Adds sanity check to make sure the route is defined on the request since we have logic in the `GraphQLController`'s constructor that will break `php artisan route:list`
None, the route should always be defined if it is a HTTP request, if not, then that means the controller's constructor is being call programmatically (i.e., getting a list of routes).

[Hotfix] Route Check

---

src/Execution/MutationExecutor.php

**PR Type**
Refactor/Docs
**Changes**
Added comments and extracted some common functionality between 
updateNested and createNested into a single method.
Nope

Document the functionality of nested Mutations

---

config/config.php
src/Console/MutationCommand.php
src/Console/QueryCommand.php
src/Console/stubs/field.stub
src/Providers/LighthouseServiceProvider.php

**PR Type**
Feature
**Changes**
Add artisan commands for adding convention compliant single-class field resolvers.
Sort default namespaces and command imports.
Nope

Field and mutation generator commands

---

.gitattributes

export-ignore some more unneeded stuff

---

src/Exceptions/ValidationException.php
src/Execution/GraphQLValidator.php
src/GraphQL.php
src/Schema/AST/ASTHelper.php
src/Schema/AST/DocumentAST.php
src/Schema/Context.php
src/Schema/DirectiveRegistry.php
src/Schema/Directives/Args/BcryptDirective.php
src/Schema/Directives/BaseDirective.php
src/Schema/Directives/Fields/AllDirective.php
src/Schema/Directives/Fields/CacheDirective.php
src/Schema/Directives/Fields/PaginateDirective.php
src/Schema/Factories/ArgumentFactory.php
src/Schema/Factories/FieldFactory.php
src/Schema/Factories/NodeFactory.php
src/Schema/Factories/RuleFactory.php
src/Schema/SchemaBuilder.php
src/Schema/Values/FieldValue.php
src/Support/Contracts/ArgMiddleware.php
src/Support/Http/Controllers/GraphQLController.php
tests/Integration/Schema/Directives/CacheDirectiveTest.php
tests/Unit/Schema/Factories/RuleFactoryTest.php

Pulling this in before some bigger changes to keep the PR's that
contain functional changes more focused.

Formatting plus some PHPDoc cleanup

---

src/Schema/Values/NodeValue.php

None
**PR Type**
Feature
**Changes**
Add shortcut to access type definition node fields.
None

[Feat] Add shortcut to get NodeValue type definition fields

---

docs/.github/README.md
docs/.vuepress/lib/versioning.js
docs/INDEX.md

Fix latest version method. It should be latest version, not the master.

Fix latest version method

---

docs/2.6/api-reference/directives.md
docs/master/api-reference/directives.md

**Changes**
Added docs for `@search` directive

[Docs] Added @search directive

---

docs/2.6/api-reference/directives.md

Docs (2.6): Add `key` argument for @eq operator

---

docs/master/api-reference/directives.md

Docs (master): Add `key` argument for @eq operator

---

src/Schema/Types/Scalars/Date.php
tests/Unit/Schema/Types/Scalars/DateTest.php

Set date to startofDay otherwise Date is set date + current timestamp and fails equality checks with existing dates
No

Set Date to startOfDay

---

docs/.vuepress/enhanceApp.js
docs/.vuepress/styles/index.styl
docs/INDEX.md
docs/package.json

Doc Updates
**Changes**
Add routes to internal pages to use on homepage.
N/A

[Docs] Add routes to internal pages

---

docs/.vuepress/styles/index.styl
docs/master/extensions/deferred.md
docs/master/sidebar.js
docs/packages/vuepress-theme-lighthouse/components/Footer.vue
docs/packages/vuepress-theme-lighthouse/package.json

Add docs for `DeferExtension` which includes new "Extensions" section in sidebar.
**Changes**
Docs
N/A

[DOCS] Defer Extension

---

src/Schema/Extensions/ExtensionRegistry.php
src/Schema/Extensions/GraphQLExtension.php
src/Schema/Extensions/TracingExtension.php
src/Schema/Factories/RuleFactory.php

**Changes**
Fix some docblocks.
No

Fix some docblocks.

---

src/GraphQL.php
src/Schema/Directives/Fields/DeferrableDirective.php
src/Schema/Extensions/DeferExtension.php
src/Schema/Extensions/TracingExtension.php
src/Support/Http/Controllers/GraphQLController.php
src/Support/helpers.php
tests/Integration/Schema/Directives/Fields/BelongsToTest.php
tests/Unit/Schema/Extensions/DeferExtensionTest.php
tests/Unit/Schema/Extensions/GraphQLExtensionTest.php
tests/Unit/Schema/Extensions/TracingExtensionTest.php
tests/Utils/Models/Product.php

**Changes**
The codebase contains lots of useless imports, this PR removes them.
No breaking change.

Remove useless imports.

---

src/Schema/AST/ASTBuilder.php

**Changes**
This PR remove a useless variable assignment.
No breaking change

Remove a useless variable assignment.

---

composer.json

**Changes**
This PR enforces PRETTY_PRINT JSON syntax on composer.json.
It also sorts packages as required by `sort-packages` config key.

Get sorted packages and PRETTY_PRINT composer.json 

---

tests/database/factories/ACLFactory.php
tests/database/factories/Color.php
tests/database/factories/CommentFactory.php
tests/database/factories/CompanyFactory.php
tests/database/factories/PostFactory.php
tests/database/factories/ProductFactory.php
tests/database/factories/RoleFactory.php
tests/database/factories/TagFactory.php
tests/database/factories/TaskFactory.php
tests/database/factories/TeamFactory.php
tests/database/factories/UserFactory.php

**Changes**
Simplify and make factories consistent:
- Import all models
- No need to set `created_at` and `updated_at` fields as they're all automatically populated
- Type-hint `$factory`
No

Simplify and make factories consistant.

---

tests/Integration/Schema/Directives/Args/SearchDirectiveTest.php
tests/Integration/Support/DataLoader/ModelRelationLoaderPolymorphicTest.php
tests/Integration/Support/DataLoader/ModelRelationLoaderTest.php
tests/TestCase.php
tests/Unit/Schema/AST/SchemaStitcherTest.php
tests/Unit/Schema/DirectiveRegistryTest.php

**Changes**
- Ensure tests setUp and tearDown are protected 
- Also ensures that the parent function is always called.
No

Ensure tests setUp and tearDown are protected 

---

tests/Integration/Schema/Directives/CacheDirectiveTest.php
tests/Integration/Schema/Directives/Fields/FindDirectiveTest.php
tests/Integration/Schema/Source/SchemaSourceProviderTest.php
tests/Unit/Schema/AST/PartialParserTest.php
tests/Unit/Schema/Directives/Args/RulesDirectiveTest.php
tests/Unit/Schema/Directives/Fields/AuthDirectiveTest.php
tests/Unit/Schema/Directives/Fields/MethodDirectiveTest.php
tests/Unit/Schema/Directives/Fields/RenameDirectiveTest.php
tests/Unit/Schema/Directives/Nodes/GroupDirectiveTest.php
tests/Unit/Schema/Extensions/DeferExtensionTest.php
tests/Unit/Schema/Extensions/GraphQLExtensionTest.php

**Changes**
Prefer stricter string assertions.
No

Prefer stricter string assertions.

---

tests/Unit/Schema/AST/PartialParserTest.php

**Changes**
Use consistent tests naming convention: all tests use the `@test` docblock. There is no reason why these ones should not.
No

Use consistant tests naming convention.

---

tests/Unit/Schema/AST/SchemaStitcherTest.php

**Changes**
Ensure all tests classes extends Tests\TestCase (instead of phpunit framework testcase)
No

Ensure all tests classes extend Tests\TestCase.

---

src/Execution/QueryFilter.php
src/Schema/DirectiveRegistry.php
src/Schema/Directives/Fields/PaginateDirective.php
src/Schema/Source/SchemaStitcher.php
src/Support/Http/Responses/Stream.php
tests/Integration/Schema/Directives/CacheDirectiveTest.php

Avoid string helpers functions.
**Changes**
Call directly Str methods
No breaking change.

Avoid string helpers functions.

---

docs/2.6/guides/relationships.md
docs/master/api-reference/directives.md
docs/master/extensions/deferred.md
docs/master/getting-started/configuration.md
docs/master/getting-started/installation.md
docs/master/getting-started/tutorial.md
docs/master/guides/auth.md
docs/master/guides/relationships.md
docs/master/guides/relay.md
docs/master/guides/schema-organisation.md
docs/master/guides/validation.md
docs/master/the-basics/fields.md

- optimise -> optimize
- Change namespaces to the new defaults
- Always prefer `[TypeName!]!` list definitions
- Some formatting

Update the master docs to the latest changes

---

docs/master/guides/relationships.md
docs/master/the-basics/fields.md

Add docs for nested mutations for BelongsTo relationships

---

docs/2.6/api-reference/directives.md
docs/master/api-reference/directives.md

Add the @cache directive to the documentation

---

.travis.yml
composer.json
src/Console/stubs/scalar.stub
src/Exceptions/GenericException.php
src/Execution/ExtensionErrorHandler.php
src/Schema/Types/Scalars/Date.php
src/Schema/Types/Scalars/DateTime.php
src/Schema/Values/FieldValue.php
src/Subscriptions/Subscriber.php
src/Support/helpers.php
tests/Integration/Subscriptions/HandlesSubscribers.php
tests/Unit/Schema/Directives/Args/RulesDirectiveTest.php
tests/Unit/Schema/Extensions/DeferExtensionTest.php
tests/Utils/Scalars/Email.php

Breaking changes for our users are minimal, as we wrap webonyx most of the time.
Read https://github.com/webonyx/graphql-php/blob/v0.13.0/UPGRADE.md for more information.
Resolves #218

Bump webonyx/graphql-php to ^0.13 and php to >= 7.1

---

.travis.yml

**Changes**
Enable Travis for PHP 7.3.
No beaking change

Enable Travis for PHP 7.3.

---

src/Console/ClearCacheCommand.php
src/Console/InterfaceCommand.php
src/Console/LighthouseGeneratorCommand.php
src/Console/MutationCommand.php
src/Console/PrintSchemaCommand.php
src/Console/QueryCommand.php
src/Console/ScalarCommand.php
src/Console/UnionCommand.php
src/Console/ValidateSchemaCommand.php
src/Console/stubs/field.stub
src/Console/stubs/scalar.stub
src/Console/stubs/typeResolver.stub

None
**Changes**
Add FQCN docblocks and return types + typehint functions
None

Console comments and return types.

---

README.md

None
**Changes**
Small update in Readme
None

Update Readme list

---

config/config.php
src/Subscriptions/BroadcastManager.php
src/Subscriptions/SubscriptionRouter.php
tests/Unit/Schema/Directives/Fields/MiddlewareDirectiveTest.php

none
**Changes**
Enforce `::class` notation.
none

Enforce ::class notation.

---

tests/Integration/GraphQLTest.php
tests/Integration/Schema/Directives/CacheDirectiveTest.php
tests/Integration/Schema/Directives/Fields/BelongsToManyDirectiveTest.php
tests/Integration/Schema/Directives/Fields/BelongsToTest.php
tests/Integration/Schema/Directives/Fields/HasManyDirectiveTest.php
tests/Integration/Schema/Directives/Fields/PaginateDirectiveTest.php
tests/Integration/Schema/Directives/Fields/UpdateDirectiveTest.php
tests/Integration/Schema/Directives/Fields/WithDirectiveTest.php
tests/Integration/Schema/Extensions/DeferExtensionDBTest.php
tests/Integration/Subscriptions/BroadcastManagerTest.php
tests/Integration/Subscriptions/StorageManagerTest.php
tests/Integration/Support/DataLoader/ModelRelationLoaderPolymorphicTest.php
tests/Integration/Support/DataLoader/ModelRelationLoaderTest.php
tests/Unit/Schema/AST/ASTHelperTest.php
tests/Unit/Schema/Directives/Args/RulesDirectiveTest.php
tests/Unit/Schema/Directives/Client/ClientDirectiveTest.php
tests/Unit/Schema/Directives/Fields/DeprecatedDirectiveTest.php
tests/Unit/Schema/Directives/Fields/PaginateDirectiveTest.php
tests/Unit/Schema/Directives/Fields/SubscriptionDirectiveTest.php
tests/Unit/Schema/Extensions/DeferExtensionTest.php
tests/Unit/Schema/Extensions/TracingExtensionTest.php
tests/Unit/Schema/Factories/DirectiveFactoryTest.php
tests/Unit/Schema/Factories/NodeFactoryTest.php
tests/Unit/Subscriptions/Iterators/SyncIteratorTest.php

None
**Changes**
Clean up tests:
- use protected for setUp and tearDown functions
- remove obvious useless docblocks
- use stricter assertions

Clean up tests.

---

src/Execution/DataLoader/ModelRelationFetcher.php
src/Execution/ErrorBuffer.php
src/Schema/AST/DocumentAST.php
src/Schema/Directives/Args/SearchDirective.php
src/Schema/Directives/BaseDirective.php
src/Schema/Directives/Fields/CanDirective.php
src/Schema/Directives/Fields/GlobalIdDirective.php
src/Schema/Directives/Fields/PaginateDirective.php
src/Schema/Factories/DirectiveFactory.php
src/Schema/Factories/NodeFactory.php
src/Schema/Values/FieldValue.php
src/Support/Utils.php
tests/Unit/Schema/AST/DocumentASTTest.php
tests/Unit/Schema/Factories/DirectiveFactoryTest.php

none
**Changes**
Do not use functions backslashes.
none

Do not use functions backslashes.

---

src/Execution/DataLoader/BatchLoader.php
src/Execution/ErrorBuffer.php
src/Execution/MutationExecutor.php
src/Execution/Utils/Subscription.php
src/Schema/AST/ASTBuilder.php
src/Schema/AST/PartialParser.php
src/Schema/Conversion/DefinitionNodeConverter.php
src/Schema/Directives/Args/SearchDirective.php
src/Schema/Directives/BaseDirective.php
src/Schema/Directives/Fields/CacheDirective.php
src/Schema/Directives/Fields/DeferrableDirective.php
src/Schema/Directives/Fields/DeleteDirective.php
src/Schema/Directives/Fields/PaginationManipulator.php
src/Schema/Extensions/DeferExtension.php
src/Schema/Factories/FieldFactory.php
src/Subscriptions/Authorizer.php
src/Subscriptions/Broadcasters/PusherBroadcaster.php
src/Subscriptions/Subscriber.php
src/Subscriptions/SubscriptionRegistry.php
src/Subscriptions/SubscriptionRouter.php
tests/Integration/Schema/Directives/Args/SearchDirectiveTest.php
tests/Unit/Schema/AST/ASTHelperTest.php
tests/Unit/Schema/Directives/Client/ClientDirectiveTest.php
tests/Utils/Policies/UserPolicy.php

None
**Changes**
Do not use yoda-style notation.
None

Do not use yoda-style notation.

---

docs/2.6/api-reference/directives.md

Fixed rendering of where directive in documentation

---

src/GraphQL.php

None
**Changes**
Cleanup GraphQL.
None

Cleanup GraphQL.

---

src/Subscriptions/Broadcasters/PusherBroadcaster.php
src/Subscriptions/SubscriptionRouter.php
src/Support/Http/Responses/ResponseStream.php
tests/Integration/Schema/Directives/Args/SearchDirectiveTest.php
tests/Unit/Schema/Directives/Client/ClientDirectiveTest.php

None
**Changes**
Enforce stricter comparisons
None

Enforce stricter comparisons.

---

src/Execution/MutationExecutor.php
src/Execution/Utils/GlobalId.php
src/Schema/AST/DocumentAST.php
src/Schema/Directives/BaseDirective.php
src/Schema/Directives/Fields/ComplexityDirective.php
src/Schema/Directives/Fields/FieldDirective.php
src/Schema/NodeRegistry.php

None
**Changes**
Prefer shorter list syntax.
NOne

Prefer shorter list syntax.

---

src/Schema/Directives/Fields/CacheDirective.php
src/Schema/Extensions/ExtensionRequest.php
src/Support/DriverManager.php
src/Support/Http/Controllers/GraphQLController.php
src/Support/Pipeline.php

None
**Changes**
Replace is_null() with === null.
None

Replace is_null() with === null.

---

src/Schema/Conversion/DefinitionNodeConverter.php
src/Support/DriverManager.php
tests/Utils/Interfaces/Nameable.php

None
**Changes**
Get rid of useless else & elseif.
None

Get rid of useless else & elseif.

---

config/config.php
docs/master/api-reference/directives.md
docs/master/extensions/subscriptions.md
src/Schema/Directives/Fields/SubscriptionDirective.php
src/Schema/Values/FieldValue.php
tests/Unit/Schema/Directives/Fields/SubscriptionDirectiveTest.php

None
**Changes**
Adds default namespace for subscriptions.
None

[Feat] Add default subscription namespace

---

docs/INDEX.md
docs/packages/vuepress-theme-lighthouse/components/Footer.vue

No open issue.
**Changes**
Updates the copyright year on the website and docs footers from `2018` to `2019`.
None :smile:

Update the copyright year in the footer

---

tests/database/factories/CategoryFactory.php

Simplify CategoryFactory
**Changes**

Remove unnecessary time assignment CategoryFactory

---

config/config.php
docs/master/getting-started/configuration.md

Add missing DeferExtension to the config, some formatting

---

docs/master/guides/relationships.md

Add more extensive and descriptive docs for nested mutations

---

docs/pages/resources.md

Add Lighthouse usage tutorial
Docs update
**Changes**
Added tutorial to docs
None

Add Tutorial to Lighthouse Resources

---

config/config.php
src/Subscriptions/BroadcastManager.php

This allow you to configure which broadcast connection parameters are used to configure the Pusher broadcaster, this gives you a bit more flexibility IMO.

Use Laravel broadcast connection parameters for Pusher broadcaster

---

.travis.yml
composer.json
tests/Integration/Subscriptions/BroadcastManagerTest.php
tests/Unit/Schema/Directives/Args/RulesDirectiveTest.php

**Changes**
Refactor Travis build and fix tests

Refactor Travis / Fix tests

---

src/Schema/Directives/Fields/CanDirective.php

Double Negative

---

src/Execution/DataLoader/BatchLoader.php
src/Execution/DataLoader/ModelRelationFetcher.php
src/Execution/ErrorBuffer.php
src/Execution/ErrorHandler.php
src/Execution/ExtensionErrorHandler.php
src/Execution/MutationExecutor.php
src/Execution/QueryAST.php
src/Execution/QueryFilter.php
src/Execution/Utils/Cursor.php
src/Execution/Utils/Pagination.php
src/Execution/Utils/Subscription.php

- Fix some missing imports
- Split long code into many methods
- promote early return
- some clean-up on duplicate code
- some docblocks fixes

Some fixes / tweaks in Execution namepace

---

src/Execution/DataLoader/BatchLoader.php
src/Execution/DataLoader/ModelRelationFetcher.php
src/Execution/DataLoader/RelationBatchLoader.php
src/Execution/ErrorBuffer.php
src/Execution/MutationExecutor.php
src/Execution/QueryFilter.php
src/GraphQL.php
src/Schema/AST/PartialParser.php
src/Schema/Conversion/DefinitionNodeConverter.php
src/Schema/Directives/BaseDirective.php
src/Schema/Directives/Fields/RelationDirective.php
src/Schema/Extensions/SubscriptionExtension.php
src/Schema/Factories/DirectiveFactory.php
src/Schema/Factories/FieldFactory.php
src/Schema/NodeRegistry.php
src/Schema/Types/GraphQLSubscription.php
src/Subscriptions/Contracts/Broadcaster.php
src/Support/Contracts/CreatesContext.php
src/Support/Utils.php
tests/Unit/Schema/Directives/BaseDirectiveTest.php

Fix some docblocks and apply consistant style
**Changes**

Fix some docblocks and apply consistant style

---

.travis.yml
composer.json
tests/DBTestCase.php
tests/Integration/GraphQLTest.php
tests/Integration/Schema/Directives/Args/QueryFilterDirectiveTest.php
tests/Integration/Schema/Directives/Args/SearchDirectiveTest.php
tests/Integration/Schema/Directives/Fields/BelongsToManyDirectiveTest.php
tests/Integration/Schema/Directives/Fields/BelongsToTest.php
tests/Integration/Schema/Directives/Fields/HasManyDirectiveTest.php
tests/Integration/Schema/Directives/Fields/WithDirectiveTest.php
tests/Integration/Schema/Source/SchemaSourceProviderTest.php
tests/Integration/Subscriptions/BroadcastManagerTest.php
tests/Integration/Subscriptions/StorageManagerTest.php
tests/Integration/Subscriptions/SubscriptionTest.php
tests/Integration/Support/DataLoader/ModelRelationLoaderPolymorphicTest.php
tests/Integration/Support/DataLoader/ModelRelationLoaderTest.php
tests/TestCase.php
tests/Unit/Execution/Utils/SubscriptionTest.php
tests/Unit/Schema/AST/SchemaStitcherTest.php
tests/Unit/Schema/Directives/Args/RulesDirectiveTest.php
tests/Unit/Schema/Factories/NodeFactoryTest.php
tests/Unit/Subscriptions/Iterators/SyncIteratorTest.php

Provide support for Laravel 5.8
**Changes**
No

Provide support for Laravel 5.8

---

src/Schema/AST/DocumentAST.php
src/Schema/Directives/Fields/LazyLoadDirective.php
src/Schema/Directives/Fields/TracingDirective.php
src/Schema/Extensions/ExtensionRegistry.php
src/Schema/Extensions/GraphQLExtension.php
src/Schema/Types/NotFoundSubscription.php
src/Subscriptions/Exceptions/UnauthorizedSubscriber.php
src/Support/Contracts/ArgDirective.php
src/Support/Contracts/ArgDirectiveForArray.php
src/Support/NoValue.php
tests/Integration/Subscriptions/BroadcastManagerTest.php
tests/TestCase.php
tests/Unit/Schema/Execution/ContextFactoryTest.php
tests/Unit/Schema/Factories/DirectiveFactoryTest.php
tests/Unit/Schema/Types/Scalars/DateTest.php
tests/Utils/InterfacesSecondary/Bar.php
tests/Utils/Models/Closure.php
tests/Utils/ModelsSecondary/Category.php
tests/Utils/ModelsSecondary/OnlyHere.php

Comment empty statements and add missing imports.
**Changes**

Comment empty statements and add missing imports.

---

src/Schema/Directives/Fields/TracingDirective.php
src/Schema/Factories/FieldFactory.php
src/Schema/Factories/NodeFactory.php
src/Support/helpers.php

Always use `app()` helper, as `resolve()` is just an alias.
**Changes**

Always use app() helper.

---

src/Schema/AST/ASTHelper.php
src/Schema/Factories/DirectiveFactory.php
src/Schema/Factories/FieldFactory.php
src/Schema/Factories/NodeFactory.php
src/Subscriptions/Subscriber.php
src/Subscriptions/SubscriptionRegistry.php
tests/Integration/Subscriptions/BroadcastManagerTest.php
tests/Integration/Subscriptions/HandlesSubscribers.php
tests/Unit/Execution/Utils/SubscriptionTest.php
tests/Unit/Schema/Directives/BaseDirectiveTest.php
tests/Unit/Schema/Directives/Fields/CanDirectiveTest.php
tests/Unit/Schema/Directives/Fields/MethodDirectiveTest.php
tests/Unit/Schema/Execution/ContextFactoryTest.php
tests/Unit/Schema/Extensions/GraphQLExtensionTest.php
tests/Unit/Schema/Extensions/RequestsStreamedResponses.php
tests/Unit/Schema/Factories/DirectiveFactoryTest.php
tests/Unit/Schema/Types/Scalars/DateTest.php
tests/Unit/Subscriptions/Iterators/SyncIteratorTest.php

Stay consistant with Laravel style and remove useless braces with new.
**Changes**

Remove useless braces with new.

---

src/Schema/Types/Scalars/Date.php
src/Schema/Types/Scalars/DateTime.php
src/Subscriptions/Authorizer.php
src/Subscriptions/Iterators/SyncIterator.php
src/Support/Http/Responses/ResponseStream.php

Import caught exceptions.
**Changes**

Import caught exceptions.

---

src/Schema/Directives/Fields/MiddlewareDirective.php
src/Schema/Factories/FieldFactory.php
src/Schema/NodeRegistry.php
src/Subscriptions/BroadcastManager.php
tests/Unit/Schema/Extensions/TracingExtensionTest.php

Some codstyle fixes
**Changes**

Some codstyle fixes

---

tests/Unit/Schema/Types/Scalars/DateTimeTest.php

Avoid braces on new.
**Changes**

Avoid braces on new.

---

src/Schema/Factories/FieldFactory.php
src/Schema/Factories/NodeFactory.php
src/Support/Http/Responses/ResponseStream.php
src/Support/helpers.php
tests/Integration/Schema/Source/SchemaSourceProviderTest.php
tests/Unit/Schema/Extensions/GraphQLExtensionTest.php
tests/Unit/Schema/Factories/DirectiveFactoryTest.php
tests/Unit/Schema/Values/FieldValueTest.php
tests/Unit/Subscriptions/Iterators/SyncIteratorTest.php

Some code fixes.

---

docs/pages/resources.md

- [x ] Added Docs for all relevant versions
None
**Changes**
Added a tutorial about using API auth in Lighthouse. Also covers topics about custom directives and resolvers.
None

Add an article to the resources tab

---

.gitignore
tests/Integration/GraphQLTest.php
tests/Unit/Schema/Factories/DirectiveFactoryTest.php

Fix PHPUnit 8 depreciation warnings.
**Changes**

Fix PHPUnit 8 depreciation warnings.

---

.gitignore
tests/Integration/GraphQLTest.php
tests/Unit/Schema/Factories/DirectiveFactoryTest.php

Revert "[WIP] Fix PHPUnit 8 depreciation warnings."

---

docs/master/api-reference/directives.md
docs/master/guides/error-handling.md
docs/master/sidebar.js
docs/master/the-basics/fields.md
src/GraphQL.php

Add docs for error handling

---

src/Schema/Directives/Fields/PaginationManipulator.php
src/Schema/Directives/Nodes/GroupDirective.php

Simplify return.

---

src/Support/DriverManager.php
tests/Integration/Schema/Directives/Fields/CreateDirectiveTests/CoreTest.php
tests/Unit/Execution/Utils/SubscriptionTest.php

Add missing imports.

---

src/Tracing/Tracing.php
src/Tracing/TracingDirective.php

Fix tracing precision

---

docs/master/api-reference/directives.md
src/Schema/Directives/BaseDirective.php
src/Schema/Directives/Fields/CanDirective.php
tests/Unit/Schema/Directives/Fields/CanDirectiveDbTest.php
tests/Utils/Policies/AuthServiceProvider.php
tests/Utils/Policies/PostPolicy.php
tests/Utils/Policies/UserPolicy.php

Enable passing model instance to determine if a user is authorized to perform a given action on this model.
Resolves https://github.com/nuwave/lighthouse/issues/244
**Changes**
Check if an ID is passed in the query when `@can` directive is given.
No breaking changes to my knowledge.

Enable passing in model instance to @can directive

---

src/Schema/Directives/Fields/PaginateDirective.php

Properly namespace the model class in the PaginateDirective

---

.gitattributes
.github/CONTRIBUTING.md
Dockerfile
Dockerfile_xdebug
docker-compose.yml

Change the docker-compose dev setup to a self-contained, php 7.2 based build

---

.github/CONTRIBUTING.md

Thanks @lucasmichot for the regexes :)

Add rule about how to reference class names

---

src/Schema/Types/Scalars/Date.php
src/Schema/Types/Scalars/DateTime.php

Fix more docblocks.
**Changes**

Fix more docblocks.

---

.github/CONTRIBUTING.md
src/Schema/Factories/NodeFactory.php

Fix param docblocks.
**Changes**

Fix param docblocks.

---

composer.json

Add composer homepage details
Also fix a typo
**Changes**

Add composer homepage details

---

src/Subscriptions/Broadcasters/LogBroadcaster.php

Remove useless key check. `Arr::get` method already checks this
**Changes**

Remove useless key check.

---

src/GraphQL.php
tests/Integration/Schema/Directives/Fields/BelongsToTest.php
tests/Unit/Schema/AST/ASTHelperTest.php

Fix some typos.

---

tests/Integration/Schema/Directives/Fields/TrimDirectiveTest.php

Add tests for trim directive.
**Changes**

Add tests for trim directive.

---

tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php
tests/Integration/Execution/MutationExecutor/BelongsToTest.php
tests/Integration/Execution/MutationExecutor/HasManyTest.php
tests/Integration/Execution/MutationExecutor/HasOneTest.php
tests/Integration/Execution/MutationExecutor/MorphManyTest.php
tests/Integration/Execution/MutationExecutor/MorphOneTest.php
tests/Integration/Execution/MutationExecutor/MorphToTest.php

Fix setup visibility.
**Changes**

Fix setup visibility.

---

CHANGELOG.md
docs/master/api-reference/directives.md
src/GraphQL.php
src/Schema/Directives/Fields/CacheDirective.php
src/Schema/Directives/Fields/EventDirective.php
tests/Integration/Schema/Directives/Fields/EventDirectiveTest.php
tests/Integration/Schema/Directives/Fields/Fixtures/CompanyWasCreatedEvent.php

The `fire` method has been deprecated for quite some times. It's better to use `dispatch`.
This PR also adds `@event` tests.
**Changes**

Add event dispatch + tests.

---

src/LighthouseServiceProvider.php
src/Subscriptions/ExceptionHandler.php
src/Support/Contracts/SubscriptionExceptionHandler.php

Add some missing imports.
**Changes**

Add some missing imports.

---

src/Subscriptions/Broadcasters/LogBroadcaster.php
src/Subscriptions/Contracts/Broadcaster.php
src/Subscriptions/Contracts/BroadcastsSubscriptions.php
src/Subscriptions/Contracts/StoresSubscriptions.php
src/Subscriptions/Contracts/SubscriptionIterator.php
src/Subscriptions/Events/BroadcastSubscriptionListener.php
src/Support/Contracts/SubscriptionExceptionHandler.php
tests/Integration/Defer/SetUpDefer.php
tests/Integration/Schema/Types/UnionTest.php
tests/TestCase.php
tests/Unit/Schema/Directives/CanDirectiveDbTest.php
tests/Unit/Schema/Directives/CanDirectiveTest.php
tests/Unit/Schema/Directives/MiddlewareDirectiveTest.php
tests/Unit/Schema/Types/Scalars/DateTest.php
tests/Unit/Schema/Types/Scalars/DateTimeTest.php

Add missing `@return void` docblocks.
**Changes**

Add missing return void docblocks.

---

config/config.php

Do not import class in config.php.
Laravel import class everywhere *but* in configuration files.
**Changes**

Do not import class in configuration.

---

src/Subscriptions/Broadcasters/LogBroadcaster.php
src/Subscriptions/Events/BroadcastSubscriptionListener.php
src/Subscriptions/SubscriptionRegistry.php
tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php
tests/Integration/Schema/Directives/CacheDirectiveTest.php
tests/Unit/Schema/Directives/OrderByDirectiveTest.php

Add missing void type-hint.
**Changes**

Add missing void type-hint.

---

src/Support/Http/Middleware/AcceptJson.php

Import Closure and add docblock in `\Nuwave\Lighthouse\Support\Http\Middleware\AcceptJson`
**Changes**

Import Closure and add docblock.

---

src/Execution/ExtensionErrorHandler.php

Remove useless check.
**Changes**

Remove useless check.

---

src/LighthouseServiceProvider.php
src/Schema/Factories/FieldFactory.php
tests/Unit/Schema/ResolverProviderTest.php

Remove useless parenthesis.
**Changes**

Remove useless parenthesis.

---

src/Subscriptions/Contracts/StoresSubscriptions.php

Remove  useless import.
**Changes**

Remove  useless import.

---

tests/Integration/Defer/DeferDBTest.php
tests/Integration/Defer/DeferTest.php
tests/Integration/Events/BuildSchemaStringTest.php
tests/Integration/MultipleRequestsTest.php
tests/Integration/Schema/Directives/BuilderDirectiveTest.php
tests/Integration/Schema/Directives/CacheDirectiveTest.php
tests/Integration/Schema/Types/InterfaceTest.php
tests/Integration/Schema/Types/UnionTest.php
tests/Integration/Subscriptions/SubscriptionTest.php
tests/TestCase.php
tests/Unit/Execution/Utils/SubscriptionTest.php
tests/Unit/Schema/ClientDirectiveTest.php
tests/Unit/Schema/Directives/BcryptDirectiveTest.php
tests/Unit/Schema/Directives/CanDirectiveDbTest.php
tests/Unit/Schema/Directives/CanDirectiveTest.php
tests/Unit/Schema/Directives/ComplexityDirectiveTest.php
tests/Unit/Schema/Directives/InjectDirectiveTest.php
tests/Unit/Schema/Directives/RenameDirectiveTest.php
tests/Unit/Schema/Directives/RulesDirectiveTest.php
tests/Unit/Schema/Execution/ContextFactoryTest.php

Factorise tests resolvers
**Changes**

Add helper to TestCase to get  a fully qualified reference to a method that is defined on the test class

---

docs/2.6/getting-started/configuration.md
docs/2.6/getting-started/installation.md
docs/3.0/getting-started/configuration.md
docs/3.0/getting-started/installation.md
docs/3.0/guides/file-uploads.md
docs/3.1/getting-started/configuration.md
docs/3.1/getting-started/installation.md
docs/3.1/guides/file-uploads.md
docs/3.2/getting-started/configuration.md
docs/3.2/getting-started/installation.md
docs/3.2/guides/file-uploads.md
docs/3.3/getting-started/configuration.md
docs/3.3/getting-started/installation.md
docs/3.3/guides/file-uploads.md
docs/3.4/getting-started/configuration.md
docs/3.4/getting-started/installation.md
docs/3.4/guides/file-uploads.md
docs/3.5/getting-started/configuration.md
docs/3.5/getting-started/installation.md
docs/3.5/guides/file-uploads.md
docs/3.6/getting-started/configuration.md
docs/3.6/getting-started/installation.md
docs/3.6/guides/file-uploads.md
docs/master/getting-started/configuration.md
docs/master/getting-started/installation.md
docs/master/guides/file-uploads.md

**Changes**
Replace sh with bash in docs annotations.

Replace sh with bash and remove the leading $

---

docs/master/guides/validation.md

https://github.com/nuwave/lighthouse/issues/794

Enhance docs around validating arguments for uniqueness

---

CHANGELOG.md
docs/master/api-reference/directives.md
src/Schema/Directives/GlobalIdDirective.php
tests/Unit/Schema/Directives/GlobalIdDirectiveTest.php

Add option `decode` to `@globaldId` to control the result of decoding

---

docs/pages/resources.md

Added a link to my Lighthouse-client for Angular.

Added Buoy to the resources-page

---

src/Schema/Directives/CreateDirective.php
src/Schema/Directives/UpdateDirective.php

**Changes**
Remove useless braces when newing an object.

Remove useless braces when newing an object.

---

src/Execution/Builder.php
src/Schema/Directives/NeqDirective.php

Fix doxblock spacing.
**Changes**

Fix doxblock spacing.

---

src/Execution/DataLoader/ModelRelationFetcher.php

**Changes**
Remove useless comment.

Remove useless comment.

---

.travis.yml

Get that performance visibility.

Run benchmarks in travis

---

docs/3.7/sidebar.js
docs/master/sidebar.js

Hi! I think it is missed from the sidebar.
None
**Changes**
Added a reference into sidebar to the file `subscriptions/client-implementations`.
None

Add Client Implementations to Subscriptions menu

---

CHANGELOG.md
src/Execution/MutationExecutor.php

Make nested mutations work with subclassed relationship types

---

phpunit.xml.dist

n/a
**Changes**
Only updated `phpunit.xml.dist`
None

phpunit: remove file not present anymore

---

CHANGELOG.md
src/LighthouseServiceProvider.php
src/Subscriptions/SubscriptionServiceProvider.php
tests/TestCase.php

Use config repository contract

---

docs/master/the-basics/fields.md

Spelling mistake corrected

---

docs/master/the-basics/types.md

For a better understanding of @input directive associated with @spread directive

input directive example updated

---

docs/master/eloquent/nested-mutations.md

isn't it supposed to be @update instead of @create ?

Fix BelongsToMany example in nested mutation docs

---

docs/master/eloquent/getting-started.md

I've heard several examples of new users being confused about why their `@create` and `@update` directives are not working and a common problem is not having put the fields into their `$fillable` list to allow mass assignment.

Added disclaimer about mass assignment

---

docs/master/api-reference/directives.md
src/Schema/Directives/CacheDirective.php
src/Schema/Values/CacheValue.php

Simplified and commented the code to make it more readable.

Refactor caching for simplicity

---

docs/pages/resources.md

Added the alternative test package to our resources 
[marvinrabe/laravel-graphql-test](https://github.com/marvinrabe/laravel-graphql-test)

[Docs]: Add marvinrabe/laravel-graphql-test package to resources

---

docs/3.7/security/validation.md

Documents Issue #812 
**Changes**
Documentation updated
Non

Add Custom Validation Rules to Doc

---

docs/.vuepress/enhanceApp.js
docs/INDEX.md

Add missing route for Eloquent section from home page.

[docs] Fix route from home page

---

docs/3.7/api-reference/directives.md

[docs]: Fix `@union` example

---

docs/4.0/testing/phpunit.md
docs/master/testing/phpunit.md

**Changes**
`quite` repeated in testing docs

Update phpunit.md: `quite` repeated

---

src/Schema/Directives/MorphToDirective.php

Define MorphToDirective

---

CHANGELOG.md
docs/master/api-reference/directives.md
docs/master/eloquent/polymorphic-relationships.md
src/Schema/Directives/BelongsToManyDirective.php
src/Schema/Directives/HasManyDirective.php
src/Schema/Directives/MorphManyDirective.php
src/Schema/Directives/MorphOneDirective.php
tests/Integration/Schema/Directives/MorphManyDirectiveTest.php
tests/Integration/Schema/Directives/MorphOneDirectiveTest.php

Add `@morphOne` and `@morphMany` directives. #332
None

Add @morphOne and @morphMany directives

---

.travis.yml
composer.json

Leverage https://github.com/localheinz/composer-normalize
I applied autoformatting and added a check to CI.

composer normalize

---

src/Schema/AST/ASTBuilder.php
src/Schema/AST/ASTHelper.php
src/Schema/Directives/CacheDirective.php
src/Schema/Directives/MiddlewareDirective.php
tests/Unit/Schema/AST/ASTHelperTest.php
tests/Unit/Schema/Directives/BcryptDirectiveTest.php

Simplify ASTHelper and add firstByName method

---

docs/3.7/api-reference/directives.md
docs/4.0/api-reference/directives.md
docs/4.1/api-reference/directives.md
docs/4.2/api-reference/directives.md
docs/4.3/api-reference/directives.md
docs/4.4/api-reference/directives.md
docs/4.5/api-reference/directives.md
docs/master/api-reference/directives.md
src/Schema/Directives/InjectDirective.php

**Changes**
Fixes incorrectly listed directive location for `@inject`.
None

Fix incorrect directive location for @inject

---

docs/tutorial/README.md

`User!` was used on line 328, so I assume line 43 was a mistake.
**Changes**
Edit in GraphQL example.
None

Change type in example

---

CHANGELOG.md
src/Schema/ResolverProvider.php

Resolves #1044
**Changes**
The new error message mentions how to fix the mistake.
No.

Improve the error message for missing field resolvers by offering a solution

---

docs/master/api-reference/directives.md
src/Schema/Directives/ScopeDirective.php

**Changes**
Adds INPUT_FIELD_DEFINITION to the scope directive.
None.

Add INPUT_FIELD_DEFINITION to scope directive

---

CHANGELOG.md
docs/3.7/api-reference/directives.md
docs/4.0/api-reference/directives.md
docs/4.1/api-reference/directives.md
docs/4.2/api-reference/directives.md
docs/4.3/api-reference/directives.md
docs/4.4/api-reference/directives.md
docs/4.5/api-reference/directives.md
docs/4.6/api-reference/directives.md
docs/master/api-reference/directives.md
src/Schema/Directives/EnumDirective.php
src/Schema/TypeRegistry.php

Resolves https://github.com/nuwave/lighthouse/issues/1077
**Changes**
Now it shows up in `schema-directives.graphql` and can potentially be overwritten.
No.

Define `@enum` as a directive class

---

docs/master/custom-directives/argument-directives.md
src/Schema/Directives/BaseDirective.php
src/Schema/Directives/CanDirective.php
src/Schema/Directives/CountDirective.php
src/Schema/Directives/EqDirective.php
src/Schema/Directives/InDirective.php
src/Schema/Directives/MethodDirective.php
src/Schema/Directives/ModifyModelExistenceDirective.php
src/Schema/Directives/NeqDirective.php
src/Schema/Directives/NotInDirective.php
src/Schema/Directives/RelationDirective.php
src/Schema/Directives/ScopeDirective.php
src/Schema/Directives/WhereBetweenDirective.php
src/Schema/Directives/WhereDirective.php
src/Schema/Directives/WhereJsonContainsDirective.php
src/Schema/Directives/WhereNotBetweenDirective.php
src/Schema/Directives/WithDirective.php

This is an internal refactoring PR.

Improve type safety in BaseDirective.php and add `nodeName()` helper

---

docs/master/digging-deeper/extending-lighthouse.md

This is a pure documentation update.

Document how to use a custom `GraphQLContext`

---

docs/master/security/validation.md

**Changes**
Doc changes only. No behavioral changes.
Field validation example was missing the `@update` directive for the mutation schema. Verified the change as necessary and working with a a similar mutation schema in my own project.
None.

Docs - Corrected field validation example

---

tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php

This is just an extra test in search of a possible bug described in https://github.com/nuwave/lighthouse/issues/1080.

Add test for renaming @belongsToMany relations

---

CHANGELOG.md
docs/master/api-reference/directives.md
src/OrderBy/OrderByServiceProvider.php
src/Pagination/PaginationManipulator.php
src/Schema/AST/ASTBuilder.php
src/SoftDeletes/SoftDeletesServiceProvider.php
src/WhereConstraints/SQLOperator.php
src/WhereConstraints/WhereConstraintsServiceProvider.php

Resolves #1123
**Changes**
This PR only adds some missing descriptions to the schema definition. No changes to the behavior of the library.
There are no breaking changes.

Add missing descriptions to generated and built-in schema types

---

docs/master/api-reference/directives.md
src/Execution/DataLoader/BatchLoader.php
src/Execution/DataLoader/RelationBatchLoader.php
src/Support/Http/Responses/MemoryStream.php
src/Support/Http/Responses/ResponseStream.php
src/Support/Http/Responses/Stream.php

See https://github.com/nuwave/lighthouse/issues/772
This replaces some parts where `Collection` classes are just temporarily instantiated.

Use array functions instead of short-lived Collection instances

---

UPGRADE.md

Add upgrade guide for `@modelClass` and `@model` in v5

---

Makefile

Resolves https://github.com/nuwave/lighthouse/issues/1152
Thanks @chescos for noticing!

Fix running make before first composer install

---

docs/master/eloquent/complex-where-conditions.md

Related to #1151 
**Changes**
Added detailed description how to create and register custom operator implementation for `@whereConditions`
no

Improve docs on how to register a custom operator for `@whereConditions`

---

docs/master/api-reference/directives.md
docs/master/security/sanitization.md
docs/master/sidebar.js
src/Schema/Directives/RulesDirective.php

See https://github.com/nuwave/lighthouse/pull/1165
I added a section about sanitization to offer an alternative.

Document that mutating arguments in validation is not supported

---

CHANGELOG.md
README.md
docs/.vuepress/config.js

Resolves https://github.com/nuwave/lighthouse/issues/1128

Link CHANGELOG.md and UPGRADE.md in docs page

---

docs/master/digging-deeper/adding-types-programmatically.md

Document schema stitcher usage

---

CHANGELOG.md

Remove release comparison links, GitHub does it better

---

tests/Integration/Schema/Directives/PaginateDirectiveDBTest.php
tests/Utils/Models/User.php

Add test to ensure https://github.com/nuwave/lighthouse/issues/1196 is not an issue within Lighthouse:

Test `@paginate` with `scopes`

---

docs/master/eloquent/nested-mutations.md

**Changes**
Fixing typo in documentation.

Fix typo in nested mutation docs

---

docs/3.6/guides/relationships.md

Removed dubble ``input CreateAuthorInput`` and added the ``input UpdateAuthorInput``

Replace duplicate `CreateAuthorInput` in docs with `UpdateAuthorInput`

---

CHANGELOG.md
src/Support/AppVersion.php

Fix Lumen version check

---

.github/workflows/continuous-integration.yml
phpstan.neon
tests/Integration/Schema/Types/LaravelEnumTypeDBTest.php
tests/Unit/Schema/Types/LaravelEnumTypeTest.php

It is now compatible with Laravel 7.

Reenable CI for bensampo/laravel-enum

---

CHANGELOG.md
src/Subscriptions/SubscriptionRouter.php

Ensure subscription routes are named uniquely

---

docs/master/testing/phpunit.md

Fix missing comma in testing docs

---

docs/2.6/getting-started/configuration.md
docs/3.0/getting-started/configuration.md
docs/3.1/getting-started/configuration.md
docs/3.2/getting-started/configuration.md
docs/3.3/getting-started/configuration.md
docs/3.4/getting-started/configuration.md
docs/3.5/getting-started/configuration.md
docs/3.6/getting-started/configuration.md
docs/3.7/getting-started/configuration.md
docs/4.0/getting-started/configuration.md
docs/4.1/getting-started/configuration.md
docs/4.10/getting-started/configuration.md
docs/4.11/getting-started/configuration.md
docs/4.2/getting-started/configuration.md
docs/4.3/getting-started/configuration.md
docs/4.4/getting-started/configuration.md
docs/4.5/getting-started/configuration.md
docs/4.6/getting-started/configuration.md
docs/4.7/getting-started/configuration.md
docs/4.8/getting-started/configuration.md
docs/4.9/getting-started/configuration.md
docs/master/getting-started/configuration.md

Resolves https://github.com/nuwave/lighthouse/issues/1266

Document how to configure CORS

---

tests/Integration/Defer/DeferDBTest.php
tests/Integration/Defer/DeferTest.php

**Changes**
Use proper assertions.

Use assertContains where appropriate

---

tests/Integration/Schema/Directives/EventDirectiveTest.php
tests/Integration/Schema/Directives/Fixtures/CompanyWasCreatedEvent.php
tests/Unit/Execution/Arguments/ArgPartitionerTest.php
tests/Unit/Execution/Arguments/Fixtures/Nested.php
tests/Unit/Schema/Directives/Fixtures/Foo.php
tests/Unit/Schema/Directives/MethodDirectiveTest.php

**Changes**
Extract tests for fixtures.

Extract test class definitions to separate fixture files

---

src/Console/IdeHelperCommand.php
src/LighthouseServiceProvider.php
src/Schema/Directives/RelationDirective.php
tests/TestCase.php

**Changes**
Simplify some conditions.
**Notes**
Not sure why https://codecov.io/gh/nuwave/lighthouse/compare/ee7fd652e0a2c457b7b91be832a28247678bf306...1bde9b52b58f0ef3593e4429de271c906eceba21 fails.
But still feel it brings clarity and is valuable to merge.

Remove unnecessary else blocks

---

src/Defer/Defer.php
src/Schema/Directives/CacheDirective.php
src/Schema/Directives/LazyLoadDirective.php
src/Support/Http/Responses/ResponseStream.php

**Changes**
Remove useless braces.

Remove useless braces

---

CHANGELOG.md
src/Subscriptions/SubscriptionRegistry.php

**Changes**
Instead of concrete implementation typehint the contract allowing us to replace it.
None, unless `SubscriptionRegistry->__construct` was extended by the user.

Type hint StoresSubscription instead of implementation

---

src/Subscriptions/SubscriptionBroadcaster.php

I missed one reference in PR #1286, this fixes that.

Fix missed use of subscription contract

---

docs/master/security/authorization.md

Gives an example on how to solve #1293
**Changes**
Added an additional section to `Security`->`Authorization`, that describes with an example, how to protect particular fields (in most cases model attributes) and return `null`, if user has no access to the field.
None

Add HowTo to docs: define custom field middleware to protect attributes

---

CHANGELOG.md
src/Schema/Directives/RulesDirective.php
src/Schema/Directives/RulesForArrayDirective.php

Resolves https://github.com/nuwave/lighthouse/issues/1304

Replace usage of `resolve()` helper with Lumen-compatible `app()`

---

src/Execution/Arguments/ArgumentSet.php
src/Execution/Arguments/ArgumentSetFactory.php
src/Schema/Factories/FieldFactory.php
src/Schema/TypeRegistry.php
tests/Unit/Execution/Arguments/ArgumentSetFactoryTest.php

Include `undefined` arguments within ArgumentSet

---

CHANGELOG.md
assets/default-schema.graphql
docs/3.0/api-reference/scalars.md
docs/3.1/api-reference/scalars.md
docs/3.2/api-reference/scalars.md
docs/3.3/api-reference/scalars.md
docs/3.4/api-reference/scalars.md
docs/3.5/api-reference/scalars.md
docs/3.6/api-reference/scalars.md
docs/3.7/api-reference/scalars.md
docs/4.0/api-reference/scalars.md
docs/4.1/api-reference/scalars.md
docs/4.10/api-reference/scalars.md
docs/4.11/api-reference/scalars.md
docs/4.2/api-reference/scalars.md
docs/4.3/api-reference/scalars.md
docs/4.4/api-reference/scalars.md
docs/4.5/api-reference/scalars.md
docs/4.6/api-reference/scalars.md
docs/4.7/api-reference/scalars.md
docs/4.8/api-reference/scalars.md
docs/4.9/api-reference/scalars.md
docs/master/api-reference/scalars.md
src/Schema/Types/Scalars/Date.php
src/Schema/Types/Scalars/DateScalar.php
src/Schema/Types/Scalars/DateTimeTz.php
tests/Unit/Schema/Types/Scalars/DateScalarTest.php
tests/Unit/Schema/Types/Scalars/DateTest.php
tests/Unit/Schema/Types/Scalars/DateTimeTest.php
tests/Unit/Schema/Types/Scalars/DateTimeTzTest.php

Resolves https://github.com/nuwave/lighthouse/issues/1255
**Changes**
Add an ISO 8601 formatted scalar `DateTimeTz`.
No

Add scalar `DateTimeTz`

---

CHANGELOG.md
docs/master/testing/phpunit.md
src/Console/IdeHelperCommand.php
src/LighthouseServiceProvider.php
tests/Integration/Console/IdeHelperCommandTest.php

Publish `_lighthouse_ide_helper.php` with `artisan lighthouse:ide-helper`

---

docs/master/security/authentication.md

Hi, thank you for the wonderful library.
Based on the following thread, it is highly common usecase to use lighthouse with Laravel Sanctum, so this section would be helpful especially for beginners.
https://github.com/nuwave/lighthouse/issues/1190
Hope this helps.
**Changes**

Add docs on using `@guard` with Sanctum

---

CHANGELOG.md
src/Testing/MakesGraphQLRequests.php

Resolves https://github.com/nuwave/lighthouse/issues/1173

Allow passing additional headers to multipartGraphQL test helper

---

CHANGELOG.md
src/LighthouseServiceProvider.php

Fix publishing the config when using Lumen

---

CHANGELOG.md
UPGRADE.md
src/Support/Contracts/DefinedDirective.php

- ~[ ] Added or updated tests~
Resolves https://github.com/nuwave/lighthouse/issues/1383
**Changes**
Document why `DefinedDirective` is deprecated.
Not yet, will land in https://github.com/nuwave/lighthouse/pull/1386

Clarify DefinedDirective deprecation

---

src/ClientDirectives/ClientDirectiveFactory.php
src/GraphQL.php
src/Schema/Directives/BaseDirective.php
src/Schema/Directives/DeleteDirective.php
src/Subscriptions/Subscriber.php
src/Support/Http/Middleware/AttemptAuthentication.php
src/Support/Http/Responses/MemoryStream.php
src/Support/Http/Responses/ResponseStream.php
src/Testing/MakesGraphQLRequests.php
src/Testing/MakesGraphQLRequestsLumen.php
src/Testing/TestResponseMixin.php
src/WhereConditions/SQLOperator.php

Fix phan issues

---

docs/master/eloquent/getting-started.md

Example added to demonstrate how to use local scopes with a query

Document how to use Model scopes from directives

---

docs/4.0/api-reference/directives.md
docs/4.1/api-reference/directives.md
docs/4.10/api-reference/directives.md
docs/4.11/api-reference/directives.md
docs/4.12/api-reference/directives.md
docs/4.13/api-reference/directives.md
docs/4.14/api-reference/directives.md
docs/4.2/api-reference/directives.md
docs/4.3/api-reference/directives.md
docs/4.4/api-reference/directives.md
docs/4.5/api-reference/directives.md
docs/4.6/api-reference/directives.md
docs/4.7/api-reference/directives.md
docs/4.8/api-reference/directives.md
docs/4.9/api-reference/directives.md
docs/master/api-reference/directives.md
src/Schema/Directives/CanDirective.php

https://github.com/nuwave/lighthouse/issues/1435

Document clearly that `@can` uses primary keys in `find`

---

CHANGELOG.md
src/Support/Http/Middleware/AcceptJson.php
src/Support/Http/Middleware/AttemptAuthentication.php
src/Support/Http/Middleware/LogGraphQLQueries.php
src/lighthouse.php
tests/TestsSerialization.php
tests/Unit/Support/Http/Middleware/AcceptJsonTest.php
tests/Unit/Support/Http/Middleware/LogGraphQLQueriesTest.php

**Changes**
Something i use in a few projects and found generally useful.
No.

Add middleware to log incoming GraphQL queries

---

docs/master/api-reference/directives.md

imagable => imageable
**Changes**
Fix typo in docs

Fix typo in docs

---

docs/tutorial/README.md

[old]
Tag: config
Tag: schema
[new] 
Tag: lighthouse-config
Tag: lighthouse-schema
**Changes**

Fix publish command in tutorial docs

---

docs/tutorial/README.md

Model names are singular
**Changes**

Use singular model name in tutorial

---

docs/4.16/getting-started/installation.md

This simply corrects the command in the docs to work.

docs: correct the lighthouse-schema command

---

docs/4.13/api-reference/directives.md
docs/4.14/api-reference/directives.md
docs/4.15/api-reference/directives.md
docs/4.16/api-reference/directives.md
docs/master/api-reference/directives.md
src/Schema/Directives/MorphManyDirective.php

**Changes**
changed **#one-to-one-polymorphic-relations** to **#manyto-one-polymorphic-relations**

Fixed the link corresponding to the MorphMany relationship

---

CHANGELOG.md
src/Schema/Factories/FieldFactory.php
src/lighthouse.php

Resolves https://github.com/nuwave/lighthouse/issues/1136
**Changes**
Instead of hardcoding them, this allows the user to add or remove global field middleware directives.
No

Allow configuring global field middleware directives

---

src/Pagination/PaginateDirective.php
src/Schema/Directives/BroadcastDirective.php
src/Schema/Directives/BuilderDirective.php

Avoid call_user_func*

---

src/Schema/Factories/FieldFactory.php
tests/Integration/FieldMiddlewareTest.php
tests/Utils/Directives/CustomFieldMiddlewareDirective.php

Resolves https://github.com/nuwave/lighthouse/issues/1535

Fix middleware directive order

---

docs/4.13/api-reference/scalars.md
docs/4.13/digging-deeper/file-uploads.md
docs/4.14/api-reference/scalars.md
docs/4.14/digging-deeper/file-uploads.md
docs/4.15/api-reference/scalars.md
docs/4.15/digging-deeper/file-uploads.md
docs/4.16/api-reference/scalars.md
docs/4.16/digging-deeper/file-uploads.md
docs/master/api-reference/scalars.md
docs/master/digging-deeper/file-uploads.md

Hey @spawnia 
a minor fix of broken links into the Laravel docs.
Cheers,
Peter

Fix broken links to Laravel docs

---

docs/users/README.md

Added Cinemas Cinemax

---

docs/master/getting-started/installation.md

Document how to enable service providers in Lumen

---

src/Console/stubs/typeResolver.stub

Just a missing use. Resolves #1599.
**Changes**
None.
None.

Add mising use to typeResolver stub

---

src/Schema/Directives/MorphToManyDirective.php
tests/Integration/Schema/Directives/MorphToManyDirectiveTest.php

See #332 
**Changes**
None.
None.

Add @morphToMany directive

---

docs/master/custom-directives/getting-started.md
src/Console/DirectiveCommand.php
tests/Console/ValidateSchemaCommandTest.php
tests/Integration/Validation/RulesDirectiveTest.php

Resolves https://github.com/nuwave/lighthouse/issues/1609

Validate that artisan lighthouse:directive is called with at least one of --type, --field or --argument

---

CHANGELOG.md
docs/master/api-reference/scalars.md
src/Schema/Types/Scalars/DateTimeTz.php

Resolves https://github.com/nuwave/lighthouse/issues/1619

Use DateTime::ATOM for DateTimeTZ ISO 8601 compatibility

---

CHANGELOG.md
src/Schema/AST/ASTBuilder.php
tests/Unit/Schema/AST/ASTBuilderTest.php

Resolves #1634
**Changes**
Allows extending a type while adding an interface to it.

Merge type interfaces when extending type

---

CHANGELOG.md
composer.json
docs/3.6/api-reference/directives.md
docs/3.7/api-reference/directives.md
docs/4.0/api-reference/directives.md
docs/4.1/api-reference/directives.md
docs/4.10/eloquent/complex-where-conditions.md
docs/4.11/eloquent/complex-where-conditions.md
docs/4.12/eloquent/complex-where-conditions.md
docs/4.13/eloquent/complex-where-conditions.md
docs/4.14/eloquent/complex-where-conditions.md
docs/4.15/eloquent/complex-where-conditions.md
docs/4.16/eloquent/complex-where-conditions.md
docs/4.17/eloquent/complex-where-conditions.md
docs/4.18/eloquent/complex-where-conditions.md
docs/4.2/api-reference/directives.md
docs/4.3/api-reference/directives.md
docs/4.4/api-reference/directives.md
docs/4.5/api-reference/directives.md
docs/4.6/api-reference/directives.md
docs/4.7/api-reference/directives.md
docs/4.8/eloquent/complex-where-conditions.md
docs/4.9/eloquent/complex-where-conditions.md
docs/master/eloquent/complex-where-conditions.md
src/WhereConditions/WhereConditionsServiceProvider.php

Thank you to @Nozibulla for bringing this up in https://github.com/nuwave/lighthouse/pull/1638

Update to PHP 8 compatible mll-lab/graphql-php-scalars 4

---

CHANGELOG.md
composer.json
docs/master/api-reference/events.md
docs/master/api-reference/scalars.md
src/Events/StartExecution.php
src/Events/StartRequest.php
src/Schema/Directives/CacheDirective.php
src/Schema/Types/Scalars/Date.php
src/Schema/Types/Scalars/DateScalar.php
src/Schema/Types/Scalars/DateTime.php
src/Schema/Types/Scalars/DateTimeTz.php
src/Schema/Types/Scalars/DateTimeUtc.php
src/Subscriptions/StorageManager.php
src/Tracing/Tracing.php
tests/Unit/Schema/Types/Scalars/DateScalarTest.php
tests/Unit/Schema/Types/Scalars/DateTimeUtcTest.php
tests/Utils/Models/Activity.php
tests/Utils/Models/Category.php
tests/Utils/Models/Color.php
tests/Utils/Models/Comment.php
tests/Utils/Models/Company.php
tests/Utils/Models/Contractor.php
tests/Utils/Models/Employee.php
tests/Utils/Models/Image.php
tests/Utils/Models/Post.php
tests/Utils/Models/Product.php
tests/Utils/Models/Tag.php
tests/Utils/Models/Task.php
tests/Utils/Models/Team.php
tests/Utils/Models/User.php

Resolves #1623
**Changes**
Replace `Carbon\Carbon` with `Illuminate\Support\Carbon`
Might be some issues if you have extended methods.

Use Illuminate\Support\Carbon instead of Carbon\Carbon

---

CHANGELOG.md
src/Schema/Directives/ModelDirective.php
tests/Integration/Schema/Directives/CacheDirectiveTest.php

Resolves https://github.com/nuwave/lighthouse/issues/1657

Make `@model` not extend `@node` accidentally

---

docs/5.0/api-reference/directives.md
docs/master/api-reference/directives.md
src/Schema/Directives/BelongsToManyDirective.php

Follow up to https://github.com/nuwave/lighthouse/pull/1649

Fix docs for auxiliary directive definitions

---

docs/5.0/security/authentication.md

Fix typo in authentication docs

---

src/Subscriptions/Storage/RedisStorageManager.php
tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php

Fixes https://github.com/nuwave/lighthouse/pull/1685

Fix the fix for subscription TTL

---

CHANGELOG.md
docs/master/api-reference/directives.md
src/Schema/Directives/BuilderDirective.php
tests/Integration/Schema/Directives/BuilderDirectiveTest.php

Add field support for builder directive.
**Changes**
Adds field definition to builder directive.

Allow using the `@builder` directive on fields

---

CONTRIBUTING.md
Makefile
phpunit.xml.dist
tests/DBTestCase.php

**Changes**
Add some changes to make local development easier without the usage of a docker container.

Document local development setup with native tools

---

CHANGELOG.md
docs/master/api-reference/directives.md
docs/master/subscriptions/client-implementations.md
docs/master/subscriptions/getting-started.md
src/Subscriptions/SubscriptionRegistry.php
src/lighthouse.php
tests/Integration/Subscriptions/SubscriptionTest.php

**Changes**
This adds a more simplified response when creating subscriptions.
There shouldn't be any breaking changes as long as the subscriptions version 1 are used.

Subscriptions v2

---

tests/Integration/ErrorTest.php

https://github.com/nuwave/lighthouse/issues/1737

Add test to ensure exceptions are rethrown

---

CHANGELOG.md
docs/master/api-reference/directives.md
src/Schema/Directives/BuilderDirective.php
src/Schema/Directives/CanDirective.php
src/Schema/Directives/EnumDirective.php
src/Schema/Directives/EqDirective.php

**Changes**
Improves static validation and IDE editing experience.
No.

Define scalars instead of `Mixed` type in directive definitions

---

CHANGELOG.md
src/ClientDirectives/ClientDirective.php
src/Console/PrintSchemaCommand.php
src/Console/ValidateSchemaCommand.php
src/Execution/Utils/Subscription.php
src/GraphQL.php
src/LighthouseServiceProvider.php
src/Schema/AST/ASTBuilder.php
src/Schema/SchemaBuilder.php
src/Subscriptions/SubscriptionRegistry.php
src/Support/Http/Controllers/GraphQLController.php

**Changes**
Further reduce the responsibility of this class to focus solely on execution.
No.

Move HTTP and Schema handling out of the GraphQL class

---

CHANGELOG.md
src/Defer/Defer.php
src/GraphQL.php
src/Schema/AST/ASTBuilder.php
src/Schema/SchemaBuilder.php
src/Subscriptions/SubscriptionBroadcaster.php

**Changes**
Ensure that error handling and debug settings are always applied. In particular, broadcast results now apply the same, consistent error handling.
Some internals were shifted around.

Apply error handling and debug settings consistently

---

UPGRADE.md

**Changes**
Small documentation fix of getting an argument inside a validator in the UPGRADE.md file.

Fix documentation of getting an argument inside a validator in UPGRADE.md

---

docs/tutorial/README.md

Fix the tinker command for user factory
**Changes**

Fix the tinker command for user factory

---

docs/5.0/api-reference/directives.md
docs/5.1/api-reference/directives.md
docs/5.2/api-reference/directives.md
docs/5.3/api-reference/directives.md
docs/master/api-reference/directives.md

**Changes**
Correct wrong description of @paginate directive using CONNECTION type on [here](https://lighthouse-php.com/5.3/api-reference/directives.html#paginate).

Fix wrong docs of @paginate with CONNECTION type

---

CHANGELOG.md
_ide_helper.php
src/Testing/TestResponseMixin.php
tests/Integration/Defer/DeferTest.php
tests/Integration/ErrorTest.php
tests/Integration/Schema/Directives/CanDirectiveDBTest.php
tests/Integration/Schema/Directives/DeleteDirectiveTest.php
tests/Integration/Schema/Directives/ThrottleDirectiveTest.php
tests/Integration/Schema/Directives/UpdateDirectiveTest.php
tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
tests/Unit/Schema/Directives/CanDirectiveTest.php
tests/Unit/Schema/Directives/GuardDirectiveTest.php

```php
$this
->graphQL(/** @lang GraphQL */ '
{
shouldFail
}
')
->assertGraphQLErrorMessage('Expected error message.');
```

Add method `assertGraphQLErrorMessage()` to `TestResponse` mixin

---

CHANGELOG.md
src/Validation/RulesGatherer.php
tests/Integration/Validation/ValidationTest.php
tests/Utils/Validators/FooClosureValidator.php

Solves this issue https://github.com/nuwave/lighthouse/pull/1824#issuecomment-826706848

Fix usage of closures in validation

---

CHANGELOG.md
src/Scout/ScoutEnhancer.php
tests/Integration/Scout/SearchDirectiveTest.php

Resolves https://github.com/nuwave/lighthouse/issues/1852

Pass plain values to `ScoutBuilderDirective::handleScoutBuilder()`

---

CHANGELOG.md
composer.json
phpstan.neon
src/Defer/DeferServiceProvider.php
src/Execution/Arguments/ArgumentSetFactory.php
src/Execution/ContextFactory.php
src/Execution/ErrorPool.php
src/Execution/ValidationRulesProvider.php
src/GlobalId/GlobalIdServiceProvider.php
src/GraphQL.php
src/LighthouseServiceProvider.php
src/Schema/AST/ASTBuilder.php
src/Schema/AST/ASTHelper.php
src/Schema/Factories/FieldFactory.php
src/Subscriptions/Iterators/AuthenticatingSyncIterator.php
src/Subscriptions/Storage/CacheStorageManager.php
src/Subscriptions/SubscriptionServiceProvider.php
src/Support/Compatibility/LumenMiddlewareAdapter.php
src/Testing/MakesGraphQLRequests.php
src/Testing/MakesGraphQLRequestsLumen.php
src/Testing/TestingServiceProvider.php
src/Tracing/TracingServiceProvider.php
src/WhereConditions/WhereConditionsServiceProvider.php
tests/Console/CacheCommandTest.php
tests/Integration/ErrorTest.php
tests/Integration/ReportingErrorHandlerTest.php
tests/TestCase.php
tests/Unit/Schema/DirectiveLocatorTest.php
tests/Unit/Schema/Source/SchemaSourceProviderTest.php

Resolves https://github.com/nuwave/lighthouse/issues/1818
**Changes**
Fix problematic dependency injection patterns.
No.

Ensure compatibility with Laravel Octane

---

CHANGELOG.md
docs/5/api-reference/events.md
docs/master/api-reference/events.md
src/Events/EndExecution.php
src/Events/EndOperationOrOperations.php
src/Events/StartExecution.php
src/Events/StartOperationOrOperations.php
src/GraphQL.php
tests/Integration/LifecycleEventsTest.php

https://github.com/getsentry/sentry-laravel/pull/490/files#r636514647
**Changes**
Wraps lifecycle events around `GraphQL::executeOperationOrOperations()`
No.

Add lifecycle events `StartOperationOrOperations` and `EndOperationOrOperations`

---

composer.json
phpstan.neon
src/Schema/Directives/ScopeDirective.php

Blocked by https://github.com/phpstan/phpstan/issues/5150

Enable PHPStan bleeding edge config

---

CHANGELOG.md
src/Exceptions/ParseException.php
src/Schema/AST/DocumentAST.php
tests/Unit/Schema/AST/DocumentASTTest.php

Inspired by https://github.com/nuwave/lighthouse/issues/1189#issuecomment-879104099, resolves https://github.com/nuwave/lighthouse/issues/1189
**Changes**

Provide context for syntax errors

---

CHANGELOG.md
docs/5/security/validation.md
docs/master/security/validation.md
src/Support/Contracts/WithReferenceRule.php
tests/Integration/Validation/ValidationTest.php
tests/Utils/Rules/EqualFieldRule.php
tests/Utils/Validators/EqualFieldCustomRuleValidator.php

https://github.com/nuwave/lighthouse/pull/1903

Clean up with_references validation

---

CHANGELOG.md
docs/master/api-reference/directives.md
docs/master/security/authorization.md
phpunit.xml.dist
src/Schema/Directives/CanDirective.php
tests/Integration/Schema/Directives/CanDirectiveDBTest.php
tests/Integration/SoftDeletes/ForceDeleteDirectiveTest.php
tests/Integration/SoftDeletes/RestoreDirectiveTest.php
tests/Unit/Schema/Directives/CanDirectiveTest.php

Resolves https://github.com/nuwave/lighthouse/issues/1916

Add `query` and `scopes` arguments to the `@can` directive

---

CHANGELOG.md
src/Schema/Types/Scalars/DateScalar.php
tests/Unit/Schema/Types/Scalars/DateScalarTest.php

Resolves #1923 
**Changes**
Allows \Carbon\CarbonImmutable for date scalars

Allow \Carbon\CarbonImmutable for date scalars

---

CHANGELOG.md
src/Execution/Arguments/ArgumentSet.php
src/Schema/Directives/SpreadDirective.php
tests/Unit/Execution/Arguments/ArgumentSetTest.php
tests/Unit/Schema/Directives/SpreadDirectiveTest.php

Relates to https://github.com/nuwave/lighthouse/pull/1939

Apply `@spread` to inputs nested within lists

---

docs/4/testing/extensions.md
docs/5/testing/extensions.md
docs/master/testing/extensions.md

**Changes**
Fixing doc link break in testing/extension

Fix docs link in testing/extensions.md

---

CHANGELOG.md
src/Schema/Directives/RelationDirective.php
tests/DBTestCase.php
tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php
tests/Utils/Models/AlternateConnection.php
tests/Utils/Models/User.php
tests/database/factories/AlternateConnectionFactory.php
tests/database/migrations/2021_04_14_000000_create_testbench_alternate_connections_table.php

https://github.com/nuwave/lighthouse/pull/1945 with tests

Dont batchload relations with different database connections

---

CHANGELOG.md
docs/5/api-reference/directives.md
docs/5/digging-deeper/ordering.md
docs/master/eloquent/complex-where-conditions.md
src/Schema/TypeRegistry.php
src/WhereConditions/WhereConditionsBaseDirective.php
src/WhereConditions/WhereConditionsDirective.php
src/WhereConditions/WhereConditionsHandler.php
src/WhereConditions/WhereHasConditionsDirective.php
tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php

**Changes**
- Add ability to provide custom handler for `@whereConditions` and `@whereHasConditions`
None

Add ability to provide custom handler for `@whereConditions` and `@whereHasConditions`

---

docs/resources/README.md

Add Laracasts series to the Tutorials section.

---

composer.json

Resolves: #2021 
**Changes**
Add support for running both safe v1 and v2

Add support for safe v2

---

CHANGELOG.md
src/Execution/Arguments/ArgPartitioner.php
tests/Unit/Execution/Arguments/ArgPartitionerTest.php
tests/Utils/Models/User.php

Resolves https://github.com/nuwave/lighthouse/issues/2024

Fix partitioning of arguments where the model has a non-relation method returning primitive

---

CHANGELOG.md
composer.json
phpstan.neon
src/Console/LighthouseGeneratorCommand.php
src/Exceptions/ParseException.php
src/Schema/Types/LaravelEnumType.php
src/Schema/Values/CacheKeyAndTags.php

https://github.com/nuwave/lighthouse/issues/2027

Ensure compatibility with thecodingmachine/safe:2

---

CHANGELOG.md
src/default-schema.graphql
tests/Integration/DefaultSchemaTest.php
tests/Integration/Execution/ArgBuilderDirectiveTest.php
tests/Utils/Models/User.php
tests/database/migrations/2018_02_28_000002_create_testbench_users_table.php

Removes dependence on optional features, see https://github.com/nuwave/lighthouse/pull/2030#discussion_r786981293
**Changes**
- Improve default schema
None, the schema is published once.

Improve default schema

---

docs/5/performance/query-caching.md

**Changes**
Just some documentation changes that came up over the last weeks using query caching.

Improve query caching docs

---

CHANGELOG.md
src/Schema/Directives/RelationDirective.php
src/lighthouse.php
tests/Integration/Schema/Directives/BelongsToDirectiveTest.php
tests/database/factories/CompanyFactory.php
tests/database/migrations/2018_02_28_000000_create_testbench_companies_table.php

**Changes**
For now this PR only include a failing unit test to describe issue exposed in #2033 
No

 Fix relationship query shortcut on renamed id field

---

docs/5/api-reference/directives.md
docs/master/api-reference/directives.md
src/Schema/Directives/RelationDirective.php
src/Schema/Factories/FieldFactory.php
src/lighthouse.php
tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php
tests/Unit/Schema/Directives/ThrottleDirectiveTest.php
tests/Utils/Models/Role.php
tests/Utils/Models/User.php

**Changes**
Documents how to access pivot data.
None.

Document pivot access

---

CHANGELOG.md
src/Subscriptions/Storage/RedisStorageManager.php
tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php

Resolves https://github.com/nuwave/lighthouse/issues/2085

Handle invalid subscriber cache entries from redis

---

CHANGELOG.md
src/LighthouseServiceProvider.php

Resolves https://github.com/nuwave/lighthouse/issues/2057

Register artisan commands not only when running in console

---

src/Subscriptions/Storage/RedisStorageManager.php
tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php

Fix mget returning false for entries

---

CHANGELOG.md
docs/5/api-reference/directives.md
docs/master/api-reference/directives.md
src/Schema/Directives/ClearCacheDirective.php
tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php

Resolves https://github.com/nuwave/lighthouse/issues/2098

Fix definition of `@clearCache` argument `idSource`

---

CHANGELOG.md
docs/master/api-reference/directives.md
src/Schema/Directives/ConvertEmptyStringsToNullDirective.php
src/lighthouse.php
tests/Integration/Schema/Directives/ConvertEmptyStringsToNullDirectiveTest.php
tests/Integration/Schema/Directives/TrimDirectiveTest.php
tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
tests/Utils/Mutations/Upload.php

Resolves https://github.com/nuwave/lighthouse/issues/1459
**Changes**
Adds a new directive and enables it by default.
None if the config was published.

Add `@convertEmptyStringsToNull` directive

---

docs/5/subscriptions/getting-started.md
docs/master/subscriptions/getting-started.md

**Changes**
While answering a [SO question](https://stackoverflow.com/questions/71869694/remove-unsubscribed-subscriptions/71870088) I noticed the expiring subscription docs were incorrect and/or outdated. This should fix that.
Nope.

Fix expiring suscriptions docs

---

CHANGELOG.md
docs/5/api-reference/directives.md
docs/master/api-reference/directives.md
src/Console/ValidateSchemaCommand.php
src/Schema/Directives/CacheKeyDirective.php
src/Schema/Validator.php
src/Schema/Values/TypeValue.php
tests/Integration/LifecycleEventsTest.php
tests/Integration/Schema/Directives/CacheDirectiveTest.php
tests/Unit/Support/Http/Middleware/EnsureXHRTest.php

Allow `@cacheKey` on field definition

---

CHANGELOG.md
composer.json
docs/master/api-reference/directives.md
docs/master/performance/caching.md
src/CacheControl/CacheControl.php
src/CacheControl/CacheControlDirective.php
src/CacheControl/CacheControlServiceProvider.php
src/Events/StartExecution.php
src/GraphQL.php
tests/Integration/CacheControl/CacheControlDirectiveTest.php
tests/TestCase.php

Resolves https://github.com/nuwave/lighthouse/issues/2126
**Changes**
Allows setting the `Cache-Control` header through the usage of the `@cacheControl` directive.
Nope.

Add `@cacheControl` directive

---

CHANGELOG.md
docs/master/api-reference/directives.md
src/Schema/Directives/CountDirective.php
tests/Integration/Schema/Directives/CountDirectiveDBTest.php

**Changes**
- Add `columns` and `distinct` args to `@count` directive https://github.com/nuwave/lighthouse/pull/2138
- Nope

Add `columns` and `distinct` args to `@count` directive

---

CHANGELOG.md
docs/5/api-reference/directives.md
docs/5/custom-directives/argument-directives.md
docs/5/digging-deeper/relay.md
docs/5/eloquent/relationships.md
docs/master/api-reference/directives.md
docs/master/custom-directives/argument-directives.md
docs/master/digging-deeper/relay.md
docs/master/eloquent/relationships.md
src/Schema/Directives/HasManyThroughDirective.php
tests/Integration/Schema/Directives/HasManyThroughDirectiveTest.php
tests/Utils/Models/Task.php

https://github.com/nuwave/lighthouse/issues/332
**Changes**

Implement `@hasManyThrough` directive

---

src/Console/stubs/field_full.stub

Clean duplicate `@param`.
**Changes**
In PHPDoc documentation of `__invoke()` function in `field_full.stub`.
N/A

Clean duplicate `@param` in `field_full.stub`

---

docs/5/testing/phpunit.md

**Changes**
Fixes an incorrect indentation in the documentation.
No

docs: fix broken indentation

---

CHANGELOG.md
src/Schema/Types/LaravelEnumType.php

- [] ~Added or updated tests~
- [] ~Documented user facing changes~
**Changes**
Extract a method to allow easy overriding.
An internal API was changed slightly.

Allow easily overwriting enum description generation from `bensampo/laravel-enum`

---

CHANGELOG.md
src/Schema/DirectiveLocator.php
src/Schema/Directives/BaseDirective.php
src/Schema/Directives/MethodDirective.php
src/Schema/Directives/NamespaceDirective.php
src/Schema/Factories/FieldFactory.php
src/Support/Utils.php
tests/Integration/FieldMiddlewareTest.php
tests/Unit/Schema/Directives/BaseDirectiveTest.php
tests/Utils/Directives/GlobalFieldMiddlewareDirective.php

Resolves https://github.com/nuwave/lighthouse/issues/2217
**Changes**
- Set the `$definitionNode` for `field_middleware`
- Handle unset `$directiveNode`
No.

Handle unset properties in `field_middleware` directives

---

src/Execution/ModelsLoader/PaginatedModelsLoader.php
src/Support/Compatibility/LumenMiddlewareAdapter.php
src/Support/Utils.php
tests/Unit/Schema/DirectiveLocatorTest.php

Improve utils for protected access

---

CHANGELOG.md
src/Schema/TypeRegistry.php
tests/Unit/Schema/TypeRegistryTest.php

**Changes**
Interface can also implements other interfaces. It was implemented a long time ago in https://github.com/webonyx/graphql-php/issues/728 but still missed in Lightouse.

Allow interfaces to implement interfaces

---

src/Execution/ModelsLoader/PaginatedModelsLoader.php
tests/Integration/Schema/Directives/HasManyDirectiveTest.php
tests/Utils/Models/Post.php

Avoid duplicated data in relation directives with paginator with non-unique foreign keys

---

CHANGELOG.md
src/Cache/CacheDirective.php
src/Execution/BatchLoader/RelationBatchLoader.php
src/GraphQL.php
tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php
tests/Integration/Schema/Directives/LimitDirectiveTest.php

Resolves #2269 
**Changes**
- add failed test

BatchLoader fails with expired cache entry

---

tests/Integration/Validation/RulesDirectiveTest.php
tests/Integration/Validation/ValidationTest.php
tests/Integration/Validation/ValidatorDirectiveTest.php
tests/Utils/Validators/EmailCustomAttributeValidator.php

Fix Laravel 10 validation messages in tests

---

composer.json

**Changes**
This bumps the class-finder ot the newest version. According to changelog no BC's have happened, just new features was added in.

Bump class-finder

---

CHANGELOG.md
docs/master/api-reference/directives.md
src/Schema/Directives/EqDirective.php
src/Schema/Directives/WhereDirective.php
src/Schema/Directives/WhereKeyDirective.php
tests/Integration/Schema/Directives/WhereDirectiveTest.php

Resolves https://github.com/nuwave/lighthouse/issues/2302

Allow `@where` on fields

---

CHANGELOG.md
docs/master/performance/caching.md
docs/master/performance/schema-caching.md
src/Cache/CacheDirective.php
src/Exceptions/UnknownCacheVersionException.php
src/LighthouseServiceProvider.php
src/Schema/AST/ASTCache.php
src/lighthouse.php
tests/Console/CacheCommandTest.php
tests/Console/ClearCacheCommandTest.php
tests/Integration/Cache/CacheDirectiveTest.php
tests/Integration/Cache/ClearCacheDirectiveTest.php
tests/Integration/SchemaCachingTest.php
tests/TestCase.php
tests/TestsSchemaCache.php

Resolves https://github.com/nuwave/lighthouse/issues/2031

Rework config

---

README.md
src/Execution/ErrorHandler.php
src/Execution/ValidationRulesProvider.php
src/GraphQL.php
src/Schema/Directives/BaseDirective.php
src/Schema/TypeRegistry.php
src/Support/Contracts/GraphQLContext.php
src/Support/Contracts/ProvidesResolver.php
src/Support/Contracts/ProvidesSubscriptionResolver.php
src/lighthouse.php

Resolves https://github.com/nuwave/lighthouse/issues/283

Add `@api` to mark elements of our public API

---

src/CacheControl/CacheControlServiceProvider.php
src/Deprecation/DetectDeprecatedUsage.php
src/Schema/AST/ASTCache.php
src/Schema/Directives/BaseDirective.php
tests/Console/CacheCommandTest.php
tests/Console/ClearCacheCommandTest.php
tests/Unit/Auth/GuardDirectiveTest.php

https://github.com/nuwave/lighthouse/issues/2319#issuecomment-1442463338

Fix directives on type extensions

---

CHANGELOG.md
benchmarks/QueryBench.php
src/Testing/MakesGraphQLRequests.php
src/Testing/MakesGraphQLRequestsLumen.php
src/lighthouse.php

Resolves #2332 
**Changes**
- added routeParams in GraphQL-Test-Request for patterns

Adding routeParams to MakeGraphQLRequests for testing

---

CHANGELOG.md
UPGRADE.md
docs/master/subscriptions/getting-started.md
src/Subscriptions/SubscriptionRegistry.php
src/lighthouse.php
tests/Integration/Subscriptions/SubscriptionTest.php
tests/TestsRedis.php

**(Breaking) Changes**
Removes subscriptions version 1.

remove subscriptions version 1

---

CHANGELOG.md
composer.json
src/GraphQL.php
src/Subscriptions/SubscriptionRegistry.php
tests/Integration/AutomaticPersistedQueriesTest.php
tests/Integration/ErrorTest.php
tests/Integration/Validation/ValidationTest.php

https://github.com/laragraph/utils/releases/tag/v2.0.0

Allow `laragraph/utils:^2`

---

CHANGELOG.md
docs/master/api-reference/commands.md
docs/master/api-reference/directives.md
docs/master/digging-deeper/extending-lighthouse.md
docs/master/performance/n-plus-one.md
docs/master/the-basics/fields.md
rector.php
src/Console/FieldCommand.php
src/Console/InterfaceCommand.php
src/Console/LighthouseGeneratorCommand.php
src/Console/MutationCommand.php
src/Console/QueryCommand.php
src/Console/SubscriptionCommand.php
src/Console/UnionCommand.php
src/LighthouseServiceProvider.php
src/Schema/Directives/ComplexityDirective.php
src/Schema/Directives/FieldDirective.php
src/Schema/ResolverProvider.php
src/Schema/RootType.php
src/Schema/Values/FieldValue.php
src/Subscriptions/Storage/CacheStorageManager.php
src/Subscriptions/SubscriptionRegistry.php
src/Subscriptions/SubscriptionResolverProvider.php
src/lighthouse.php
tests/Integration/Schema/ResolverProviderTest.php
tests/TestCase.php
tests/Unit/Schema/Directives/FieldDirectiveTest.php
tests/Utils/Types/User/NonRootClassResolver.php

Resolves https://github.com/nuwave/lighthouse/issues/1711

Add configurable namespace to allow custom non-root type field resolvers without FQN

---

docs/.vuepress/config.js

Expose v6 docs

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
docs/4/subscriptions/client-implementations.md
docs/5/subscriptions/client-implementations.md
docs/6/subscriptions/client-implementations.md
docs/master/subscriptions/client-implementations.md
src/Federation/ASTManipulator.php
src/GlobalId/GlobalIdServiceProvider.php
src/GlobalId/NodeDirective.php
src/Pagination/PaginationManipulator.php
src/Validation/ValidatorDirective.php
src/WhereConditions/WhereConditionsServiceProvider.php
tests/TestCase.php

Resolves https://github.com/LastDragon-ru/lara-asp/issues/73
**Changes**
Register the `Node` interface in the schema earlier.
I do not think so.

Add Node interface as soon as a type uses it

---

src/Console/stubs/scalar.stub

**Changes**
- fixed typo in scalar.stub

fixed scalar.stub return value

---

CHANGELOG.md
docs/master/api-reference/directives.md
src/Schema/Directives/HideDirective.php
src/Schema/Directives/ShowDirective.php
tests/Unit/Schema/Directives/HideDirectiveTest.php
tests/Unit/Schema/Directives/ShowDirectiveTest.php

Resolves https://github.com/nuwave/lighthouse/issues/2368
**Changes**
Adds `@hide` directive to hide some parts of schema on different environments.

Add `@show` and `@hide` directives

---

CHANGELOG.md
src/Http/Responses/Stream.php
src/Schema/DirectiveLocator.php
src/Schema/Source/SchemaStitcher.php
src/Subscriptions/Authorizer.php
tests/Integration/LifecycleEventsTest.php
tests/Unit/Schema/DirectiveLocatorTest.php

Resolves https://github.com/nuwave/lighthouse/issues/2401

Ensure built-in directives have lowest priority

---

UPGRADE.md

Correct file path in UPGRADE.md

---

CHANGELOG.md
src/WhereConditions/SQLOperator.php
tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php

Resolves https://github.com/nuwave/lighthouse/issues/2427

Fix `NOT_LIKE` operator in `@whereConditions`

---

.github/workflows/format.yml
.github/workflows/validate.yml
php.dockerfile
src/Schema/Directives/RelationDirective.php
tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php
tests/Integration/Schema/Types/UnionTest.php

Also improves an error message and fixes a PHPUnit deprecation.

Use PHP 8.2 for CI

---

src/Schema/Directives/NamespacedDirective.php
tests/Integration/Schema/Directives/NamespacedDirectiveTest.php

**Changes**
Fixes NamespacedDirective to have appropriate namespace; updated resolveField to match requested change in #2478 
Duplicated NestDirectiveTest and modified it for the NamespacedDirective.

Namespaced directive

---

composer.json
src/Federation/Directives/LinkDirective.php
src/Tracing/FederatedTracing/Proto/FieldStat.php
src/Tracing/FederatedTracing/Proto/QueryLatencyStats.php
src/Tracing/FederatedTracing/Proto/Trace.php
src/Tracing/FederatedTracing/Proto/Trace/QueryPlanNode/FetchNode.php

**Changes**
Add type for `link__Import` and `link__Purpose` used in `@link` directive
None

Fix: Add types for link import & purpose

---

src/Validation/RulesGatherer.php
tests/Integration/Validation/RulesDirectiveTest.php

https://github.com/nuwave/lighthouse/issues/2488
**Changes**

Fix If the ListType field is not present, the rule directive is applied to the array itself

---

docs/6/api-reference/directives.md
docs/6/eloquent/nested-mutations.md
docs/6/security/authorization.md
docs/master/api-reference/directives.md
docs/master/eloquent/nested-mutations.md
docs/master/security/authorization.md
src/Auth/BaseCanDirective.php
src/Auth/CanResolvedDirective.php
src/Cache/CacheDirective.php
tests/Integration/ErrorTest.php
tests/Unit/Auth/CanResolvedDirectiveTest.php
tests/Unit/Auth/CanRootDirectiveTest.php
tests/Unit/Subscriptions/Storage/CacheStorageManagerTest.php
tests/Utils/Policies/UserPolicy.php

https://github.com/nuwave/lighthouse/issues/2496

Test error locations

---

src/Auth/CanDirective.php

Remove duplicate of CanArgs from definition

---

.github/workflows/validate.yml
phpstan.neon
tests/Integration/Schema/Types/InterfaceTest.php
tests/Integration/Schema/Types/UnionTest.php
tests/Unit/Schema/Directives/DeprecatedDirectiveTest.php
tests/Unit/Schema/Directives/HasManyDirectiveTest.php
tests/Unit/Subscriptions/Iterators/AuthenticatingSyncIteratorTest.php

Fix support for Laravel 11

---

docs/6/subscriptions/getting-started.md
docs/master/subscriptions/getting-started.md
tests/Integration/Schema/Directives/ThrottleDirectiveTest.php

Resolves https://github.com/nuwave/lighthouse/issues/2520
Thank you @danbka33 for firguring this out, does this look right to you?

Document adding `SubscriptionRegistry` to `octane.warm`

---

tests/Integration/Schema/Directives/EnumDirectiveTest.php

Resolves https://github.com/nuwave/lighthouse/issues/2629

Add explicit test for `@enum` directive

---

.phpstan-bootstrap.php
phpstan.neon

Warning: Trying to access array offset on null
src/Schema/AST/ASTCache.php:28
**Changes**

Fix PHPStan error

---

src/Execution/Arguments/ArgumentSet.php
tests/Unit/Execution/Arguments/ArgumentSetTest.php

Add `exists` method to `ArgumentSet`
**Changes**

feat: Add exists method to ArgumentSet

---

composer.json
tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
tests/Utils/Models/User.php
tests/database/factories/UserFactory.php
tests/database/migrations/2018_02_28_000002_create_testbench_users_table.php

This PR exists as a demo for an issue: https://github.com/nuwave/lighthouse/issues/2699

POC: Create a failing test to demo filtering BETWEEN with variables
